### ISSUE TITLE
Would it make more sense to use `slide_int()` rather than `slide_vec()`?

### ISSUE THREAD

**Issue by DavisVaughan** [hadley/r4ds#1011]
Since it maps more directly to purrr (there isn't a `map_vec()` but there is `map_int()`), and all your examples are of summing up an integer vector?

https://github.com/hadley/r4ds/blob/9f8161c86ba33a88dda8e02a1a639a487ebdca6d/numbers.Rmd#L346-L353

**Comment by hadley** [comment]
But isn't `slide_vec()` more likely to work with any type of `x`? i.e. I'd prefer not to get into a discussion of vector types at this point in the book.

**Comment by DavisVaughan** [comment]
Yea, if you haven't introduced vector types then what you have makes sense
