### ISSUE TITLE
Edit this page still not fixed from #994

### ISSUE THREAD

**Issue by onlyphantom** [hadley/r4ds#1015]
It seems like the "Edit this page" links at the sidebar of each chapter still points to the old 'master' branch. 

The “view source” link also points to the “master” branch but it gets redirected to main so its functionality isn’t affected. 

The edit links though would lead to a 404 / broken. An earlier PR #994 didnt seem to have resolve that issue.

**Comment by zhugejun** [comment]
It looks like the links are broken again after converting to Quarto book.

**Comment by hadley** [comment]
@zhugejun they work for me

**Comment by zhugejun** [comment]
Does it mean that the website https://r4ds.had.co.nz/ is not up to date?

**Comment by hadley** [comment]
@zhugejun that’s for the first edition, so no.
