### ISSUE TITLE
Small issue in Chapter 11: the book codes claim to be calculating "scheduled" times, when it's actual times of nyc flights

### ISSUE THREAD

**Issue by tshdesmond** [hadley/r4ds#104]
In Chapter 11 Dates and times, under the section "11.1.0.1 The structure of dates and times", near the end of this section:

"This gives us a way to calculate the scheduled departure and arrival times of each flight in flights." together with the following code block.

I think this part is in fact calculating the **actual** departure and arrival times, not the **scheduled** times, of the nyc flights data.

Just thought I should highlight this. Thank you.

**Comment by hadley** [comment]
Thanks - the data has changed since we wrote that chapter and we'll update v. soon.
