### ISSUE TITLE
Minor edit in data-visualize.qmd

### ISSUE THREAD

**Issue by kevinxperese** [hadley/r4ds#1044]
Line 91 in data-visualize.qmd describes a positive relationship, when it would be clearer for it to describe a negative relationship, as specified in the previous line: https://github.com/hadley/r4ds/blob/main/data-visualize.qmd#L90-L91.

I would propose deleting line 91 and replacing it with "In other words, cars with small engines have higher fuel efficiency and, in general, as engine size increases, fuel efficiency decreases."

If that change sounds reasonable, I'll gladly open up a pull request for the change.

**Comment by hadley** [comment]
Yes, that sounds good and a PR would be welcomed.
