### ISSUE TITLE
read_csv inline csv file examples have a strange format in the second edition

### ISSUE THREAD

**Issue by xiaoxi-david** [hadley/r4ds#1046]
Although copy and paste still works perfectly, it is more difficult to read some read_csv examples in the second edition because they have a strange format.

2nd edition:
![2ndversion](https://user-images.githubusercontent.com/24303680/174581164-84b46d16-ece9-49bb-bdc2-a50b22f6c540.png)
https://r4ds.hadley.nz/data-import.html

1st edition:
![1stversion](https://user-images.githubusercontent.com/24303680/174581182-529b73e1-51ab-4709-83f6-7c1d7e2c28ea.png)
https://r4ds.had.co.nz/data-import.html

Opera, Microsoft Edge and Firefox on my Windows 10 laptop all display the second edition with the strange format.

**Comment by hadley** [comment]
Known issue with downlit: https://github.com/r-lib/downlit/issues/139
