### ISSUE TITLE
Update GitHub contribution link from .rmd to .qmd

### ISSUE THREAD

**Issue by now-im** [hadley/r4ds#1049]
As all the contents has basically moved from Rmd to Qmd, reference contribution link needs to be updated too.

For example:
![Screenshot_20220623_022731](https://user-images.githubusercontent.com/22009014/175130491-ae2dd8d3-2563-4af5-aa79-0e154728b87d.png)

**Comment by hadley** [comment]
You can only edit the 2nd edition of the book: https://r4ds.hadley.nz
