### ISSUE TITLE
Non-tidy data section, link to blog post by Jeff Leek is not working

### ISSUE THREAD

**Issue by anjalisilva** [hadley/r4ds#1051]
The link provided on Chapter 12, under Non-tidy data section [https://r4ds.had.co.nz/tidy-data.html](url) is not working. The link provided is: http://simplystatistics.org/2016/02/17/non-tidy-data/

Correct link should be https://simplystatistics.org/posts/2016-02-17-non-tidy-data/

**Comment by hadley** [comment]
This is now a fuller section so no longer links out to the blog: https://r4ds.hadley.nz/data-tidy.html#untidy-data
