### ISSUE TITLE
feedback on "Data rectangling" chapter

### ISSUE THREAD

**Issue by stefanoanzani** [hadley/r4ds#1052]
Hi, I've seen [a tweet](https://twitter.com/hadleywickham/status/1544470643047006208) from @hadley mentioning this chapter and I gave it a read, as it would have helped me a lot in my past year of fighting with json objects 😄 

To be honest I have more questions than feedback, mostly related to my experience with rectangling, but I hope they might still be helpful.

### Performance of  `unnest_*` functions vs `map_*`
Is there any difference between using `unnest_wider` and then `select`ing the columns that I need, versus using a series of `map_*` calls to extract directly the things that I need? 
My code was really slow, I tried this to make things faster and it worked, but I changed more than one thing at a time, so I'm not sure if this actually makes any difference.

### Handling `NULL` values with `map_*`
Using `map_*` variants to extract information with a vector of names gave me a new problem, missing elements in the lists were returning `NULL` and the `map_*` variants give an error. 
It took me a while to discover the `.default` argument, which solves most of my issues, my previous solution was to extract with `map` and then coercing the result with `as.*` functions. 

Since this was so hard to discover/solve, I fear that I might be using a suboptimal (if not off label) strategy. And if it's not suboptimal I think that `.default` deserves a bit more exposure 😅 

### Usage of `hoist`
I've seen `hoist` mentioned a couple of times in the past but I've never really understood how it works. The example in the chapter is the first time that I understand it a bit more, but it's still quite obscure.  

Could I use it instead of the series of `map_*` calls?
This is an example of what I do now to make a table from a `jsonlite` list, in this case each element is in the first level, but there are cases where I pass a vector of names for nested elements.

```
info_sessioni<-tibble::tibble(
    ss_id = purrr::map_chr(sessions_l, "id"),
    subject_id = purrr::map_chr(sessions_l,"subject_id", .default = NA_character_),
    n_answers = purrr::map_int(sessions_l, "n_answers", .default = NA_integer_),
    started_on = purrr::map_chr(sessions_l, "started_on", .default = NA_character_),
    last_action = purrr::map_chr(sessions_l, "last_action", .default = NA_character_),
    completed_on = purrr::map_chr(sessions_l, "completed_on", .default = NA_character_),
    params_data = purrr::map_chr(sessions_l, "data", .default = "{}"),
    user_agent = purrr::map_chr(sessions_l, "user_agent",.default = NA_character_)
  )
```

I see that a bunch of new chapters are about topics that I learned recently about on my own.
I understand that it's not exactly the feedback on the contents that you were looking for, but if this kind of feedback is useful in any way I can open other issues, since I'll be reading the new chapters anyway 😄

**Comment by hadley** [comment]
Thanks for the feedback!

* We haven't don't much optimisation of `unnest_*()` and friends yet, so it wouldn't surprise me that `map_*` is faster.

* `unnest_*()` makes most of the struggles of dealing with absent components go away 😄 

* Yes, that's much easier with `hoist()`. Something like this: 
   ```R
   df <- tibble(json = sessions_l)
    df |> hoist(json, 
      ss_id = "id",
      "subject_id"
      "n_answers",
      "started_on",
      "last_action",
      "completed_on",
      "data",
      "user_agent",
    ) |>
    mutate(data = coalesce(data, "{}"))
    ```
