### ISSUE TITLE
1st edition updates

### ISSUE THREAD

**Issue by hadley** [hadley/r4ds#1053]
* Link to translations from main page
* Remove edit this page link

**Comment by david-romano** [comment]
With the "Edit this page" link removed (it still appears in book but link sends to 404 page), what is the best way to suggest edits?

**Comment by hadley** [comment]
There's no point in suggesting edits to the 1st edition; instead suggest them to the second: https://r4ds.hadley.nz

**Comment by david-romano** [comment]
Thanks -- I've been using the link https://r4ds.had.co.nz/index.html, which
still points to the 1st edition, so didn't realized the 2nd edition was
available.

**Comment by david-romano** [comment]
Oh, and that's where the link in the READ.ME for hadley/r4ds points
(meaning, to the 1st edition).
