### ISSUE TITLE
New r4ds documentation 

### ISSUE THREAD

**Issue by fralfaro** [hadley/r4ds#1056]
Hi everyone. I find a problem with this documentation. I think that each chapter/section should  be reproducible, for example, with google colab (with R kernel). I have developed an alternative documentation with mkdocs, google colab and github actions. This repository lives at [fralfaro/r4ds-book](https://github.com/fralfaro/r4ds-book) (documentation: [link](https://fralfaro.github.io/r4ds-book/)). In each chapter there is a jupyter notebook connected with google colab. I hope this is a good alternative.

**Comment by hadley** [comment]
Each chapter already is reproducible? I'm not sure what the advantage of your approach is.

**Comment by fralfaro** [comment]
Hi Hadley, my approach is as follows:

In each section, there is a logo called **Open in Colab**, if you click on this logo, you will be redirected to Google Colab with this section, where you can reproduce the same code.

The goal is that you can use Google Colab (with R kernel) to replicate each section instead of installing all the R packages on your computer. This approach is more friendly to novice users, since installing R packages can be complex for many reasons: operating system, previous version of R installed, etc.

![img_01](https://user-images.githubusercontent.com/18752583/183444466-2bdc6af5-7445-47cb-9114-08247a2f819a.png)


![img_02](https://user-images.githubusercontent.com/18752583/183444495-6b0f3f57-6bfb-4b61-ae99-e20b10cef85f.png)

**Comment by hadley** [comment]
Got it, thanks for sharing.
