### ISSUE TITLE
Update name of YAML

### ISSUE THREAD

**Issue by TangoYankee** [hadley/r4ds#1076]
The name for YAML has changed from its original meaning. The 'R communication' chapter lists the legacy name.

Name as listed in r4ds: [yet another markup language](https://github.com/hadley/r4ds/blob/1d0902c9bf51c7832c2a932b8bbdc0749978457d/rmarkdown.qmd#L400)

Name as listed on the YAML Site: [YAML Ain't Markup Language](https://yaml.org/)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
