### ISSUE TITLE
wrong list names in diagrams/lists-pmap-named.png ?

### ISSUE THREAD

**Issue by martin-raden** [hadley/r4ds#1090]
Hi,

while studying R4DS (1st edition) I find in the pmap section
 https://r4ds.had.co.nz/iteration.html#mapping-over-multiple-arguments

the code 

```{R}
args2 <- list(mean = mu, sd = sigma, n = n)
args2 %>% 
  pmap(rnorm) %>% 
  str()
```

but the image (here taken from the github repo)

![](https://raw.githubusercontent.com/hadley/r4ds/main/diagrams/lists-pmap-named.png)

shows in the `arg2` visualization the names of the original vectors instead of the names `mean`, `sd` and `n` used when `args2` was defined.

Is this  a bug or a "feature" ? :-)

Intuitively, I would expect the names from the list rather than the vector names within the plot.

If you wanted to visualize where the data came from, it might be best to put the list names on top of the vector columns within the `arg2` visualization.

Hope that makes sense.

Best,
Martin

**Comment by hadley** [comment]
This diagram is going away in 2e.
