### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by erwinlares** [hadley/r4ds#1095]
The very last line of section 3.1 Coding basics has a typo. "giveyoureyesabreak" is missing spaces.

**Comment by mine-cetinkaya-rundel** [comment]
That's intentional 😄 

> Code is miserable to read on a good day, so giveyoureyesabreak and use spaces.

**Comment by erwinlares** [comment]
Ha! Good call

---
Erwin Lares

Research Cyberinfrastructure Consultant
Division of Information Technology
1210 West Dayton St
University of Wisconsin-Madison
Madison, Wisconsin 53706



From: Mine Cetinkaya-Rundel ***@***.***>
Date: Tuesday, September 20, 2022 at 12:08 PM
To: hadley/r4ds ***@***.***>
Cc: ERWIN LARES ***@***.***>, Author ***@***.***>
Subject: Re: [hadley/r4ds] typo (Issue #1095)

That's intentional 😄

Code is miserable to read on a good day, so giveyoureyesabreak and use spaces.
