### ISSUE TITLE
What is a grouped data frame?

### ISSUE THREAD

**Issue by hadley** [hadley/r4ds#1102]
https://sta199-f22-1.github.io/hw/hw-3.html#exercise-2

**Comment by gregorywaynepower** [comment]
I think you may need to ask your professor on that one. group_by() behaves similar to the "GROUP BY" statement in SQL, but applies it to your Dataframe. [Here's a link to the documentation and if you scroll to Examples, this should provide more clarity.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)

**Comment by MattCowgill** [comment]
@gregorywaynepower have a look at who you're responding to...

**Comment by gregorywaynepower** [comment]
Ooooops, I may have just put my entire foot in my mouth. 🙃

**Comment by mine-cetinkaya-rundel** [comment]
We just have this here as a potential exercise for the relevant section 😀
