### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by PKSim1** [hadley/r4ds#1111]
This link is not working for me: https://github.com/hadley/r4ds/tree/master/rmarkdown

**Comment by mine-cetinkaya-rundel** [comment]
As we're updating the book to introduce Quarto instead of RMarkdown, that link has been updated to https://github.com/hadley/r4ds/tree/main/quarto. Where in the book did you come across the link?

**Comment by hadley** [comment]
@mine-cetinkaya-rundel this is a duplicate of #1053
