### ISSUE TITLE
Minor comments to the quarto chapter

### ISSUE THREAD

**Issue by mpaulacaldas** [hadley/r4ds#1117]
Hi @mine-cetinkaya-rundel! I'm responding to your call for feedback on the quarto chapter. These are minor. I think the chapter is great! I particularly liked the additions to the YAML header section 😄 

Now, for my comments:

- [x] Though I think this ordering was intentional, the section on the _source editor_ still reads as if it should come before the one from the _visual editor_. Mostly, I think this is because the visual editor section mentions [Pandoc markdown](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L146), but it's the [next section](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L182-L185) that explains what it is.
- [x] The _caching_ section seems a bit out-of-place. In terms of logical order, I think global options and inline code are more common, but presented later. I see you are moving _Figures_ and _Tables_ up in the document hierarchy (from an H3 to an H2 heading), so perhaps the same would make sense for caching.
- [x] It could be worth a mention that one common source of rendering errors can come from repeating the same label in different chunks. You could add this either in the "chunk label" or "troubleshooting" sections, or as an exercise (I think the certified RStudio trainers test had something like this).
- [x] Some of the examples in the chapter [use underscores in the chunk labels](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L408) instead of the [suggested dashes](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L274-L275). I think the motivation behind this suggestion [was this hard-to-debug issue when generating PDFs](https://yihui.org/en/2018/03/space-pain/). 
- [x] [The qmd example at the beginning of the chapter](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L50-L62) doesn't have any text formatting, unlike what is mentioned in the third bullet-point in the text right below.
- [x] A couple of places still use _knit_ instead of _render_.
- [x] This [cross-reference](https://github.com/hadley/r4ds/blob/9bba5cb695105d95f427cba306e98cde0eb11979/quarto.qmd#L353) should be to the _Figures_ section in the same document.

I hope these are helpful, and congrats on this new edition! It's shaping up very nicely.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you so much @mpaulacaldas!

**Comment by mpaulacaldas** [comment]
My pleasure @mine-cetinkaya-rundel!
