### ISSUE TITLE
Webpage Github Link broken 

### ISSUE THREAD

**Issue by vasnt** [hadley/r4ds#1135]
github links ( https://github.com/hadley/r4ds/edit/master/index.Rmd)- located don top right on webpage (https://r4ds.had.co.nz/index.html) are broken.

**Comment by r-31415** [comment]
Add to that the links to amazon books in https://r4ds.had.co.nz/exploratory-data-analysis.html#learning-more

**Comment by hadley** [comment]
Duplicate of #1053
