### ISSUE TITLE
Minor points to be clarified about filter() and subset()

### ISSUE THREAD

**Issue by dracodoc** [hadley/r4ds#114]
In `4.3 Filter rows with filter()`, 

> filter() works similarly to subset() except that you can give it any number of filtering conditions, which are joined together with &.

Does it actually mean "you can give it any number of filtering conditions separately, which are joined together with & automatically behind scene"? Because if you are giving one huge expressions with multiple conditions joined, it should work with both filter() and subset().

In `4.3.2 Logical operators`

> Multiple arguments to filter() are combined with “and”.

Should it be this?

> Multiple arguments to filter() are combined with “&”.

**Comment by fereshtehRS** [comment]
I was also confused by this sentence in: `4.3 Filter rows with filter()`,
```
filter() works similarly to subset() except that you can give it any number of filtering conditions, which are joined together with &.
```

**Comment by hadley** [comment]
That whole section has now been rewritten. Thanks for pointing out the confusion!
