### ISSUE TITLE
Suggestion for preface for 2e // should linked functions be underlined?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [hadley/r4ds#1143]
How about another bullet point about `code-link` feature in the online version? Something like

- If reading the online version of the book, you can click on any R function and it will take you to the function documentation.

... or something along those lines.

I think we had this in 1e after @hadley switched it over to bs4book but not at the time 1e was first published.

I thought about this because it's not super clear that those functions are clickable links, they're not underlined currently. Maybe just implementing underlining would be good enough and additional text not needed?

**Comment by hadley** [comment]
Looks like the stripping of underlines was an accidental change, so I restored it.
