### ISSUE TITLE
Notes on the spreadsheets chapter

### ISSUE THREAD

**Issue by jennybc** [hadley/r4ds#1183]
Chapter looks great! I just made a few observations here, but definitely don't necessarily think they all need to be acted on. Take what's useful and ignore the rest.

> xlsx and XLConnect can also be used for reading data from and writing data to Excel spreadsheets.

I think openxlsx is actually the 2nd most used "excel-handling" package, after readxl so I would sort of expect to see it here. (Ecosystem-wise, I think it's also important re: writing rich spreadsheets, but maybe you don't get into that. Update: I now see that you do. So maybe just mention openxlsx here and say it'll come up later.)

> The column names are all over the place.

Presumably you considered this, but providing a function (like `janitor::clean_names()`) might be worth a mention as something that scales better than hard-wiring actual names.

> By default, only "" (empty string, or, in the case of reading from a spreadsheet, an empty cell) is recognized as an NA.

Technically that's not true. True "spreadsheet NAs" are also read as `NA`. For example, if a cell has the formula `=NA()`, which displays as `#N/A`, it gets read as `NA`. But I could understand if you don't want to get into that.

> The syntax is a bit different, though.

Re: col type specification. This is such a nice way of saying "the syntax is much more awkward" :disappointed_relieved:

> It took us multiple steps and trial-and-error to load the data in exactly the format we want, and this is not unexpected. Data science is an iterative process. 

I think spreadsheets, in particular, tend to be very weird and dirty because humans have usually interacted with them, with their bare and unwashed hands.

> That might be tempting, but it’s strongly not recommended as Excel can modify certain types of data upon launch with no way to track this change.

I feel like this is too much FUD and it's too discouraging re: looking at the actual data. Presumably you've already got an `.xlsx` file, so opening it, in most cases is relatively low risk. The genes as dates problem occurs more when data is first going into a spreadsheet. I.e. if you've already got an `.xlsx` that you need to read, it's rare that opening it in Excel is going to make things *worse*. (There *are* some things where Excel changes what's on disk when you merely open a file, but I wouldn't dwell on that too much.)

I also think it's just impractical to think that people aren't going to open an Excel file in Excel. It's like "just say no".

> Reading individual sheets

I would say "worksheet" here and lots of other places. But you're probably saying "sheet" because the argument is `sheet`.

> `read_excel(deaths_path, range = cell_limits(c(5, 1), c(15, 6)))`

I'm not sure `cell_limits()` is worth showing. It's mostly useful internally and mostly because it allows for partially open rectangles. I guess if you decide to show it, that would be the thing to mention? But I'd probably suppress it.

> A cell can be one of five things ... A currency

This seems odd to me and it's really not true. There isn't such a cell type and I would leave it off, for parallelism. It's just like a date time, where the underlying cell type is numeric and then the display is controlled by a format. Another example would be a percentage. Or even a number where we including comma as the grouping mark (between the thousands) or parentheses to indicate a negative number.

> These differences between how the underlying data are stored vs. how they’re displayed can cause surprises when the data are loaded into R.

This is a VERY important point. What you see (in Excel) is NOT what's on disk.

> You can do this with `gs4_auth()` ...

Perhaps worth pointing out that you can sit back and let googlesheets4 prompt you for auth. You only need to call `gs4_auth()` explicitly if you have some non-default goals (like specifying the email or whatnot).

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
