### ISSUE TITLE
Not datasets

### ISSUE THREAD

**Issue by cristinarodriguezarribas** [hadley/r4ds#1189]
In this two sections: 
6.3.3 Many variables in column names
6.3.4 Data and variable names in the column headers

I can't find the datasets: who2 and household.

**Comment by mine-cetinkaya-rundel** [comment]
Both of these are in the development version of tidyr package, so they will be in the released version soon too: 

- https://tidyr.tidyverse.org/dev/reference/who.html
- https://tidyr.tidyverse.org/dev/reference/household.html
