### ISSUE TITLE
Typo in 8.3.3

### ISSUE THREAD

**Issue by zhzhou** [hadley/r4ds#1190]
It's a great book. Thanks for your share.

There are some typos which are maked in bold.

1. The third paragraph of 8.3.3,
"[col_integer()] reads integers. We distinguish **because** integers and doubles in this book because they’re functionally equivalent,"

2. The first paragraph of 16.3, 
"We’ll show you how to do this with [str_c()] and [str_glue()] and how you can **you** use them with [mutate()]."

3. In 17.2,
"Character classes are defined by [] and let you match a set **set** of characters"

4. In 17.3.2,
"Use [str_to_lower()] to convert the names to lower case: str_count(str_to_lower(name), "[aeiou]"). **You learned about this function in [Section 16.6]**." Right now, str_to_lower is not included in 16.6.

**Comment by zhzhou** [comment]
Another typo in the first paragraph of 16.3, i.e.,

"We’ll show you how to do this with [str_c()] and [str_glue()] and how you can **you** use them with [mutate()]."

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for catching these and reporting! I've updated them in the text.
