### ISSUE TITLE
Typos in Chapter 2

### ISSUE THREAD

**Issue by Allison0802** [hadley/r4ds#1191]
Thank you for such a wonderfull book! I just finished chapter 2 and here are 2 typos I found:

The ninth exercise problem of 2.2 has some markdown texts left.

The second paragraph of 2.6 is "This will save your plot to your working directory, a concept you’ll learn more about in ?sec-workflow-scripts." I'm guessing "?sec-workflow-scripts" should have been a link to another chapter?

Can't wait to see the complete book!

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for catching and reporting! I've updated them in the text.
