### ISSUE TITLE
include palmerpenguins in "other packages"

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1192]
The current iteration of https://r4ds.hadley.nz/intro.html#other-packages shows the following "other packages":

```r
install.packages("nycflights13", "gapminder", "Lahman")
```

https://github.com/hadley/r4ds/blob/96ef4b2d3b422f5243705f0b69a0e862635e9b6b/intro.qmd#L218-L226

However, soon after, in the [Data visualization](https://r4ds.hadley.nz/data-visualize.html#prerequisites) section, we are asked to use `palmerpenguins`, without suggesting its installation:

```r
library(palmerpenguins)
```

https://github.com/hadley/r4ds/blob/96ef4b2d3b422f5243705f0b69a0e862635e9b6b/data-visualize.qmd#L48-L52

This `library` statement is just after a similar `library(tidyverse)` statement, which repeats the installation instructions given previously in the introduction.

**Comment by mine-cetinkaya-rundel** [comment]
I've added it now, thank you!
