### ISSUE TITLE
exercise (2.2.5-8) should suppress warnings

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1193]
The following exercise includes the emitted warnings in the rendered book:

https://github.com/hadley/r4ds/blob/96ef4b2d3b422f5243705f0b69a0e862635e9b6b/data-visualize.qmd#L366-L382

The result:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/362187/209210008-40406569-25e0-4d3e-abaf-d367d2182d12.png">

The code producing this graph probably should hide the warnings, as done elsewhere.

````markdown
```{r}
#| warning: false
# ...
```
````

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
