### ISSUE TITLE
exercise (2.2.5-8) includes markup

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1194]
This exercise:

https://github.com/hadley/r4ds/blob/96ef4b2d3b422f5243705f0b69a0e862635e9b6b/data-visualize.qmd#L384-L386

is currently rendering with `{.cell}` and other markup remnants.

The current result from https://r4ds.hadley.nz/data-visualize.html#exercises

<img width="784" alt="image" src="https://user-images.githubusercontent.com/362187/209211059-4ac238c0-4119-4eaa-a9cc-2b2a7608bbda.png">

The next exercise, which also includes code for study, appears to render correctly.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks! This is also mentioned in #1191 and will be fixed with #1204.
