### ISSUE TITLE
Question about labs() in section 2.2.4

### ISSUE THREAD

**Issue by leecreighton** [hadley/r4ds#1199]
Section 2.2.4 has the following as its culmulating code for the desired graph:

[ggplot](https://ggplot2.tidyverse.org/reference/ggplot.html)(penguins, 
       [aes](https://ggplot2.tidyverse.org/reference/aes.html)(x = flipper_length_mm, y = body_mass_g)) +
  [geom_point](https://ggplot2.tidyverse.org/reference/geom_point.html)([aes](https://ggplot2.tidyverse.org/reference/aes.html)(color = species, shape = species)) +
  [geom_smooth](https://ggplot2.tidyverse.org/reference/geom_smooth.html)() +
  [labs](https://ggplot2.tidyverse.org/reference/labs.html)(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", 
    y = "Body mass (g)",
    color = "Species", 
    shape = "Species"
  )

It is not obvious nor explained why color= and shape= parameters are used in the labs section. Additionally, when deleted, the graph doesn’t change. 

I’m not saying they need to come out, but as a newcomer to tidyverse, there’s a lot in this chapter and figuring out why and where to put those parameters is not obvious.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the question and comment! `color` and `shape` update the label of the legend. I've added some text to clarify this as well.
