### ISSUE TITLE
who2 dataset is missing

### ISSUE THREAD

**Issue by leecreighton** [hadley/r4ds#1206]
In Chapter 6 Data Tidying, the second example uses a dataset names who2. As far as I can tell, there is no who2 data set in any tidyverse package nor in R's default datasets.

There is a who dataset in tidyr, and in its vignette (see https://tidyr.tidyverse.org/articles/pivot.html) there are steps to tidy it, including an intermediate step that generates a who2 data set. However, this is also not the who2 data set used in the example.

**Comment by hadley** [comment]
You need the dev version of tidyr.
