### ISSUE TITLE
exercise 2.5.5 2: third variable request ambiguously worded

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1209]
The current text of 2.5.5 exercise 2: 

> Make a scatterplot of hwy vs. displ using the mpg data frame. Then, map a third, numerical variable to color, size, and shape. How do these aesthetics behave differently for categorical vs. numerical variables?

As worded, this made me feel like a single numeric variable could be mapped to all three of these aesthetics.

```r
ggplot(mpg, aes(x = hwy, y = displ)) +
  geom_point(aes(color = cyl, size = cyl, shape = cyl))
```

This approach errs, as a continuous variable cannot be used for `shape`.

```
Error in `geom_point()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `scale_f()`:
! A continuous variable cannot be mapped to the shape aesthetic
ℹ choose a different aesthetic or use `scale_shape_binned()`
Run `rlang::last_error()` to see where the error occurred.
```

Is the intent to gather more experience building graphs or to show that some aesthetics cannot be used for continuous variables? Could the exercise be reworded to first encourage successful plot building before suggesting experimentation?

**Comment by hadley** [comment]
Maybe it could be:

> Next, map a third, numerical variable to color, then size, then colour and size, then shape. How do these aesthetics behave differently for categorical vs. numerical variables?

**Comment by aronatkins** [comment]
That suggestion looks great to me. I especially like the use of color and colour!

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, updated, though not with the UK spelling.
