### ISSUE TITLE
2.6 Saving your plots includes warning output

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1210]
https://r4ds.hadley.nz/data-visualize.html#sec-ggsave

As currently rendered:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/362187/210606768-5f757edb-dc8d-4cc6-8def-4b4c9adce23b.png">

This output includes the warnings:

```
#> Warning: Removed 2 rows containing missing values (`geom_point()`).

#> Saving 6 x 4 in image
#> Warning: Removed 2 rows containing missing values (`geom_point()`).
```

Are these warnings intentionally included? Other examples using the `penguins` data set do not include warnings about the removed rows, such as the example showing three or more variables at https://r4ds.hadley.nz/data-visualize.html#three-or-more-variables.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
