### ISSUE TITLE
nit: environment pane example inconsistent with variables in code

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1211]
The Environment pane screenshot included in https://r4ds.hadley.nz/workflow-basics.html includes the variables `r_rocks`, `this_is_a_really_long_name`, `x`, and `y`. The image shows a `y` variable that is not used in the code examples, and is missing the `primes` variable that is used.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/362187/210610496-44b4c6f3-b388-44f7-8946-0a16ceaf4c81.png">

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
