### ISSUE TITLE
data_frame "no partical matching"

### ISSUE THREAD

**Issue by rlzijdeman** [hadley/r4ds#122]
Hi, I have difficulty understanding the last bullet in 4.1. There's an argument that unlike a data.frame, an object of type tbl_df does not do partial matching. But the output shows it actually does partial matching. I had expected, that:

```
df <- data.frame(abc = 1)
df$a
```
 would have resulted in 1.

And that
```
df2 <- data_frame(abc = 1)
class(df2)
df2$a 
```
would resulted in NULL.

Actually both, result in: 1

Thanks, Richard

**Comment by hadley** [comment]
That's because I've written the text for a version of dplyr that isn't released yet. Will resolve itself soon.
