### ISSUE TITLE
Seems awkward: 2.3 ggplot2 calls

### ISSUE THREAD

**Issue by cm1776** [hadley/r4ds#1220]
"The first two arguments to ggplot() are data and mapping, in the remainder of the book, we won’t supply those names."

**Comment by hadley** [comment]
I don't understand what you're asking.

**Comment by Abinashbunty** [comment]
Exactly. @cm1776 It is just written as a tip that you can omit the names of arguments. You can omit the names and directly pass the argument itself. The R interpreter understands the code without explicitly writing the names of arguments.
