### ISSUE TITLE
6.3 Pivoting - Data without Sources

### ISSUE THREAD

**Issue by Ajsomaduroff** [hadley/r4ds#1221]
Hello! I'm working my way through the book (thank you so very much for this amazing tool) and have found that there is no explanation for getting the following datasets:

**6.3.3**
who2

**6.3.4**
household

**6.3.5**
cms_patient_experience

If this is intentional, please disregard my issue. While I have been enjoying following along through the book, I understand some sections may be for reading only and this may be one of them. Thank you, again, for all the time and energy you've spent putting this book together.

Best,
Austin

**Comment by hadley** [comment]
They're all in the dev version of tidyr
