### ISSUE TITLE
R for Data Science (2e)

### ISSUE THREAD

**Issue by ruinw** [hadley/r4ds#1228]
6.2 Tidy data

# Compute cases per year
table1 |>
  [count](https://dplyr.tidyverse.org/reference/count.html)(year, wt = cases)

when i run it,there will be

table1 |>
+   count(year, wt = cases)
Error in count(table1, year, wt = cases) : 
  Argument 'x' is not a vector: list

**Comment by hadley** [comment]
You probably need to update the vctrs package.
