### ISSUE TITLE
Red-green color blindness and default penguin colors

### ISSUE THREAD

**Issue by HeartlandNetwork** [hadley/r4ds#1243]
Hello:
I am really enjoying the second edition of your book. However, I am red-green color blind and I am not able to distinguish between Adelie and Chinstrap penguins in the default color assignment in several ofthe ggplots data visualizations in this chapter.  For your final version of the digital version of this book, are you planning to address what we call in the U.S.,  "508 compliance"? This includes requirements for web pages and online products that address disability needs for color assignment, image intensity, screen readers and other web features.  

More info can be found here:
https://www.section508.gov/
https://508-compliance.org/

Thanks,

Gareth Rowell
gareth_rowell@nps.gov
https://github.com/HeartlandNetwork

**Comment by HeartlandNetwork** [comment]
I found this reference below that specifically deals with color-blindness and the default ggplot2 colors. Its also an O-Reilly pub, as you probably already know. Maybe you could include this reference early in your chapter 2.

http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette

**Comment by hadley** [comment]
We touch on this briefly in https://r4ds.hadley.nz/communication.html#scales, but we should bump up the detail a bit do a call ahead to this section when we first hit the problem.

**Comment by HeartlandNetwork** [comment]
Looks like 508 compliance in R deserves its own project. This is the only thing I found, not sure whether you want to cite it, tho.

http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette

**Comment by hadley** [comment]
There's more info in https://ggplot2-book.org/scale-colour.html#colour-blindness.

**Comment by HeartlandNetwork** [comment]
Super, Thank you!!

**Comment by hadley** [comment]
Re-opening just so we remember to point to these resources in R4DS.

**Comment by HeartlandNetwork** [comment]
You may have already seen this, 

[CENTERING ACCESSIBILITY 
IN DATA VISUALIZATION](https://www.urban.org/sites/default/files/2022-12/Do%20No%20Harm%20Guide%20Centering%20Accessibility%20in%20Data%20Visualization.pdf)
