### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by davidrsch** [hadley/r4ds#1253]
Hey, when running: `devtools::install_github("hadley/r4ds")` I get the following error:
```
Downloading GitHub repo hadley/r4ds@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/hadley/r4ds/tarball/HEAD'
```
My OS is windows 10, I am using RStudio version 2022.12.0-353 and R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"

**Comment by hadley** [comment]
Why are you running that code? R4DS is a book, not a package.

**Comment by davidrsch** [comment]
Because I found several errors while rendering like in EDA.qmd:

```
diamonds2 <- diamonds |> 
      mutate(y = if_else(y < 3 | y > 20, NA, y))
````
returns:
```
Error in `mutate()`:
! Problem while computing `y = if_else(y < 3 | y > 20, NA, y)`.
Caused by error in `if_else()`:
! `false` must be a logical vector, not a double vector.
Backtrace:
 1. dplyr::mutate(diamonds, y = if_else(y < 3 | y > 20, NA, y))
 6. dplyr::if_else(y < 3 | y > 20, NA, y)
```
So I thought it would be necessary to update to the developer versions of the packages that the book uses. So I follow the instructions in the description:

> The R packages used in this book can be installed via

>`devtools::install_github("hadley/r4ds")`

**Comment by davidrsch** [comment]
I could fix the error commented previously (line 289 of EDA.qmd)  by changing it to:
```
diamonds2 <- diamonds |> 
      mutate(y = ifelse(y < 3 | y > 20, NA, y))
```
But I think that the goal is use the `if_else()` function from the dplyr package.

**Comment by hadley** [comment]
Oh, oops, I'll fix the instructions in the README.

You can get the dev version of dplyr with `devtools::install_github("tidyverse/dplyr")`
