### ISSUE TITLE
Error, perhaps, Section 12.4

### ISSUE THREAD

**Issue by bfletcherjohnson** [hadley/r4ds#1254]
Section 12.4 Unusual values, second code box.
diamonds2 <- diamonds |> 
  mutate(y = if_else(y < 3 | y > 20, NA, y))

I get an error:
! Problem while computing `y = if_else(y < 3 | y > 20, NA, y)`.
Caused by error in `if_else()`:
! `false` must be a logical vector, not a double vector.

if_else does not like it that NA is a logical vector whilst y is a double vector (right?)

If I change "if_else" to "ifelse" the code executes as described in text; I get the Warning:  Removed 9 rows and the plot shown in the text.

**Comment by davidrsch** [comment]
No it isn't an error. I encountered the same issue and solved as suggested by @hadley installing the development version of dplyr 
```
devtools::install_github("tidyverse/dplyr")
```
Check issue #1253

**Comment by hadley** [comment]
This is now the CRAN version of dplyr 😄
