### ISSUE TITLE
if_else() function is giving error in section 12.4 

### ISSUE THREAD

**Issue by HasanSourav** [hadley/r4ds#1262]
Please be noted that in chapter 12, section 12.4, the code in 2 shows error while running in R studio:

`diamonds2 <- diamonds |> 
  mutate(y = if_else(y < 3 | y > 20, NA, y))`

The following error is shown while running the code 

> Caused by error in `if_else()`:
! `false` must be a logical vector, not a double vector.

After searching through google it seems that dplyr package's _if_else_ function doesn't support different types of values. It suggests to use base R's _ifelse_ function.

Section 7.4 (Missing values) of 1st edition of r4ds is also seen the code to use _ifelse_ function.

`diamonds2 <- diamonds %>% 
  mutate(y = ifelse(y < 3 | y > 20, NA, y))`

**Comment by davidrsch** [comment]
To solve this issue update to the last version of dplyr, check issue #1254

**Comment by hadley** [comment]
Thanks for answering these @davidrsch!

**Comment by davidrsch** [comment]
Always a pleasure to help
