### ISSUE TITLE
Error while rending arrow.qmd

### ISSUE THREAD

**Issue by davidrsch** [hadley/r4ds#1268]
While trying to render arrow.qmd get the following error message:

```
processing file: arrow.qmd
  |........                       |  27% (open-dataset)                        Quitting from lines 78-86 (arrow.qmd) 
Error: IOError: Cannot list directory 'F:/My/directory/of/project/r4ds/data/seattle-library-checkouts.csv'. Detail: [Windows error 3] The system cannot find the path specified.
```
My OS is windows 10, I am using RStudio version 2022.12.0-353 and R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"

**Comment by davidrsch** [comment]
The lines specified in the error message shown in the previous comment are:
```{r}
# partial schema for ISBN column only
opts <- CsvConvertOptions$create(col_types = schema(ISBN = string()))

seattle_csv <- open_dataset(
  sources = "data/seattle-library-checkouts.csv", 
  format = "csv",
  convert_options = opts
)
```
But I think the error is due to the previous lines, which are suppose to download the dataset but are set to `eval: false`
```{r}
#| eval: false
dir.create("data", showWarnings = FALSE)

curl::multi_download(
  "https://r4ds.s3.us-west-2.amazonaws.com/seattle-library-checkouts.csv",
  "data/seattle-library-checkouts.csv",
  resume = TRUE
)
```
If this is indeed the cause of the error I understand it, because It wouldn't be right to make the user download such a big data set to render the book. I think errors like this should be warned to users, preferably in the repository's decryption than in the chapter itself.

**Comment by davidrsch** [comment]
Already able to render the book. I am guessing that its due to the changes applied in the pull request #1310. Before closing this issue I would like to know if the following warning messages that I got are normal.

For the files:

- data-visualize.qmd
- data-transform.qmd
- layers.qmd
- communication.qmd
- regexps.qmd
- joins.qmd
- iteration.qmd

I got the following Warning message
```
# > WARNING: Warning diff of engine output time out. No source lines will be available.
```

And for the file *database.qmd* I got the following Warning message
```
#> Warning message
#> 1: Connection is garbage-collected, use dbDisconnect() to avoid this.
#> 2: Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this
```

**Comment by hadley** [comment]
I've never seen "Warning diff of engine output time out..." before; but I doubt it's anything to do with R4DS.

The database warnings are expected

**Comment by davidrsch** [comment]
For I could find this "Warning diff of engine output time out..." has to be with js and may be related to my PC power
