### ISSUE TITLE
Average vs. Median

### ISSUE THREAD

**Issue by Hakarl22** [hadley/r4ds#1269]
I believe the following statement regarding interpretation of boxplots for the diamonds data set needs to be modified:

"It supports the counter-intuitive finding that better quality diamonds are cheaper on average! In the exercises, you’ll be challenged to figure out why." 

The issue is that the average is not shown in plots but rather the median.  Moreover there is a large difference between the two in terms of values.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, I've rephrased as "typically cheaper" since _typical value_ could refer to mean or median.
