### ISSUE TITLE
ifelse / if_else

### ISSUE THREAD

**Issue by pkriechling** [hadley/r4ds#1270]
Dear Team

This code in chapter 12.4 is not working. 

diamonds2 <- diamonds |> 
  [mutate](https://dplyr.tidyverse.org/reference/mutate.html)(y = [if_else](https://dplyr.tidyverse.org/reference/if_else.html)(y < 3 | y > 20, NA, y)) 

The reason is, that the function works only as ifelse. 

Best wishes
Philipp

**Comment by davidrsch** [comment]
To solve this issue update to the last version of  `dplyr`, check issue https://github.com/hadley/r4ds/issues/1254
