### ISSUE TITLE
Last topic in 12.6

### ISSUE THREAD

**Issue by Hakarl22** [hadley/r4ds#1271]
The discussion of the diamond data set and the introduction of residuals (from modeling) is quite confusing.  I suggest either expanding on the topic or removing it entirely.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback. Given that this chapter is about EDA in general, it makes sense to leave this in. In the Introduction (at https://r4ds.hadley.nz/intro.html#modeling) we point to more resources on modeling.
