### ISSUE TITLE
Typos in EDA.qmd

### ISSUE THREAD

**Issue by davidrsch** [hadley/r4ds#1272]
Open an issue and not a pull request, because I don't know if the first typo mentioned below is indeed a typo.

1. Regarding to section "12.4 Unusual data". Shouldn't be "12.4 Missing data" as suggested in the section name in the code line 268:
```
## Unusual values {#sec-missing-values-eda}
``` 
2. Typo in figure alternative in lines 331-335. Concretaly 335, says:
```
#|   flights not cancelled are much higher than those not cancelled.
```

and I think it should be

```
#|   flights not cancelled are much higher than those cancelled.
```

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
