### ISSUE TITLE
The diamonds package has been removed from cran

### ISSUE THREAD

**Issue by haifaharoon** [hadley/r4ds#1275]
The diamonds package has been removed/unavailable. (Also, thank you for the book!!)

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback @haifaharoon. 

`diamonds` is a dataset, not a package. It should be available when you load the tidyverse with `library(tidyverse)`. Does the language somewhere in the book suggest it might be a package? If so, we should fix that.

**Comment by haifaharoon** [comment]
Hi there --

Thanks for responding so quickly!

No, it doesn't. It seems I made an assumption it was a separate package - I
didn't realize tidyverse came with datasets as well, so I was trying to use
the install and library functions.

I figured it out though, I just needed to use "view (diamonds)".

Thanks again!
Haifa

**Comment by mine-cetinkaya-rundel** [comment]
Sounds good, glad it's clear now!
