### ISSUE TITLE
Adding explanation of `dep_time` of `flights` dataset

### ISSUE THREAD

**Issue by zekiakyol** [hadley/r4ds#1280]
### Problem 

We can add an explanation for the last chunk of <https://r4ds.hadley.nz/workflow-style.html#spaces> but I am not sure to add the data explanation in this *code style* chapter.

   ```
   flights |> 
     mutate(
       speed      = air_time / distance,
       dep_hour   = dep_time %/% 100,
       dep_minute = dep_time %%  100
     )
   ```

---

### Reasons

1. We use `%/%` and `%%` first time in [7.2 Spaces](https://r4ds.hadley.nz/workflow-style.html#spaces) and [12.4 Unusual values](https://r4ds.hadley.nz/eda#sec-unusual-values-eda) but we explain these operators in [15.4.3 Modular arithmetic](https://r4ds.hadley.nz/numbers.html#modular-arithmetic).
2. 
   Even though it is mentioned in the documentation below and also recommended at <https://r4ds.hadley.nz/data-transform.html#nycflights13>, we might still briefly mention `dep_time` is in `HMM` or `HHMM` format in the plaintext because I think it feels like typo that we need to replace `100` by `60` at first glance.
   ```
   library(nycflights13)
   ?flights
   ```

---

### Possible Explanation

``
Since `dep_time` is in HMM or HHMM fomat, we use integer division (`%/%`) to get hour and remainder (`%%`) to get minute.
``

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Comment by zekiakyol** [comment]
You are welcome!
