### ISSUE TITLE
Section 16.4.3  6th code box

### ISSUE THREAD

**Issue by bfletcherjohnson** [hadley/r4ds#1281]
In the 6th code box which is introduced with ", you can see the purpose of x_remainder:"

I believe assigning the tibble to "x" AND naming a column "x" creates odd behavior.  In the output the x column contains the entire string.  If you name the tibble "a"; in the output the x column contains the first entry, the fourth column entitled "a" contains the entire string.

**Comment by mine-cetinkaya-rundel** [comment]
Is this the code you're referring to?

```r
debug <- df |> 
  [separate_wider_delim](https://tidyr.tidyverse.org/reference/separate_wider_delim.html)(
    x,
    delim = "-",
    names = [c](https://rdrr.io/r/base/c.html)("x", "y", "z"),
    too_many = "debug"
  )
```

If so, the data frame is `debug`, not `x`. Does that address the concern?

**Comment by mine-cetinkaya-rundel** [comment]
We've made some changes to this chapter during the review so I think this issue might have gone away. I'll close for now but feel free to reopen if there's something else that is unclear.
