### ISSUE TITLE
Contar Historia com Dados

### ISSUE THREAD

**Issue by MarioDhiego** [hadley/r4ds#1303]
Boa tarde, Hadley, Sou Mário Diego, Estatístico, trabalho na área de Trânsito e Transporte, moro na cidade de Belém, Estado do Pará, Brasil.

Comprei seu Livro R para ciência de dados, lido 4 vezes, o melhor e mais didático que existe hoje. Achei que faltou um capítulo falando como Contar historias estatísticas ou historia com dados, sugerindo principalmente a alunos das áreas de ciências humanas, com pouco conhecimento de estatística a saber que existe um Fluxo de Trabalho para Contar Histórias com Dados usando o Rstudio.

Atenciosamente, seu Fã 
Mário Diego
+55 91 98060-7471
(WhatsApp)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the feedback! If I'm understanding correctly (based on Google Translate) this comment is about incorporating another chapter in the book on "Telling Stories with Data". Adding such a chapter is out of the scope of the book, at least for the 2nd edition that we're currently working on.

**Comment by MarioDhiego** [comment]
Thanks Darling.
