### ISSUE TITLE
Does string need specification?

### ISSUE THREAD

**Issue by davidrsch** [hadley/r4ds#1304]
Hey, yes this is more a doubt than an issue. I'm not native english speaker and while I was reading the introduction to the third part of the book (transform.qmd) I encounter that in the presentation of chapter 16 says.
`Chapter 16 will give you the tools to work with strings`
Refers to character strings as strings without specifying that are **character** strings. My doubt is if a person without any previous experience with r programming will understand that strings refers to character strings. I don't recall this been mentioned in the book before of this chapter and I specified that I am not native english speaker because this could be a normal assumption and I don't know about it.
Sorry if it is a too absurd question :sweat_smile:

**Comment by hadley** [comment]
What other sorts of string are there?

**Comment by davidrsch** [comment]
When learning english I associated strings to the strings in a violin or a guitar, I never associated to character or text strings until I started my journey with R. 
As I explained if it is a normal assumption then no clarification is needed

**Comment by mine-cetinkaya-rundel** [comment]
I added the word "character" to the second occurrence of "strings" in this paragraph, so we can keep the first reference matching the chapter title but still clarify what we mean by strings in the second occurrence.
