### ISSUE TITLE
Explain convention for "vs."?

### ISSUE THREAD

**Issue by SteveF2001** [hadley/r4ds#1311]
Chapter 2 uses "vs." in several exercises (e.g., "Make a scatterplot of hwy vs. displ..."). For readers new to the field do you want to build the habit of putting independent variables on the x-axis? If so, you might want to be more explicit in the exercises or explain the convention for "vs." with respect to which parameters are placed on which axis.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Comment by luke396** [comment]
To clarify for others who may be searching this, it pertains to the comparison between dependent and independent variables (y vs. x).

If I have misunderstood, please feel free to correct me.
