### ISSUE TITLE
Suggest Option as an alternative to Alt

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1317]
In the 3.5 Exercises (Whole game > Workflow: basics), the Alt key is suggested, which is not available on all keyboards.

> 3. Press Alt + Shift + K. What happens? How can you get to the same place using the menus?

On my MacBook Pro, I used `Option + Shift + K`.

**Comment by hadley** [comment]
Oh weird, I never noticed that only my external keyboard is marked with both alt and option, but my laptop keyboard only has option.
