### ISSUE TITLE
Tiny fixes: Chs 11, 13, 15, 21, 28

### ISSUE THREAD

**Issue by ganong123** [hadley/r4ds#1324]
### Chapter 11
- [ ] Delete “(You’ll learn how `filter()` works in the chapter on data transformations: for now, just know that this command selects only the subcompact cars.)”. This is presumably a legacy from when layers were explained before filter().

### Chapter 13
- [ ] It can be very useful for students to revisit old ideas with new tools. Ch 11 has a very nice example of using red open circle to highlight that two-seater cars deviate from the general fuel efficiency trend. In 13.3 where you teach annotation, it would be great to revisit this. For example, you could re-up the old plot with the added annotation 
> In general, increasing engine size is \nrelated to decreasing fuel economy… *but two-seaters cars achieve superior fuel economy in spite of their large engines*

where the italicized part is the new idea

### Chapter 15.6.3 & 15.6.7 
- [ ] The airport `EGE` did not move. You can easily see this by running
`flights %>% filter(dest == "EGE") %>% count(origin, carrier, distance)`
Rather, the issue is that almost everything in this dataset is reported by the airlines and United and American have slightly different recorded distances for this flight. I suggest using `IQR(distance)` and then using the `count()` verb to uncover the bug. Alternately, come up with a different IQR example (or I can).

### Chapter 21
- [ ] I can’t figure out the answer to 
> What do the tail numbers that don’t have a matching record in planes have in common? (Hint: one variable explains ~90% of the problems.) 

My solution algorithm was to use 
`flights %>% select(-year) %>% anti_join(planes) %>% count(varname)` 
and then permute over all of the variable names.

It's possible that others will find this question difficult and that a rewrite or different hint is in order

### Chapter 28.2.2
> “It’s important to note that we’re passing this function to [across()](https://dplyr.tidyverse.org/reference/across.html), so [across()](https://dplyr.tidyverse.org/reference/across.html) can call it, not calling it ourselves.” 

Sounds grammatically awkward even if it is correct. Better might be 
—“It’s important to note that we’re passing this function to [across()](https://dplyr.tidyverse.org/reference/across.html), so [across()](https://dplyr.tidyverse.org/reference/across.html) can call it, ~not~ **rather than** calling it ourselves.” 
—“It’s important to note that we’re passing this function to [across()](https://dplyr.tidyverse.org/reference/across.html), so [across()](https://dplyr.tidyverse.org/reference/across.html) can call it ~,~ **;** we’re not calling it ourselves.”

**Comment by hadley** [comment]
Chapter 13: I think that original plot has now gone

Chapter 21:

``` r
library(nycflights13)
library(tidyverse)

flights %>% 
  select(-year) %>% 
  anti_join(planes) %>% 
  count(carrier, sort = TRUE)
#> Joining with `by = join_by(tailnum)`
#> # A tibble: 10 × 2
#>    carrier     n
#>    <chr>   <int>
#>  1 MQ      25397
#>  2 AA      22558
#>  3 UA       1693
#>  4 9E       1044
#>  5 B6        830
#>  6 US        699
#>  7 FL        187
#>  8 DL        110
#>  9 F9         50
#> 10 WN         38

flights %>% 
  select(-year) %>%
  left_join(planes) |> 
  group_by(carrier) |> 
  summarise(prop_missing = mean(is.na(manufacturer))) |> 
  arrange(desc(prop_missing))
#> Joining with `by = join_by(tailnum)`
#> # A tibble: 16 × 2
#>    carrier prop_missing
#>    <chr>          <dbl>
#>  1 MQ           0.962  
#>  2 AA           0.689  
#>  3 F9           0.0730 
#>  4 FL           0.0574 
#>  5 9E           0.0566 
#>  6 US           0.0340 
#>  7 UA           0.0289 
#>  8 B6           0.0152 
#>  9 WN           0.00310
#> 10 DL           0.00229
#> 11 AS           0      
#> 12 EV           0      
#> 13 HA           0      
#> 14 OO           0      
#> 15 VX           0      
#> 16 YV           0
```

<sup>Created on 2023-03-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks!
