### ISSUE TITLE
Comments, chapter uncertain

### ISSUE THREAD

**Issue by ganong123** [hadley/r4ds#1328]
### loss of grouped mutate & filter
- [ ] In chapter 15, I’m surprised that grouped `mutate()` and `filter()` gets so little air time given that it is incredibly useful in the real-world. 1e has useful [examples](https://r4ds.had.co.nz/transform.html#grouped-mutates-and-filters). I found that the examples were too brief to be clear for my students and over the years my slides evolved into 
[grouped mutate and filter slides.pdf](https://github.com/hadley/r4ds/files/10854387/grouped.mutate.and.filter.slides.pdf). I think it is quite important to explain grouped `mutate()` and `filter()`. Could be Ch 15, but could be elsewhere.

### writing tests
- [ ] I think it would be very useful to teach students to explicitly write tests, rather than simply printing material to the console where the analyst verifies by inspection that the claim is true. 

For example, after the print statements in 21.2.2, one could include: 
```
test_that(
  "There are no tailnums that appear more than once",
  expect_equal(
    planes %>%
    count(tailnum) %>%
    filter(n > 1) %>%
    nrow(),
    0
) ) 
```
I also suggest a function which is effectively a test in Chapter 27 https://github.com/hadley/r4ds/issues/1327

### cross-cutting bug
- [ ] Avoid ever numbering data frames (e.g. `flights2`). This is just teaching students bad hygiene (and further [seems](https://style.tidyverse.org/syntax.html#object-names) inconsistent with the style guide). Either stick with the name `flights` or name it `flights_what_i_did`

**Comment by hadley** [comment]
Agree with all these points; but again not enough time to change now (and I think testing will always be out of scope for R4DS)
