### ISSUE TITLE
The example code in section 'Unknown sequence length' might need a change

### ISSUE THREAD

**Issue by fereshtehRS** [hadley/r4ds#133]
In section `16.2.4 Unknown sequence length`, this example code:

```
flip <- function() sample(c("T", "H"), 1)

flips <- 1
nheads <- 0

while (nheads < 3) {
  if (flip() == "H") {
    nheads <- nheads + 1
  } else {
    nheads <- 0
  }
  flips <- flips + 1
}
flips
```

I think setting `nheads <- 0` in the `else` construct is not correct.
Also shouldn't we start with `flips <- 0` ?

**Comment by hadley** [comment]
You're right about that we should initialise flips to 1. But I'm pretty sure setting `nhead` to 0 is correct - as soon as you see a tail, you've seen no heads in a row?

**Comment by fereshtehRS** [comment]
Sorry, my mistake. I somehow missed "in a row" part.
