### ISSUE TITLE
OK to use material for accompanying tutorials

### ISSUE THREAD

**Issue by davidkane9** [hadley/r4ds#1336]
I would like to use the material in R4DS to create some accompanying tutorials. Any objections?

Background:

1) The license for R4DS is "Creative Commons Attribution-NonCommercial-NoDerivs 3.0". The NoDerivs part can be tricky.

2) I write [lots of tutorials](https://github.com/PPBDS/all.primer.tutorials) for my students. See [here](https://ppbds.github.io/all.primer.tutorials/articles/instructions.html) for details on my approach.

3) I would like to, for example, create a tutorial about web scraping which would cajole/force students to type all the commands in the web scraping [chapter](https://r4ds.hadley.nz/webscraping.html). To do that, I would (obviously) need to use the same code/example as in the chapter itself.

If the license were simply "Creative Commons Attribution-NonCommercial", then there would be no worries. But the NoDerivs part makes it unclear whether I need permission. So, I thought I would at least ask.

Big fan of the first and second editions!

**Comment by hadley** [comment]
That all sounds like it falls in the scope of fair use to me.
