### ISSUE TITLE
"tidyverse_update()" cannot be found.

### ISSUE THREAD

**Issue by piiskop** [hadley/r4ds#1340]
[Section 1.4.3](https://r4ds.hadley.nz/intro.html#the-tidyverse) contains the following sentence:

> Packages in the tidyverse change fairly frequently. You can see if updates are available by running [tidyverse_update()](https://tidyverse.tidyverse.org/reference/tidyverse_update.html).

i ran that command in RStudio Server:

> > tidyverse_update()
> Error in tidyverse_update() : could not find function "tidyverse_update"

**Comment by davidrsch** [comment]
Hey, check if you have loaded properly the tidyverse libraries. Run:
```{r}
library(tidyverse)
```
If keep getting the same error, try:
```{r}
tidyverse::tidyverse_update()
```

**Comment by piiskop** [comment]
i was confused about which package `tidyverse_update()` belongs to. Now i know that it is `tidyverse`. Loading the library, and updating worked just fine. i suggest stressing out that the library should be loaded before trying the update process.

**Comment by hadley** [comment]
I think it's fairly clear from the context; it definitely takes a while to get the hang of which function comes from which package.

**Comment by piiskop** [comment]
i would not have come to this issue unless the text would not be clear enough. i suggest changing this sentence:

> You can see if updates are available by running [tidyverse_update()](https://tidyverse.tidyverse.org/reference/tidyverse_update.html).

to the sentence:

> You can see if updates are available by running [tidyverse_update()](https://tidyverse.tidyverse.org/reference/tidyverse_update.html) after having loaded the library _tidyverse_.
