### ISSUE TITLE
"tidyverse" cannot be installed

### ISSUE THREAD

**Issue by piiskop** [hadley/r4ds#1341]
In [section 2.1.1](https://r4ds.hadley.nz/data-visualize.html#prerequisites), you ask to install `tidyverse` however, it cannot be installed:

*

>  DONE (modelr)
> ERROR: dependency ‘ragg’ is not available for package ‘tidyverse’
> * removing ‘/home/kalmer/R/x86_64-pc-linux-gnu-library/4.2/tidyverse’
> Warning in install.packages :
>   installation of package ‘tidyverse’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘/tmp/Rtmp5lEya9/downloaded_packages’
>

**Comment by hadley** [comment]
This is some specific installation issue on your system.

**Comment by piiskop** [comment]
The specificity lies in `ragg`s dependency requiring two packages to be installed via `apt`. That should be stated in the book.

**Comment by hadley** [comment]
Only if you're installing from source, which only a vanishing small portion of people do.

**Comment by hadley** [comment]
Most people install pre-built package binaries, so they don't need external system dependencies.

**Comment by piiskop** [comment]
i cannot remember how i installed it, can i figure it out somehow?

**Comment by eweiss99** [comment]
I'm having the same problem with Linux and R 4.2.3  I've tried both installing in RStudio using "Packages" and installing in RStudio from source. I always get an error message about ragg. If I try to install ragg, the error messages in not finding ft2build.h

Is there a workaround for this problem?

**Comment by dkrulewich1** [comment]
This thread is over a year old, so might be no one still looking.  Nevertheless, on my system running Linux Mint  22.1 which is based on Ubuntu 24.04 LTS, the system libraries required to work around this can be installed using:

sudo apt install libharfbuzz-dev libfribidi-dev
