### ISSUE TITLE
gs_auth() issue with offline token

### ISSUE THREAD

**Issue by wma1125** [hadley/r4ds#135]
Hi Jenny,

i'm using googlehsheets in R. .there is some issues when I tried to use .rds for authentication without interaction with browser. it seems failed refreshing and I have to use gs_auth() to re-enter my authentication in browser.

gs_auth(token = "ttt.rds", verbose = FALSE)

Auto-refreshing stale OAuth token.
Error in function_list[k] : Unauthorized (HTTP 401).
In addition: Warning message:
Unable to refresh token

**Comment by hadley** [comment]
You need to file this on the googlesheets repo, not here.
