### ISSUE TITLE
Ch6 major inconsistency

### ISSUE THREAD

**Issue by ganong123** [hadley/r4ds#1361]
(cross-post of https://github.com/hadley/r4ds/issues/1322#issuecomment-1464570485 since I can't reopen that issue)

_I realized this issue while trying to write teaching slides based on the textbook. I understand that you are winding down writing and so this comment is probably untimely, but I would rather you know about the problem and decide not to address it than not be aware of the problem. I think this is the only comment I have of this nature (I will collect comments for a future edition elsewhere)_

Chapter 6 has an inconsistent definition of what constitutes tidy that will make it really hard for a reader to understand what tidy means.

| Chapter section | is `table1` tidy? | is `table2` tidy? | notes |
| --- | --- | --- | --- | 
| 6.1 | yes | no | "table1, will be much easier to work with inside the tidyverse because it’s tidy." |
| 6.3.2 | no | yes | "we can tidy df with... `pivot_longer()`." see also figures 6.3, 6.4, and 6.5 |

**Comment by mine-cetinkaya-rundel** [comment]
Thank you! I reworded to make it explicit what we're doing, particularly since this is in the section where we're illustrating how `pivot_longer()` works, as opposed to making a commentary on why we might want to pivot longer.
