### ISSUE TITLE
Linewidth density plot

### ISSUE THREAD

**Issue by malinuden** [hadley/r4ds#1366]
I am new to RStudio and I'm working my way through the book to learn. 

I could not make 'linewidth' to work in the following: 
ggplot(penguins, aes(x = body_mass_g, color = species)) +
  geom_density(linewidth  = 0.75)

It generated a warning message:
1: Ignoring unknown parameters: linewidth 

Changing to lwd worked:
ggplot(penguins, aes(x = body_mass_g, color = species)) +
  geom_density(lwd = 0.75)

Best regards Malin

**Comment by hadley** [comment]
You need a newer version of ggplot2.

**Comment by malinuden** [comment]
Oh sorry my bad, thank you!
