### ISSUE TITLE
List all other packages used in the book in the Introduction

### ISSUE THREAD

**Issue by kevinxperese** [hadley/r4ds#1373]
There are a few more packages that are used in the book that are not listed in the Introduction. It may be useful to have them all listed in one place up front.

The packages/data sets I see used that are not listed include:
* `cms_patient_experience`
* `billboard`
* `ggthemes`
* `scales`
* `ggrepel`
* `patchwork`
* `usethis`
* `hexbin`

Some organizations require each of these to go through an approval process before they can be installed, so having all the requirements listed in one place might be useful.

**Comment by mine-cetinkaya-rundel** [comment]
The following are datasets in the tidyverse, not packages:

- `cms_patient_experience`
- `billboard`

so they're available once tidyverse is installed. In addition, scales is installed with the tidyverse.

The full list of packages required to run the code in the chunks throughout the book can be found in the [`DESCRIPTION` file](https://github.com/hadley/r4ds/blob/main/DESCRIPTION#L12-L33). I think these are too many to list in the intro but I'll defer to @hadley here. A link to this file is an option, as your comment re: potential approval process is important too.

**Comment by kevinxperese** [comment]
Thanks for the clarification. A link to the DESCRIPTION file sounds great.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the suggestion, I've added all packages to the intro.
