### ISSUE TITLE
Malformed Authors Redux?

### ISSUE THREAD

**Issue by anadkarn738** [hadley/r4ds#1387]
To whom it may concern,

I was trying to install r4ds so I could get a pdf version (I know the current version is a work in progress) to annotate.

However, I think there's a small error in the DESCRIPTION file (much like #1000).

I forked the repo and deleted the comma on line 7, which appeared to fix the issue for me.

So as far as I can tell, there seems to be an extra comma that was introduced in: b0a395b477a9f09de451f0c72206604873642c0d ?

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
