### ISSUE TITLE
Duplicated column names in Figure 6.7 in data-tidy

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1404]
I find column name "id" appears twice in the right data frame of Figure 6.7 in data-tidy.qmd. Better to change `names_to = c(".value", "id")` to something like `names_to = c(".value", "number")`.

**Comment by mine-cetinkaya-rundel** [comment]
@hadley What do you think, this is related to

![image](https://user-images.githubusercontent.com/5965649/230821166-23b3ba8f-9a44-48da-9db9-136621b3ada1.png)

where `id` column is duplicated.

**Comment by mine-cetinkaya-rundel** [comment]
Earlier it's called `number`, we could perhaps do `no` if that's not too obscure.

**Comment by hadley** [comment]
Actually, it's only one column in one diagram, so best to stick with what's in the text. I'll submit a fix momentarily; do you mind recording in the googlesheet.
