### ISSUE TITLE
Typo in section 12.3 Annotations 2ed

### ISSUE THREAD

**Issue by g-tibo** [hadley/r4ds#1413]
Dear r4ds team,

I just want to report a small typo in section 12.3 Annotations of your 2ed edition.

In this code there is an extra comma after "nudge_y = 2" that should be there.

The code in the 2ed is the following:

`ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = F) +
  geom_label_repel(
    data = label_info,
    aes(x = displ, y = hwy, label = drive_type),
    fontface = "bold",
    size = 5,
    nudge_y = 2,
  ) +
  theme(legend.position = "none")`

and it should be:
`ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = F) +
  geom_label_repel(
    data = label_info,
    aes(x = displ, y = hwy, label = drive_type),
    fontface = "bold",
    size = 5,
    nudge_y = 2
  ) +
  theme(legend.position = "none")`

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
