### ISSUE TITLE
Dates and times - 18.2.1

### ISSUE THREAD

**Issue by martinekadam** [hadley/r4ds#1415]
This passage about the ISO8601 standard has mistakes: 

> If you haven’t heard of ISO8601 before, it’s an international standard[2](https://r4ds.hadley.nz/datetimes.html#fn2) for writing dates where the components of a date are organized from biggest to smallest separated by -. For example, in ISO8601 March 5 2022 is 2022-05-03. ISO8601 dates can also include times, where hour, minute, and second are separated by :, and the date and time components are separated by either a T or a space. For example, you could write 4:26pm on March 5 2022 as either 2022-05-03 16:26 or 2022-05-03T16:26.

March 5 2022 ought to be 2022-03-05 in ISO8601. :)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
