### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by pkriechling** [hadley/r4ds#1416]
Dear Team

The book is absolutely perfect to learn R. Many thanks for all your work. However, it is sometimes difficult to solve the exercises. Is there a solution for the second edition of the book available anywhere? That would be really good because I have already thought about reading the first version of the book because solutions for the exercises are available. 

Many thanks
Philipp

**Comment by mine-cetinkaya-rundel** [comment]
Glad you're enjoying the book! When a solutions manual is available, we'll be sure to link from the README! In the meantime, [Posit Community](https://community.rstudio.com/) as well as [R for Data Science Online Learning Community](https://www.rfordatasci.com/) are great places to ask questions about exercises in this book.
