### ISSUE TITLE
Section 11.3 EDA/Variation: measurement and observation

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1426]
I feel odd at a part of the sentence, "it varies between measurements on the same observation as well as across observations" in the first paragraph of Section 11.3 EDA/Variation, as measurement and observation usually means the same thing. I don't get the meaning of "measurements on the same observation." How can they be in tidy data?

**Comment by mine-cetinkaya-rundel** [comment]
A dataset can be wide (with multiple measurements on the same observation) and still be tidy.
