### ISSUE TITLE
Section 13.2 Comparisons

### ISSUE THREAD

**Issue by jcornickm** [hadley/r4ds#1442]
It is a minor thing, and makes no difference in terms of learning about logical comparisons, but since the text refers to flights that leave roughly on time, it would make more sense to use abs(dep_delay) in the code, instead of abs(arr_delay):  the correlation between the two is quite imperfect

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, I've updated the text to match the code in 58547b1ec4123df5db46a26c1c49ed895438c2db.
