### ISSUE TITLE
Chapter 6, example on how pivoting works

### ISSUE THREAD

**Issue by AdaemmerP** [hadley/r4ds#1453]
Thank you very much for this outstanding book!

While explaining the concept of tidy data using R4DS (2e), I was a bit confused by the example in 6.3.2. Doesn't the tibble contain the same "problem" as  6.3.4 ("Data and variable names in the header"), because "bp" is a variable (name) and the digits are the values for the variable "measurement". According to 6.3.4, shouldn't the tibble be better pivoted like this?

``` r
# Create tibble
df <- tribble(
  ~id,  ~bp1, ~bp2,
  "A",  100,  120,
  "B",  140,  115,
  "C",  120,  125
)

# Make tibble tidy
df |> 
  pivot_longer(
    cols = bp1:bp2,
    names_to = c(".value", "measurement"),
    names_pattern = "(..)(.)"
  ) 
#> # A tibble: 6 × 3
#>   id    measurement    bp
#>   <chr> <chr>       <dbl>
#> 1 A     1             100
#> 2 A     2             120
#> 3 B     1             140
#> 4 B     2             115
#> 5 C     1             120
#> 6 C     2             125
``` 

Maybe the tibble in the example could just get different column names to begin with to get around this issue?

``` r
# Create tibble
df <- tribble(
  ~id,  ~m1, ~m2,
  "A",  100,  120,
  "B",  140,  115,
  "C",  120,  125
)

# Make tibble tidy
df |> 
  pivot_longer(
    cols = !id,
    names_to = "measurement",
    values_to = "value"
  ) 
#> # A tibble: 6 × 3
#>   id    measurement  value
#>   <chr> <chr>       <dbl>
#> 1 A     m1            100
#> 2 A     m2            120
#> 3 B     m1            140
#> 4 B     m2            115
#> 5 C     m1            120
#> 6 C     m2            125
```
In addition, a column name in Figures 6.3, 6.4, and 6.5 does not match the tidied tibble ("measurement" vs. "name").

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the feedback. We've kept the examples as is, but have updated the figures in #1464.
