### ISSUE TITLE
13.3.1 Boolean algebra and missing values

### ISSUE THREAD

**Issue by jcornickm** [hadley/r4ds#1454]
Maybe it's just me, but I found the explanation of Boolean algebra and missing values in section 13.3.1 imposible to understand.  

After being stuck for a while, I found an explanation that made sense to me immediately, so, just in case it might be useful for others  here is the link to it:

      https://www.programiz.com/r/booleans

**Comment by hadley** [comment]
I don't see any discussion of `NA` on that page?

**Comment by jcornickm** [comment]
You are right and I will have to explain myself better, because the page did help me a lot...but it was a two-step process. I will send my explanation tomorrow.

It blows my mind that you, and not somebody's assistant's  assistant would react to my comment.

Thanks

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Hadley Wickham ***@***.***>
Enviado: Wednesday, May 3, 2023 3:34:51 PM
Para: hadley/r4ds ***@***.***>
Cc: Jorge Cornick ***@***.***>; Author ***@***.***>
Asunto: Re: [hadley/r4ds] 13.3.1 Boolean algebra and missing values (Issue #1454)


I don't see any discussion of NA on that page?

**Comment by jcornickm** [comment]
Hello Hadley.

You are a busy guy, so I will provide a hopefully better but very short explanation, and then, just in case it is somehow useful, a slightly longer one.

IN SHORT
I hadn’t really understood how Boolean worked, and the explanation in the link, particularly the two tables below were very helpful.  Suddenly something “clicked” and the text in the book made sense.

[A screenshot of a computer  Description automatically generated with medium confidence]

[A screenshot of a computer  Description automatically generated with medium confidence]

NOT SO SHORT

When I read the code below, I expected “and” to be TRUE when an element belonged to X and it was equal to NA, and FALSE otherwise.  Perhaps I was thrown off because I had never seen a dataframe created as in this piece of code, and I wasn´t shure what was being compared to what.  The point is I could not make head or tails of the results (I am usually not the dumbest guy in the room, but I am not the fastest, either)

df <- tibble<https://tibble.tidyverse.org/reference/tibble.html>(x = c<https://rdrr.io/r/base/c.html>(TRUE, FALSE, NA))

df |>
  mutate<https://dplyr.tidyverse.org/reference/mutate.html>(
    and = x & NA,
    or = x | NA
  )

Then I wrote the following code to explain the results to myself as I was a 6 year old, and everything made sense to me:

## Missing values                                                           ####
df1 <- c(TRUE, FALSE, NA)
df2 <- c(NA,NA,NA)
df1 & df2
df2 & df1

# the following returns true, because at least one element is true
TRUE | TRUE

# the following also returns true, for the same reason
TRUE | FALSE
FALSE | TRUE

# Since NA are either true or false, the following also returns true
NA | TRUE
TRUE | NA

# However, the following return NA, because we don´t know if NA = TRUE, in
# which case the statement is TRUE, of if NA is FALSE, in which case the
# statement is FALSE
NA | FALSE
FALSE | NA

This is, of course, not to suggest any changes in the book, but just to explain what worked for me, in case that is useful to you as a writer.

Just for context, because the mind of young people who went to hackathons instead of kindergarten works differently:  I am 63.  I have a Ph.D in Economics and many years ago I knew a lot of Econometrics,  which I mostly stopped using after graduation, because back in the day you needed Stata or SPSS or something like that, which was unaffordable for an independent consultant such as me, and because I became Econometrics-skeptical.  Then along came R and Data Science (which I find both more modest and more powerful than traditional econometrics) and I decided to start studying a bit of it a while ago.  Now I remember why a studied Econometrics, as programming is one of the few activities that totally make me loose the sense of time.  I am working through your book, and I have Tidy Modeling and R-Packages lined up next.  I am having a fantastic time with it, and so, THANK YOU.


***@***.***

**Comment by mine-cetinkaya-rundel** [comment]
Thank you! I've expanded a bit on this section, which hopefully helps.
