### ISSUE TITLE
16.3.2 regex

### ISSUE THREAD

**Issue by SeeSeoSea** [hadley/r4ds#1455]
In 16.3.2，the code below doesn't work.
```
str_count(regex(name, ignore_case = TRUE), "[aeiou]")
```
Maybe it should be:
```r
str_count(name, regex("[aeiou]", ignore_case =TRUE))
```

**Comment by hadley** [comment]
Oops, yes. Do you want to do a PR?

**Comment by SeeSeoSea** [comment]
Maybe I could try it but I don't know exactly what PR is going to do.

**Comment by SeeSeoSea** [comment]
Maybe I can have a try.



At 2023-05-05 23:24:47, "Hadley Wickham" ***@***.***> wrote:

Oops, yes. Do you want to do a PR?

**Comment by mine-cetinkaya-rundel** [comment]
Fixed in the pull request above, thank you!
