### ISSUE TITLE
Environment pane reference in data-visualize.qmd

### ISSUE THREAD

**Issue by kevinxperese** [hadley/r4ds#1457]
"This data frame contains 8 columns. For an alternative view, where you can see all variables and the first few observations of each variable, use [glimpse()](https://pillar.r-lib.org/reference/glimpse.html). Or, if you’re in RStudio, click on the name of the data frame in the Environment pane or run View(penguins) to open an interactive data viewer."

There are no objects in the Global Environment, which will likely be confusing to a new users, without going into further detail about clicking on the dropdown menu to access the objects in the `palmerpenguins` package.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
