### ISSUE TITLE
Confusing data transform exercise

### ISSUE THREAD

**Issue by kevinxperese** [hadley/r4ds#1458]
The conditions in 4.2.5 Exercise 1 in data-transform.qmd are overly restrictive and do not produce any rows after all the filtering conditions are applied in a single pipeline. The last two conditions, in particular, are mutually exclusive.

**Comment by hadley** [comment]
Can you please provide a link?

**Comment by kevinxperese** [comment]
https://r4ds.hadley.nz/data-transform.html#exercises

1. In a single pipeline, find all flights that meet each of the following conditions:

* Had an arrival delay of two or more hours
* Flew to Houston (IAH or HOU)
* Were operated by United, American, or Delta
* Departed in summer (July, August, and September)
* Arrived more than two hours late, but didn’t leave late
* Were delayed by at least an hour, but made up over 30 minutes in flight

**Comment by hadley** [comment]
A single pipeline for _each_ of the conditions.

**Comment by kevinxperese** [comment]
I was recently in a group of ~20 who had worked through this exercise and we all interpreted the task as something like this:

```
flights |> 
  filter(arr_delay >= 120) |> 
  filter(dest %in% c("IAH", "HOU")) |> 
  filter(carrier %in% c("UA", "AA", "DL")) |> 
  filter(month %in% seq(7, 9)) |>
  etc.
```
(And then we floundered around trying to debug why the last two conditions didn't work.)

If the intention for the exercise is something like this:
```
flights |> 
  filter(arr_delay >= 120)
  
flights |>   
  filter(dest %in% c("IAH", "HOU")) 
  
flights |>   
  filter(carrier %in% c("UA", "AA", "DL"))
  
etc.
```

perhaps these instructions would be clearer?

1. Using pipes and the `filter()` function, how many flights:
* Had an arrival delay of two or more hours?
* Flew to Houston (IAH or HOU)?
* Were operated by United, American, or Delta?
* Departed in summer (July, August, and September)?
* Arrived more than two hours late, but didn’t leave late?
* Were delayed by at least an hour, but made up over 30 minutes in flight?

**Comment by mine-cetinkaya-rundel** [comment]
Updated to emphasize single pipeline for each, thanks!

**Comment by kevinxperese** [comment]
No problem, my pleasure.
Apologies for not realizing this sooner: I also think a part of my confusion could stem from this exercise being the first time the word "pipeline" is used in the chapter.
