### ISSUE TITLE
Typo in new book

### ISSUE THREAD

**Issue by rick-wheeler** [hadley/r4ds#1460]
Awesome book just reading it now.

In the intro https://r4ds.hadley.nz/intro.html

Should:
"However, it is incredible faster and the performance payoff is worth investing some time learning it if you’re working with large data."

Be:

"However, it is incredibly faster and the performance payoff is worth investing some time learning it if you’re working with large data."

??

**Comment by mine-cetinkaya-rundel** [comment]
Fixed in #1452, thanks!
