### ISSUE TITLE
Issue of labelling the whiskers range (1.5 IQR) on figure 2.1

### ISSUE THREAD

**Issue by SpicyChicken6** [hadley/r4ds#1461]
It seems the upper whisker range (1.5 x IQR) was not correctly indicated by the arrows aside.
<img width="650" alt="截屏2023-05-09 下午3 48 26" src="https://github.com/hadley/r4ds/assets/72659448/037b19e0-3369-441b-aa6b-96de5b830da4">

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the feedback!

The whisker goes to the "farthest non-outlier point in the distribution", so this figure is correct.

**Comment by SpicyChicken6** [comment]
Sorry I missed that! Thank you very much!
