### ISSUE TITLE
Missing download link to palmerpenguins xlsx file in chapter 21 

### ISSUE THREAD

**Issue by BenMarmont** [hadley/r4ds#1467]
In chapter 21 when demonstrating how to read excel files with read_excel you load the palmerpenguins excel file from you local data folder. However, there is no link provided to download the file like the other example datasets such as students. Later in the chapter when demonstrating loading google sheets a link it provided. 

In summary, please add a link to the palmerpenguis excel file section 21.2.4. The following link is the one used later in the chapter (with a link shortener).
https://docs.google.com/spreadsheets/d/1aFu8lnD_g0yjF5O-K6SFgSEWiHPpgvFCF0NY9D6LXnY/edit#gid=0

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
