### ISSUE TITLE
15.2.3 Other special characters, no blue background of str_view() output

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1479]
The last paragraph in 15.2.3 Other special characters states, "str_view() uses a blue background for tabs". However, I can't find any blue background under stringr version 1.5.

**Comment by mine-cetinkaya-rundel** [comment]
@hadley Indeed, `str_view()` doesn't result in a blue background in this chapter:

<img width="763" alt="Screenshot 2023-11-08 at 11 53 31 PM" src="https://github.com/hadley/r4ds/assets/5965649/6f7b3a71-130c-43ea-8eb7-dd15b77a2222">

It actually doesn't in [`str_view()` docs](https://stringr.tidyverse.org/reference/str_view.html#ref-examples) either, though there it does change the color of the text (just not the background, and not to blue).

Do we want to update `str_view()` to do what it claims to do, or update the language in the book?

**Comment by hadley** [comment]
Yeah, we should say it uses blue _text_ but you don't see that in the book (thanks to #1027)
