### ISSUE TITLE
23 Arrow; write_dataset(seattle_csv) fails due to null type of ISBN

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1482]
23.3 Opening a dataset
seattle_csv shows ISBN as null, while seattle_csv |> glimpse() shows ISBN as string thanks to cache.

If ISBN is null, write_dataset(seattle_csv) fails.
I followed https://stackoverflow.com/questions/74159537/rarrow-error-when-using-the-dataset-api to avoid this pitfall.

I think it would be better to let readers know about this pitfall.

**Comment by mitsuoxv** [comment]
I just found this is the same issue as #1374, which is closed.
Still, I would like to let readers know the issue and the solution in StackOverflow.

**Comment by mine-cetinkaya-rundel** [comment]
Yes, this is being tracked at #1374 and #1533. Closing this in favor of those.
