### ISSUE TITLE
29.8 Caching; cache.extra doesn't work

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1501]
After some experiments, I think I have found cache.extra doesn't work in Quarto. My quarto version is 1.3.353.
I guess file.info() is not executed when placed in #| line of Quarto, while it is executed when placed as a chunk option of Rmarkdown.

**Comment by mitsuoxv** [comment]
After more experiments, I have found below works. Still, somehow file.info() fails, while file.mtime() works.

#| cache.extra: !expr file.mtime("a_very_large_file.csv")

**Comment by mitsuoxv** [comment]
I have made PR  #1504.

**Comment by mine-cetinkaya-rundel** [comment]
Closed with #1504
