### ISSUE TITLE
Is the syntax highlighting theme available in RStudio?

### ISSUE THREAD

**Issue by dracodoc** [hadley/r4ds#151]
This question is acutally about RStudio, not really about the book, but I wanted to post here because posts in RStudio support often have no response for long time.

I found the syntax highlighting theme for code in book very informative. Once the code in book was copied to RStudio, they become rather dull with same color for almost everything. Two very helpful differences are the known library function names (bold green) and the function parameter assignments (dark red).

The theme in book seemed to be implemented by customized CSS, but there should be no difficulty to implement similar effect in RStudio. I searched RStudio support and found several similar requests dated as early as 2013.

I submitted [a feature request in RStudio support](https://support.rstudio.com/hc/en-us/community/posts/211643088-syntax-highlighting-for-known-function-names-parameter-names)

**Comment by dracodoc** [comment]
I just learned that the function name highlighting is available already. I didn't find the option, it is in 

      Options - code - display - Highlight R function calls

**Comment by truonghuy** [comment]
You can also change the theme of the Editor in RStudio as follows:

`Tools - Global Options - Appearance`
