### ISSUE TITLE
Subtitle of the physical book

### ISSUE THREAD

**Issue by mitsuoxv** [hadley/r4ds#1510]
The subtitle of the physical book, "Import, Tidy, Transform, Visualize, and Model Data", is unchanged from 1e (as of October, 2017 when the Japanese version was published), though the modelling part has been removed in 2e.

If changing it is still possible, I would like to suggest a few candidates for a new subtitle:
1. (Just remove Model) "Import, Tidy, Transform, and Visualize Data"
2. (Describe the main contents) "Best practices for efficient and reproducible workflow"
3. (Marketing for tidyverse) "Start your project with the tidyverse packages"

**Comment by mine-cetinkaya-rundel** [comment]
This is something we'll want to change for 3e, but since we can't actually address it in the repo, I'll close the issue.
