### ISSUE TITLE
4.5.3  slice_max

### ISSUE THREAD

**Issue by IraSharenow100** [hadley/r4ds#1511]
You wrote:

```r
df |> slice_max(x, n = 1) takes the row with the largest value of column x.
```

It can take more than one row if there are ties.

```r
df1 = data.frame(x = c(1,1,3,5,5), y = c(10, 10, 2,2,2), z = 14:10)
df1 |> slice_max(x, n = 1)
```

Modifying the help example

```
mtcars %>% slice_max(mpg, n = 3) # returns 4 rows

**Comment by mine-cetinkaya-rundel** [comment]
This is clarified a few lines down:

> Note that there are 105 destinations but we get 108 rows here. What’s up? [slice_min()](https://dplyr.tidyverse.org/reference/slice.html) and [slice_max()](https://dplyr.tidyverse.org/reference/slice.html) keep tied values so n = 1 means give us all rows with the highest value. If you want exactly one row per group you can set with_ties = FALSE.
