### ISSUE TITLE
Confusing symbol/placement for footnote

### ISSUE THREAD

**Issue by carinamc** [hadley/r4ds#1516]
The symbol and its placement here leads to confusing because, read literally, the ^2 exponent indicates x^2 number of rows , whereas you are trying to say there are x number of rows almost all the time. Could you just change the sentence to something like "almost always leads to a number of rows equal to x" or otherwise rearrange the sentence so the ^2 doesn't come immediately after x in the confusing way?

**Comment by carinamc** [comment]
In case it doesn't show the location I'm referring to, it's "It’s special because the output will always have the same rows as x[2](https://r4ds.hadley.nz/joins.html#fn2)"

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
