### ISSUE TITLE
8.2 Reading data from a file - Issue

### ISSUE THREAD

**Issue by amitbundi** [hadley/r4ds#1521]
The code above will work if you have the students.csv file in a data folder in your project. You can download the students.csv file from **https://pos.it/r4ds-students-csv** or you can read it directly from that URL with:

In the attached link, the file is in .txt format and not .csv format

**Comment by mine-cetinkaya-rundel** [comment]
The suffix (.txt) likely has to do with how files get downloaded on your machine. The contents of the file are comma separated. You should be able to rename the file to have .csv as suffix.
