### ISSUE TITLE
Possible typo at 8.3.3 Column types: col_character()

### ISSUE THREAD

**Issue by jAli9** [hadley/r4ds#1526]
Great second edition. 

This sentence in the description of col_character() might be easier to read with an extra "to."

Original text: 
This can be useful to specify explicitly when you have a column that is a numeric identifier, i.e., long series of digits that identifies an object but doesn’t make sense apply mathematical operations to.

Suggested change: 
This can be useful to specify explicitly when you have a column that is a numeric identifier, i.e., long series of digits that identifies an object but doesn’t make sense **to** apply mathematical operations to.

**Comment by mine-cetinkaya-rundel** [comment]
Looks like this was addressed in #1529, thank you!
