### ISSUE TITLE
Cannot find preface

### ISSUE THREAD

**Issue by raffaem** [hadley/r4ds#1530]
I've tried to run the code to produce the book, but when running:
```
htmlbook::convert_book()
```

I get:
> Error: '_book/preface-2e.html' does not exist in current working directory ('/mnt/dataint/data/progetti_altrui/r4ds').

**Comment by mine-cetinkaya-rundel** [comment]
This is a Quarto book so if you're in RStudio and open the `r4ds.rproj` file you can render it from the Build tab with Render Book.

Alternatively, you can run `quarto render` in the terminal when in the correct folder.

**Comment by raffaem** [comment]
Thank you very much.

It would be really helpful to have a list of packages you need to install to compile the book (tidyverse, babynames, writexl, ...).

Otherwise it's a pain of trial and error.

If I'm not missing a command to install them automatically.

**Comment by raffaem** [comment]
I came up with the following command to find out the list of libraries I need to compile:
```
grep -P "library\(" -r . -n --include \*.qmd | awk -F ':' '{print $3}' | grep -P "(?<=library\().*?(?=(\)|,))" -o | sort --unique | tr '\n' ','
```

which resulted in:

```
arrow,babynames,DBI,dbplyr,dplyr,duckdb,ggrepel,ggridges,ggthemes,googlesheets4,jsonlite,leaflet,nycflights13,palmerpenguins,patchwork,readxl,repurrrsive,rvest,scales,shiny,tidymodels,tidyverse,writexl
```

**Comment by mine-cetinkaya-rundel** [comment]
The required packages are listed in [`DESCRIPTION`](https://github.com/hadley/r4ds/blob/main/DESCRIPTION).

**Comment by raffaem** [comment]
I see, thanks.

1. How do you install those required packages by reading `DESCRIPTION`? That is, is there something equivalent to `pip install -r requirements`?
2. Is there a `_quarto.yml` to compile into PDF? I tried using `format: pdf` but the plots goes beyond the page

**Comment by mine-cetinkaya-rundel** [comment]
1. You can use `pak::pak()` to install all packages in `DESCRIPTION`.
2. Changing `format: pdf` is indeed the right thing to do in `_quarto.yml` but since PDF rendering is a bit different than HTML, you might need to add additional customizations. Unfortunately, we're not able to distribute the PDF in this repository since it's used as the basis for the print book.
