### ISSUE TITLE
Possible typo at 11.7 Summary

### ISSUE THREAD

**Issue by jAli9** [hadley/r4ds#1535]
This sentence might need a "the."

Original text:
This might seem painfully restrictive if you have tens or hundreds of variables in your data, but they’re foundation upon which all other techniques are built.

Suggested change:
This might seem painfully restrictive if you have tens or hundreds of variables in your data, but they’re **the** foundation upon which all other techniques are built.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
