### ISSUE TITLE
quote package names in all `library()` calls throughout the book

### ISSUE THREAD

**Issue by dlaehnemann** [hadley/r4ds#1541]
I keep coming back to this question in various contexts and finally did a cursory search for this question, prompted by non-quoted package names in this R book:

Wouldn't be a good default to *always* quote the package name in `library()` calls, to avoid unexpected side-effects where variable names identical to a package name exist?

There is a nice [question and answer regarding package name quotation on Stackoverflow](https://stackoverflow.com/a/36803188/2352071), which basically gives two reasons to always quote package names. Namely:

1. [The Journal of Statistical Software requires this in its "style guide"](https://www.jstatsoft.org/style#miscellaneous).
2. [Hadley's **Advanced R** book names exactly the above mentioned problem with variable names identical to package names as a downside of non-standard evaluation](http://adv-r.had.co.nz/Computing-on-the-language.html#nse-downsides).

Most important for me in this context is the reasoning behind `2.`, so I'll copy the example here (with a bit more context):

For a plain R environment, I get the following attached packages with `sessionInfo()`:
```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core

[...]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
[...]
```

I then run the example from the above link under `2.`, namely:
```
ggplot2 <- "plyr"
library(ggplot2)
```

If I then rerun `sessionInfo()`, I get these attached packages:
```
[...]

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.4.1

loaded via a namespace (and not attached):
 [1] utf8_1.2.3       R6_2.5.1         tidyselect_1.2.0 magrittr_2.0.3   gtable_0.3.1     glue_1.6.2       tibble_3.1.8     pkgconfig_2.0.3 
 [9] generics_0.1.3   dplyr_1.1.0      lifecycle_1.0.3  cli_3.6.0        fansi_1.0.4      scales_1.2.1     grid_4.3.0       vctrs_0.5.2     
[17] withr_2.5.0      compiler_4.3.0   rstudioapi_0.14  tools_4.3.0      munsell_0.5.0    pillar_1.8.1     colorspace_2.1-0 rlang_1.0.6
```

So the default seems to guard against the worst, which would be to have the `ggplot2 <- "plyr"` result in loading the `"plyr"` package with the command `library(ggplot2)`. But for being consistent and avoid confusing newcomers (and regularly bugging more experienced R users;), I would suggest to:

* [ ] Consistently quote the first argument in calls like `library("ggplot2")` throughout the book.
* [ ] Maybe do the same for the [other functions that have non-standard evaluation of arguments](http://adv-r.had.co.nz/Computing-on-the-language.html#nse-downsides).
* [ ] Reference the respective section of **Advanced R** somewhere (unless I just missed such a mention so far).

I'm glad to chip in with a PR here, but figured I'd first ask if not quoting package names was maybe some conscious choice with a good reason behind it.

**Comment by hadley** [comment]
We don't quote package names as a matter of style.

**Comment by hadley** [comment]
I couldn't find anywhere we've actually written this up but it's a long standing convention that we don't have plans to reconsider at the moment.
