### ISSUE TITLE
r4ds (1e) website preamble needs updating

### ISSUE THREAD

**Issue by aronatkins** [hadley/r4ds#1542]
From https://r4ds.had.co.nz

> You may instead want to consult the work-in-progress 2nd edition at http://r4ds.hadley.nz/; this should be complete by early 2023.

<img width="725" alt="image" src="https://github.com/hadley/r4ds/assets/362187/b7303f12-74d2-4a01-ba4a-e28fc0071dea">

The second edition has been released and it is no longer early 2023.

https://www.tidyverse.org/blog/2023/07/r4ds-2e/

**Comment by hadley** [comment]
Also need to link individual chapters to their corresponding updates, a la http://adv-r.had.co.nz/Data-structures.html

**Comment by hadley** [comment]
@mine-cetinkaya-rundel would you mind having a go? If you make the changes to https://github.com/hadley/r4ds/tree/first-ed-updates, I think it will just automatically update when you redploy. And if it doesn't, I can do the troubleshooting.

**Comment by mine-cetinkaya-rundel** [comment]
Looks like you'd already done most of this @hadley with e6fc2086dc9809ee01cb4dc5c2638e90d59928d0, I filled in just one missing pointer with 0037e2293793ce06d78d0362dff57c8115a51aa4.

**Comment by hadley** [comment]
Go me!
