### ISSUE TITLE
Exercise 5 in 10.5.1

### ISSUE THREAD

**Issue by pmur67** [hadley/r4ds#1543]
Exercise statement says "... we need to set group = 1." I think this must refer only to the first example, which does not include the fill aesthetic. For the second example, I think the intended fix is to have group = color, in addition to having fill = color. (Here, color is a variable in the diamonds data frame, not an aesthetic.) Perhaps the intention is for the reader to figure this out on their own, but I found it a little confusing.

**Comment by mine-cetinkaya-rundel** [comment]
Should have said "we needed to" referring to earlier plot. Thank you!
