### ISSUE TITLE
Issue in Table 18.1 : %e and %d switched?

### ISSUE THREAD

**Issue by AsdaeSunspark** [hadley/r4ds#1550]
Hello all,

I _may_ have found a problem with the date time format parameter to parse_date, or to this book's table. I think %e and %d may be switched, as %d handles 1-digit days just fine, but %e does not. This is my first contribution ever and I'm a bit lost, so sorry if I'm missing some etiquette, but here is a minimal reproducible example : 

```
# Works just fine, as intended in the documentation
parse_date("January 01 2010", format = "%B %d %Y")

# Also works, while the documentation says it should not
parse_date("January 1 2010", format = "%B %d %Y")

# Does not work, while the documentation says it should
parse_date("January 1 2010", format = "%B %e %Y")

# Works, in accordance with the documentation
parse_date("January 01 2010", format = "%B %e %Y")
```

Please tell me it's not just my computer ...

Yours truly,

Asdae

**Comment by mine-cetinkaya-rundel** [comment]
Is there a specific spot in the text where this is coming up for you?

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
