### ISSUE TITLE
Possible typo at 20.2.3

### ISSUE THREAD

**Issue by jAli9** [hadley/r4ds#1551]
"Particular" should probably be changed to "particularly" in section 20.2.3.

Original text:
Surrogate keys can be particular useful when communicating to other humans: it’s much easier to tell someone to take a look at flight 2001 than to say look at UA430 which departed 9am 2013-01-03.

Suggested change:
Surrogate keys can be particular**ly** useful when communicating to other humans: it’s much easier to tell someone to take a look at flight 2001 than to say look at UA430 which departed 9am 2013-01-03.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
