### ISSUE TITLE
Error in attempting to implement r4ds code

### ISSUE THREAD

**Issue by PananthanasZ** [hadley/r4ds#1556]
I am unable to access 'palmerpenguins' and 'ggthemes'. See below:

library(tidyverse)
> library(palmerpenguins)
Error in library(palmerpenguins) : 
  there is no package called ‘palmerpenguins’
> library(ggthemes)
Error in library(ggthemes) : there is no package called ‘ggthemes’
> library(palmerpenguins)
Error in library(palmerpenguins) : 
  there is no package called ‘palmerpenguins’

**Comment by javacup** [comment]
is it possible that you need to run the following?

install.packages("palmerpenguins")
library(palmerpenguins)

**Comment by PananthanasZ** [comment]
Yes.
Apparently I failed to install the package.
Thank you


_________________
Paul Zachos, PhD
Director, Research and Evaluation
Association for the Cooperative Advancement of Science and Education (ACASE)
110 Spring Street  Saratoga Springs, NY 12866  |  
***@***.***  |  www.acase.org

**Comment by PananthanasZ** [comment]
R4ds directs me to install 'ggthemes' but I don't seem to be able to do so. See below:
> library(ggthemes)
Error in library(ggthemes) : there is no package called ‘ggthemes’
> install.packages(ggthemes)
Error in install.packages : object 'ggthemes' not found
> library(ggthemes)
Error in library(ggthemes) : there is no package called ‘ggthemes’
> install.packages(ggthemes)
Error in install.packages : object 'ggthemes' not found
