### ISSUE TITLE
Clarification 

### ISSUE THREAD

**Issue by msgoussi** [hadley/r4ds#1558]
Dear Hadley,
Greeitngs.
I am wondering why you have used 100 as dominator not 60 (since hour is 60 minutes) in your equation
https://r4ds.hadley.nz/workflow-style#fnref1

Thanks.

**Comment by mine-cetinkaya-rundel** [comment]
In this dataset, `dep_time` given as `515` refers to 5:15. So it's not given as minutes since midnight, but as the hour and minutes concatenated.
