### ISSUE TITLE
problem installing ggthemes for Hadley

### ISSUE THREAD

**Issue by PananthanasZ** [hadley/r4ds#1560]

**Comment by PananthanasZ** [comment]
When I try to install ggthemes this is what happens

install.packages(ggthemes)
Error in install.packages : object 'ggthemes' not found

**Comment by mine-cetinkaya-rundel** [comment]
@PananthanasZ `ggthemes` should be quoted:

```r
install.packages("ggthemes")
```

**Comment by PananthanasZ** [comment]
Thank you.


_________________
Paul Zachos, PhD
Director, Research and Evaluation
Association for the Cooperative Advancement of Science and Education (ACASE)
110 Spring Street  Saratoga Springs, NY 12866  |  
***@***.***  |  www.acase.org
