### ISSUE TITLE
Chapter numbering on web ≠ print (off by one)

### ISSUE THREAD

**Issue by math-mcshane** [hadley/r4ds#1562]
The chapter numbering in the print and web version are off by one, which can/will make it confusing for professor and students. (I will be one such professor!)

The problem lies with the Introduction section, which is numbered as "Chapter 1" online although it is un-numbered in print. 

See below for comparison. 
![image](https://github.com/hadley/r4ds/assets/48807452/b9786076-cd40-41d1-9ab8-df965143b6a9)

My personal preference would be to change the web version as the "introduction" section online is the "what you will learn" section in print, and not necessarily content students will typically be asked to engage with. Obviously, there are open issues to deal with, but nipping this in the bud with 31 (now 32) open issues before students begin engaging with the content in the fall (starting imminently everywhere), will save the collective (writers and readers) more time.

**Comment by mine-cetinkaya-rundel** [comment]
Addressed in #1562.
