### ISSUE TITLE
recommendation: add subset example with summarize()

### ISSUE THREAD

**Issue by cdignam-chwy** [hadley/r4ds#1564]
Recommend adding an example using subset with summarize() since this is not often demonstrated. This was included in the first edition as the following example:

```
summarise(
    avg_delay1 = mean(arr_delay),
    avg_delay2 = mean(arr_delay[arr_delay > 0]) # the average positive delay
  )
```

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, we won't add this example at the time.
