### ISSUE TITLE
19.5.1 Cross joins

### ISSUE THREAD

**Issue by jcornickm** [hadley/r4ds#1569]
The text before and the caption of figure 20.14 describe a cross join between x and y, but the illustration itself shows a cross join between x and itself.  It is a small detail, but it might be confusing

**Comment by mine-cetinkaya-rundel** [comment]
@hadley Should we update the image or the caption and text? Latter is easier but does seem odd to join something with itself.

![image](https://github.com/hadley/r4ds/assets/5965649/7d1bb60f-491d-496f-a6aa-814dc3514b99)

**Comment by jcornickm** [comment]
So it seems you have answered your own question! It blows my mind that you, not somebody's assistant's assistant would answer something like this. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hadley** [comment]
I think it's ok to leave it as is; it's pretty common to do self-cross-joins and the main takeaway from the diagram is that every cell has a dot in it.

**Comment by jcornickm** [comment]
It is your book!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
