### ISSUE TITLE
Closing Databases

### ISSUE THREAD

**Issue by Hakarl22** [hadley/r4ds#1574]
To the authors:

I am having trouble with the code in this chapter.  When run it I get error messages and I can't render the document in Quarto.  As far as I can tell the issue lies in the fact that the database is not closed at the end of the session in the demos you give.  Thanks.

**Comment by beatrizmilz** [comment]
Hi @Hakarl22 ! I think it would be good to also cite which chapter you are referring to, so is easier for the authors to fix it :)

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback @Hakarl22. The book is rendered daily, so Quarto rendering is working. If you're still experiencing problems with this, please don't hesitate to reopen an issue with a reprex showing the errors you encounter so that we can better help.
