### ISSUE TITLE
Location of the code in the main text

### ISSUE THREAD

**Issue by jiehua-lee** [hadley/r4ds#1577]
When I read it, the code in the body text always appears centrally at the end of the paragraph, could you fix this please?

**Comment by mine-cetinkaya-rundel** [comment]
I'll close this for now since we haven't heard back but feel free to reopen with more detail if the issue persists.

**Comment by jiehua-lee** [comment]
I apologize for forgetting this feedback, this issue only occurs when the site is opened using edge.
![微信截图_20231213160500](https://github.com/hadley/r4ds/assets/128113720/6e6de5de-d7a3-403c-80ed-303b844b2047)
