### ISSUE TITLE
Consider mentioning that name of := operator

### ISSUE THREAD

**Issue by parmsam-pfizer** [hadley/r4ds#1591]
In [chapter 26.4.2](https://r4ds.hadley.nz/functions#data-frame-functions), the name of the `:=` operator isn't mentioned. This can make it hard to discuss.  Maybe could mention it as the walrus operator or colon equals operator, similar to the previous section on embracing. Thanks!

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
