### ISSUE TITLE
Warning message Section 21.3.3 DBI basics

### ISSUE THREAD

**Issue by jcornickm** [hadley/r4ds#1596]
The command

   `dbListTables(con)`

Generates the following warning:

> Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this. 

I have no idea that this means, but I thought you should be aware of it.  The following command, piping con into a tibble works just fine

**Comment by mine-cetinkaya-rundel** [comment]
Interesting, the chapter code runs continuously and we aren't seeing the message at https://r4ds.hadley.nz/databases#dbi-basics.
