### ISSUE TITLE
Section 21.1.1 Prerequisites

### ISSUE THREAD

**Issue by jcornickm** [hadley/r4ds#1597]
Souldn't duckdb be included among the Prerequisites?  It is used early in the chapter, in section 21.3.1, and even though that section indicated that it is an R package, it took me a second that I had to install it separatedly, ie. that it was not part of any of the libraries listend in Prerequistes.

Again, small potatoes that might, however, be confusing for those who are completely new to R

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback! We do this in a few places where we don't load the package and we use one or two functions from it with `::`. These packages are in `DESCRIPTION`, as well as at https://r4ds.hadley.nz/intro#other-packages.
