### ISSUE TITLE
Include non-Mac keyboard shortcut for visual editor

### ISSUE THREAD

**Issue by parmsam-pfizer** [hadley/r4ds#1607]
Right now, [28.3](https://r4ds.hadley.nz/quarto.html#visual-editor) recommends the catch-all ⌘ / shortcut to insert just about anything. However, some readers may not have the command key on their keyboards. Please consider also mentioning the Ctrl key + / shortcut for Windows keyboards. Thanks!

- https://quarto.org/docs/visual-editor/options.html#insert-anything
- https://en.wikipedia.org/wiki/Control_key#Notation

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
