### ISSUE TITLE
Exercise in 1.5.5 - linewidth as undefined parameter?

### ISSUE THREAD

**Issue by mreinaroca** [hadley/r4ds#1614]
Hi there!
I'm following all of the second edition of the book and in Exercise 3 of the 1.5.5. section is says: "In the scatterplot of `hwy` vs. `displ`, what happens if you map a third variable to `linewidth`?".  However, there is no parameter/aesthetic called `linewidth` not in the documentation nor as a factor in the dataset. When included in the code, R just ignores the parameter. So I would assume this is an error? Can someone correct me or fix this, please? This caused me a little confusion haha. 

![image](https://github.com/hadley/r4ds/assets/98564328/a6cca74d-7fbf-44f7-8a20-2678a4590cd0)

Thanks,
-MR

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the feedback. This is sort of the point of the exercise, that if you map a variable to an aesthetic that is not relevant, it's ignored.
