### ISSUE TITLE
Minor error in ch. 6.2.2

### ISSUE THREAD

**Issue by BensterW** [hadley/r4ds#1618]
In ch 6.2.2 it says "But you’re seven chapters into this book, and you’re no longer a beginner". The correct text should say "But you’re six chapters into this book, and you’re no longer a beginner".

I guess this was copied from the 1st edition where this is chapter 7 :)

Best regards

Benjamin Waldejer
University of Stavanger

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
