### ISSUE TITLE
Quotation marks in geom_smooth(method = "lm")

### ISSUE THREAD

**Issue by DominikaDomka** [hadley/r4ds#1620]
Hello,

I have realized that the code only works if geom_smooth(method = lm) does not have quotation marks over lm, otherwise the code is not running.

Thanks
Dominika

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the feedback. Would you specify where you're seeing `lm` without the quotes in the book?

**Comment by mine-cetinkaya-rundel** [comment]
I'm not able to find this in the book, and lm should have quotes around it, so I'll close this for now. Please feel free to reopen if you come across the issue again.
