### ISSUE TITLE
 Footer navigation error of  'Whole Game' section

### ISSUE THREAD

**Issue by luke396** [hadley/r4ds#1628]
https://r4ds.hadley.nz/whole-game

<img width="543" alt="image" src="https://github.com/hadley/r4ds/assets/77875500/fdf96da6-d1db-4872-9048-f52066e637fe">

Edit: maybe same as #1625

**Comment by mine-cetinkaya-rundel** [comment]
This is now fixed with a recent version of Quarto, thank you!
