### ISSUE TITLE
Some general errors found it in the book. 

### ISSUE THREAD

**Issue by lalgonzales** [hadley/r4ds#1630]
This part of the whole game section wasn't working.

![error](https://github.com/hadley/r4ds/assets/84168595/b93a2a7c-dae3-4f54-b77d-aa157a8af29a)

In the visualization section (1.2.4) this highlighted in yellow, the linear word and the m letter.
![image](https://github.com/hadley/r4ds/assets/84168595/92bd2356-a2d2-4bee-8ad8-8ded8b60094b)

At the end of chapter 1, same problem that happened in whole game.
![image](https://github.com/hadley/r4ds/assets/84168595/7a0c4b1f-d936-4873-a69d-ac4c5ba82466)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you for the feedback.

The navigation issue is now fixed.

The second one is intentional, to indicate where "lm" comes from.
