### ISSUE TITLE
Something wrong with the figure captions

### ISSUE THREAD

**Issue by gungorMetehan** [hadley/r4ds#1631]
"Introduction"
![figures](https://github.com/hadley/r4ds/assets/102655648/834172bb-15c7-4014-8978-38ee21a66de3)
![figures2](https://github.com/hadley/r4ds/assets/102655648/b308392d-be5d-49c1-ad4d-c62ce7d5e214)

"Whole game" Chapter
![figures3](https://github.com/hadley/r4ds/assets/102655648/301e0b07-5b6e-4dfe-a129-c9d31877529e)

**Comment by davidrsch** [comment]
Hello @gungorMetehan, just trying to help here, I have myself successfully rendered the book several times without encountering the issues you reported. Have you solved these issues? I am guessing are most likely related to the Quarto version or RStudio version you are using.

**Comment by gungorMetehan** [comment]
Hello @davidrsch, I didn't run the codes, I am just a reader. When I checked the relevant page a few minutes ago, I saw that the problem was fixed. So, you can close the issue. Thank you for your attention.

**Comment by davidrsch** [comment]
I am a reader just like you, must have being some issue then with the platform they use for publishing. But, as you mentioned It seems is fixed. @mine-cetinkaya-rundel issues related to this, that you may consider closing, are:
- Issue #1632 
- Issue #1630 
- Issue #1628 
- Issue #1625
