### ISSUE TITLE
Exercise 6 from 1.5.5 - Incorrect Code 

### ISSUE THREAD

**Issue by Luaaalex** [hadley/r4ds#1634]
See that the code offered is already correct.
The code did not repet the color = specie, shape = specie.

**Comment by davidrsch** [comment]
Hello @Luaaalex I believe the intention behind the exercise was to firstly execute the suggested code:
```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(color = "Species")
```
Obtaining the following output:
![image](https://github.com/hadley/r4ds/assets/72680874/c07d7a12-e0bb-4e80-9782-4458ed8cd74c)

Which indeed have two legends as stated in the exercise and then correct it:
```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point()
```
![image](https://github.com/hadley/r4ds/assets/72680874/9beefd0b-0a4f-4e0f-b87c-9e6c5856e9c6)

**Comment by mine-cetinkaya-rundel** [comment]
Indeed @davidrsch's explanation is correct, thanks!
