### ISSUE TITLE
Typo in chapter 25.2 Vector Functions

### ISSUE THREAD

**Issue by nppp** [hadley/r4ds#1638]
Hi,
This email to report the presence of a typo in Chapter 25.2.
In performing the rescaling of vector B, the minimum of A was subtracted (in the range calculation).
This results in a 5x4 tibble where vector B has values greater than 1.

![functions](https://github.com/hadley/r4ds/assets/34308088/58f17dca-f5c7-4594-85a1-6cb7fa7e911f)

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!

**Comment by althio** [comment]
It was not a mistake. 
It was on purpose, It is part of the explanation.
