### ISSUE TITLE
A tiny misprint in the caprion of Figure 12.1

### ISSUE THREAD

**Issue by DZornikov** [hadley/r4ds#1643]
Dear authors.
First of all, thanks a lot for a wonderful, or I would even dare to say incredible, book.
Second, I think it'll be fine if the book is perfect even in really small details. So, I noticed a misprint in the caption of Figure 12.1. The chunk *the shaded region show* should sound *the shaded regions show* or *the shaded region shows*.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
