### ISSUE TITLE
Advantages of frequency polygon

### ISSUE THREAD

**Issue by wibeasley** [hadley/r4ds#165]
https://github.com/hadley/r4ds/blob/56176ea369ecc03bc35d516a2003aee45eb2c467/model-basics.Rmd

In the exercise below, it's not clear to me what being compared (when you're asking about the advantages and disadvantages).    Are you asking about *absolute* vs *relative* residuals?  Are you asking about a *frequency polygon* vs some other geom/approach?

> Why might you want to look at a frequency polygon of absolute residuals? What are the advantages? What are the disadvantages?

**Comment by hadley** [comment]
Yeah, absolute vs regular.
