### ISSUE TITLE
Translation of R4DS 2ed in Chinese zh-CN

### ISSUE THREAD

**Issue by tianyeeT** [hadley/r4ds#1662]
I am writing to inquire whether there are any existing plans for a Chinese (zh-CN) translation of your materials. If no such plans are currently in place, I would like to express my interest in undertaking this task.

Thank you for your time and consideration. I look forward to your response.

**Comment by mine-cetinkaya-rundel** [comment]
@tianyeeT, could you email hadley@posit.co with your interest, and we can connect you with the publishers?
