### ISSUE TITLE
library Prerequisites for 21.1

### ISSUE THREAD

**Issue by dracodoc** [hadley/r4ds#179]
The code in `21.1` need library `tidyr` because of `expand()`, but `tidyr` is not included in Prerequisites. Actually `ggplot2` is also needed but not included, though that is kind of obvious.

Is it possible to have some shortcut to load libraries in Hadleyverse? For example, a line like `load("wrangle")` will load `tidyr`, `dplyr`, `stringr`,`lubridate` etc, `load("model")` will load all previous libraries plus `modelr`, `ggplot2`, and `load("Hverse")` load all current Hadleyverse packages.

I'm also using pacman because it can install packages if not already installed, so it's possible to run same code in other machine(all the `library()` lines will not run if not available already). It's not perfect yet but I didn't find better solution.

**Comment by hadley** [comment]
That'll get fixed once I start seriously re-writing that chapter. (The code is there, otherwise the chapter wouldn't compile, but I haven't printed it in the right place)

For this book, I think it's probably better to be explicit about which packages you need.
