### ISSUE TITLE
implicit vs. explicit

### ISSUE THREAD

**Issue by davidwolski** [hadley/r4ds#204]
Hi there, I was reading the section on tidy data just now and I think it's a great workup of both concept and package. 

The only thing that I think you might want to change is the sentence

> An implicit missing value is the presence of an absence; an explicit missing value is the absence of a presence.

where explicit and implicit should trade places.

As a reference, I think the book for ggplot2 got it right where it says:
> An `NA` is the presence of an absence; but sometimes a missing value is the absence of a presence.

Finally, a big thanks for writing this book, it's got a great deal of refreshing clarity. 
Best,
David Wolski

**Comment by hadley** [comment]
Ooops, yes, thanks!

**Comment by ay6z** [comment]
No thank to explicit vs implicit no thanks ,kindly remove please, kindly need assistance please , I issue third app of revanced 
![Screenshot_20241017_081647_Settings](https://github.com/user-attachments/assets/12188ff8-6eae-48c2-b44e-6152023f0854)
