### ISSUE TITLE
"[" -> "[[" in diagrams/lists-subsetting.png 

### ISSUE THREAD

**Issue by gergness** [hadley/r4ds#21]
Bottom right code snippet should be `a[[4]][[1]]` instead of `a[[4]][1]` in diagrams/lists-subsetting.png

**Comment by gergness** [comment]
![image](https://cloud.githubusercontent.com/assets/2104579/12124031/e8621682-b3a9-11e5-963c-88289890dde1.png)

**Comment by hadley** [comment]
Thanks - fixed!
