### ISSUE TITLE
Cannot install modelr

### ISSUE THREAD

**Issue by rcanand** [hadley/r4ds#245]
When I run the command in the [introduction page](http://r4ds.had.co.nz/introduction.html) to install the required packages, I get the following warning:

```
Warning in install.packages :
  package 'modelr' is not available (for R version 3.3.1)
```

I checked [the CRAN repo](https://cran.r-project.org/web/packages/available_packages_by_name.html#available-packages-M) - and did not find `modelr` there either.

I found the [modelr github page](https://github.com/hadley/modelr), and followed the instructions there to install from github directly.

**Comment by hadley** [comment]
It's not on CRAN, but will be soon.

**Comment by rcanand** [comment]
:thumbsup:
