### ISSUE TITLE
ggplot call at beginning of 3.5 facet_wrap is confusing

### ISSUE THREAD

**Issue by rcanand** [hadley/r4ds#246]
Uptil that point, ggplot call passed the mapping to the geom_point call. For example:

```{R}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

In the first example of 3.5, though, the mapping is specified on the ggplot call instead: 

```{R}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_wrap(~ class, nrow = 2)
```

It may be useful to clarify what the difference between the two approaches might be.

**Comment by sibusiso16** [comment]
I could be wrong but I think you may have missed a part in this chapter that explain the difference or it will be explained later in the chapter. One is used globally (last example) and the other is used internally (first example). If you add another plot to the first example you will get an error but the last example allows you to add more plots.

**Comment by hadley** [comment]
It gets explained later on, so this example should be made consistent with all the others.

**Comment by rcanand** [comment]
This last commit by hadley fixes the first instance of the changed section. There is another section referencing it in the exercise right below which also needs to be changed. 

BTW, sorry, [my PR](https://github.com/rcanand/r4ds/commit/4d346db2c5daeafe9211f4749f883f4ec813f7ac) had some extraneous garbage, but it shows the other changed section as well.
