### ISSUE TITLE
modelr

### ISSUE THREAD

**Issue by Dasonk** [hadley/r4ds#281]
You have

```
pkgs <- c("dplyr", "gapminder", "ggplot2", "jsonlite", "Lahman", 
  "lubridate", "modelr", "nycflights13", "purrr", "readr", 
  "stringr", "tibble", "tidyr"
)
install.packages(pkgs)
```

in the code but modelr isn't on cran as far as I can tell.  It should probably be removed (I haven't actually read the page so I don't know how necessary it is), made into a `devtools::install_github` call, or modelr should be put on CRAN.

**Comment by hadley** [comment]
Yes, because it will be on CRAN by the time the book is out
