### ISSUE TITLE
References to package names

### ISSUE THREAD

**Issue by pkq** [hadley/r4ds#283]
In some cases, you call out package names by making them bold, while in others, they are simply plain text. Is there a particular meaning behind the boldface? If not, it seems like it would be good to be consistent throughout. Also, it might be useful to provide a link to the relevant CRAN or Github page for each package, to make it easier for readers to get more information.

Thoughts?

**Comment by hadley** [comment]
Yes, they're bolded the first time you see them.

I figure people can google the package names if they want more info. Most of the non-primary packages do get a link.

**Comment by pkq** [comment]
Thanks for clarifying!
