### ISSUE TITLE
string about geom_smooth using method loess appears in many places

### ISSUE THREAD

**Issue by rcanand** [hadley/r4ds#288]
The string:

> #> `geom_smooth()` using method = 'loess'

appears in quote/code blocks in several (13) places in section 3.6. Particularly, in exercises 3.6.1, problem 6, it appears 5 times.

**Comment by rcanand** [comment]
10 of the 13 instances on that page are gone with this commit, but it still appears in 3 places on that same page (chapter 3). Also saw the same message at the end of the code block in section 5.6.1

**Comment by hadley** [comment]
Yes because it's an important message

**Comment by rcanand** [comment]
Thanks, @hadley - I thought it was left behind by mistake. 

I still do not understand the relevance of that message in this context by reading the text (I have read upto chapter 12 so far). I realize that this is the method used by the smoother - but since modeling is not introduced until much later, I don't see the relevance of this message.
