### ISSUE TITLE
Join diagrams (semi + anti)

### ISSUE THREAD

**Issue by bhive01** [hadley/r4ds#29]
I started writing you an email about this but felt it was better suited for here. I hope that was the correct decision. 
The join diagrams you have so far are really great. You've thought about this a lot more than me, so I'll throw out some ideas and a few questions:

**Question 1**
Is there a difference between an inner_join(x, y) and semi_join(x, y)? 

The only thing I can see is that the columns that are not joined by in y are dropped: 

Using your DS4R example:
```r
require(dplyr); require(nycflights13)

top_dest <- flights %>% # getting top ten destinations
    count(dest, sort = TRUE) %>%
    head(10)

semijoined <-flights %>% semi_join(top_dest)
flights %>% inner_join(top_dest)

flights %>% inner_join(top_dest) %>% anti_join(semijoined) #no different rows 0x17
flights %>% inner_join(top_dest) %>% anti_join(semijoined, .) #no different rows 0x16
#dropped n column from top_dest
```

**Opinion 1**
Representation of semi_join() should be the same as an inner_join(). 
![image](https://cloud.githubusercontent.com/assets/394973/12308597/dee4ef60-b9fa-11e5-90d7-f70819e27f41.png)
In this example, there are literally no difference between the two. 
```r
x <- data_frame(key = c(1, 2, 3), val_x = c("x1", "x2", "x3"))
y <- data_frame(key = c(1, 2, 4), val_y = c("y1", "y2", "y3"))
semi_join(x, y, by="key")
```
I'd love to know if I'm missing something. 

**Opinion 2**
Representation of the anti_join() could use the full join figure. 
http://r4ds.had.co.nz/diagrams/join-outer.png
![image](https://cloud.githubusercontent.com/assets/394973/12308912/c9c3ef30-b9fc-11e5-9513-09d73b18debe.png)

In the case of anti_join(x,y) you would only get the 3-X3 row as the output. I don't think it needs to be more complex than that. 

**Question 2**
Is there such a thing as a full_anti_join?
In this case, you would get rows that exist in x and aren't in y and rows that aren't in x but exist in y. Essentially: 
```r
full_join(anti_join(x,y), anti_join(y,x))
```

**Comment 1**
In the join.graffle file, I had to uncheck "wrap to shape" to get the NAs to fit in their boxes. Not sure why it looks great on the site and messed up in the file.

**Comment by hadley** [comment]
The big difference is that semi/anti joins don't affect the columns at all. I think that suggests a slighty different representation is important. 

Other big difference is what happens when there are multiple matches.

**Comment by bhive01** [comment]
Holy crap💡
I didn't see the output difference, because my brain filled it in and said, "that's right". So, using your original diagram, the output should be this:
![semianti](https://cloud.githubusercontent.com/assets/394973/12309853/bfe80366-ba01-11e5-8482-7caba4cca077.png)

This is pretty clear actually for this simple case. I'll try and play with the multiple matches and see what it does, because I've never done that before.

**Comment by hadley** [comment]
I just added a couple of pics. Let me know what you think.

**Comment by bhive01** [comment]
I like the colored dots across the lot. It's easier to visually connect... the dots. 🙃
And the semi/semi-many/anti joins with the incomplete lines makes it more clear what's being transferred to the final product. 

I am a little unsure about the anti-join. In all of the other ones, you're highlighting what is connected and transferred to the product, but in the anti- you're highlighting what isn't transferred the to product. Sticking with the theme would look something like this:
![antijoin](https://cloud.githubusercontent.com/assets/394973/12330137/700cccc2-ba98-11e5-9b8a-ec98ac3f8fe3.png)

I would really like to remove the NA in x, since it is irrelevant to the product, but I only seem to bungle it up when I do (especially the line angles!). [note to self, turn off "snap to grid"]

Like this I mean:
![antijoin2](https://cloud.githubusercontent.com/assets/394973/12330503/54eae918-ba9a-11e5-94a6-148512091a79.png)
The greyed out circles stay grey so they aren't highlighted and the red one is in the product because it doesn't connect. 

I think they look awesome though and I'm definitely using them all in my presentation. 
![t hanks small](https://cloud.githubusercontent.com/assets/394973/12330325/6a279eee-ba99-11e5-9251-81ab973c95a8.jpg)
