### ISSUE TITLE
Figure in 13.4.4 duplicate keys section missing a solid line 

### ISSUE THREAD

**Issue by rcanand** [hadley/r4ds#295]
The figure at the top of section 13.4.4, depicting an inner join with duplicate  keys does not have a solid line from the last x row with key 1 to the green dot corresponding to it in the join space. 

![image](https://cloud.githubusercontent.com/assets/303900/17835616/8b79baf4-6792-11e6-9553-b9cc97261e4b.png)

**Comment by hadley** [comment]
Thanks - fixed!

**Comment by rcanand** [comment]
👍
