### ISSUE TITLE
4 minor typos

### ISSUE THREAD

**Issue by ehtamoel** [hadley/r4ds#331]
1. *In 23.1 Introduction:* The goal of a model is to provide a simple low-dimensional summary of a dataset. In the context of    this book we’re going to use models to partition data into patterns and residuals. Strong patterns will hide subtler trends, so we’ll use models to help peel back layers of structure as we explore a **datasets**.

2. *In 23.2 A simple model:* One common way to do this in statistics **is the to use the** “root-mean-squared deviation”. We compute the difference between actual and predicted, square them, average them, and the take the square root. This distance has lots of appealing mathematical properties, which we’re not going to talk about here. You’ll just have to take my word for it!

3. *In 23.3 Visualising models:*  For simple models, like the one above, you can figure out what pattern the model captures by carefully studying the model family and the fitted coefficients. And if you ever take a statistics course on modelling, you’re likely to spend a lot of time doing just that. Here, however, we’re going to take a different **tack**. *(I am not sure here ...)* 

4. *In 27.3 Text formatting with Markdown:* Prose in .Rmd files is written in Markdown, a light weight set of conventions for formatting **plan** text files

**Comment by hadley** [comment]
Thanks! In the future, feel free to open fix them directly and submit a pull request.

**Comment by ehtamoel** [comment]
Great! Next time:-)
