### ISSUE TITLE
object 'morley' not found when kniting EDA.Rmd

### ISSUE THREAD

**Issue by adamryczkowski** [hadley/r4ds#441]
```
Quitting from lines 87-95 (EDA.Rmd) 
Error in matrix(morley$Speed + 299000, ncol = 10) : 
  object 'morley' not found
Calls: local ... withVisible -> eval -> eval -> as.data.frame -> matrix
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile EDA.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted
```

Actually I have the same error with each standard dataset (residing in the `datasets` namespace). Is there any quick way to fix it (besides editing the r4ds)?

My walkaround is to find each instance of the dataset you use and prepend it with `datasets::`.

**Comment by hadley** [comment]
You must be running in some non-standard environment, because it should just work. You should be able to resolve the problem with `library(datasets)`
