### ISSUE TITLE
Writing functions with magritt

### ISSUE THREAD

**Issue by blaquans** [hadley/r4ds#45]
In the chapter `functions.Rmd`, you write 

> This fails because it tells dplyr to group by group_var and compute the mean of mean_var neither of which exist in the data frame. Writing reusable functions for ggplot2 poses a similar problem because aes(group_var, mean_var) would look for variables called group_var and mean_var. It's really only been in the last couple of months that I fully understood this problem, so there aren't currently any great (or general) solutions.

So I'm just wondering if there is any solution to write that kind of functions. I think it would be really valuable for everyone.

**Comment by hadley** [comment]
Yes, obviously I'll work on thst

**Comment by blaquans** [comment]
There is a temporary solution on [StackOverflow](http://stackoverflow.com/questions/35345986/how-can-i-use-dplyr-magrittrs-pipe-inside-functions-in-r) : using `substitute()` outside the pipe.

**Comment by hadley** [comment]
@blaquans that is not a good solution
