### ISSUE TITLE
\emph{} not working?

### ISSUE THREAD

**Issue by yahwes** [hadley/r4ds#461]
In import.Rmd, the text "**It is \emph{not} Eastern Standard Time!**" is showing up as "**It is Eastern Standard Time!**" on my browser. See [screenshot](https://www.dropbox.com/s/9gurfgtev5biv5h/Screenshot%202016-10-08%2014.32.27.png?dl=0). I'm running Chrome for Mac version 53.0.2785.116 (64-bit).

**Comment by tteo** [comment]
This is a typo: \emph{} is LaTeX code. I've submitted a pull request to fix this.
