### ISSUE TITLE
Ch. 4 Q1 my_varıable

### ISSUE THREAD

**Issue by sedaghatfar** [hadley/r4ds#491]
Ch4 , first question
http://r4ds.had.co.nz/workflow-basics.html#practice

my_variable <- 10
my_varıable
# > Error in eval(expr, envir, enclos): object 'my_varıable' not found

I see that "my_varıable" does not have a dot on top of the i, but I am not seeing the same error when running locally

Using:
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Screenshot:
http://imgur.com/a/Wo3sd

**Comment by sedaghatfar** [comment]
Seems to be a windows issue, not reproducible when using linux

Screenshot:
http://imgur.com/a/PzY7s

**Comment by hadley** [comment]
You probably assigned something into that variable previously in the session; perhaps during experimentation?

**Comment by sedaghatfar** [comment]
I don't believe I did, but just in case restarted rstudio and reproduced the error. attached please find a screenshot of my console and what I have in my environment.

![image](https://cloud.githubusercontent.com/assets/3936021/25662290/0691a3ba-2fe2-11e7-910d-7007ee73c362.png)



Another example: https://twitter.com/CannedMan/status/785807898370723841

Likely due to the way windows treats dotless i's https://en.wikipedia.org/wiki/Dotted_and_dotless_I
