### ISSUE TITLE
3.6.1 Exercises typo

### ISSUE THREAD

**Issue by mbedward** [hadley/r4ds#499]
In 3.6.1 exercises, Q3:
What does `show.legend = FALSE` do? 

perhaps that should that read:
What does `se = FALSE` do?

But that seems to duplicate Q4. The only reference to `show.legend` in chapter 3 is further down in section 3.9

**Comment by hadley** [comment]
I think that might have been an issue due to a missing `show.legend` in a previous example. Now fixed.
