### ISSUE TITLE
Do we also need "export" chapter?

### ISSUE THREAD

**Issue by hadley** [hadley/r4ds#5]
Rmarkdown and shiny chapters will talk about communicating with other humans, but it's probably worthwhile to think about what a chapter about communicating with other programs might look like.  By parallel to the import section, it might contain:

* saving csv files
* loading data into a database
* exporting to excel, spss, sas, etc.
* uploading data to a web api

(To be comprehensive, it would probably need a decent amount of software engineering, since, e.g., readxl currently doesn't do exports)

**Comment by garrettgman** [comment]
I like the idea, if there is good software to teach. I like it because
exporting data helps complete the story:

import -> tidy -> explore -> model -> communicate -> save

**Comment by rlzijdeman** [comment]
Hi, i'd applaud such a section or chapter. Not sure why the missing export function on readxl is relevant, exporting as .csv would also allow for importing in excel, if ppl wanted to do that. perhaps beyond the scope of the book, but i'd also be interested in a section on using R to export data as Linked Data.

**Comment by hadley** [comment]
Now a little bit at the end of import.
