### ISSUE TITLE
23.4.2 - error in equation

### ISSUE THREAD

**Issue by lmadsenbc** [hadley/r4ds#507]
Under **Interactions (continuous and categorical)**

> For example, y ~ x1 * x2 is translated to y = a_0 + a_1 * a1 + a_2 * a2 + a_12 * a1 * a2. Note that whenever you use *, both the interaction and the individual components are included in the model.

Is this equation correct?  Should it not be: `y = a_0 + a_1 * x1 + a_2 * x2 + a_12 * x1 * x2 ` ?
That is, a1 should be x1.

**Comment by hadley** [comment]
Fixed now, thanks.
