### ISSUE TITLE
12.3.1 - Confusion around non-syntactic names

### ISSUE THREAD

**Issue by lmadsenbc** [hadley/r4ds#509]
>The columns to gather are specified with dplyr::select() style notation. Here there are only two columns, so we list them individually. Note that “1999” and “2000” are non-syntactic names so we have to surround them in backticks. To refresh your memory of the other ways to select columns, see select.  

I'm new to R, and this is just my opinion.  
It took me a few minutes to track down why those column names are non-syntatic.  You may want to explicitly include the fact that syntactic R variable names must start with either a letter or a dot.

**Comment by hadley** [comment]
Thanks!
