### ISSUE TITLE
3.6.1 Exercises // Little error in asked question.

### ISSUE THREAD

**Issue by Adrianzo** [hadley/r4ds#510]
The third question says "What does show.legend = FALSE do? What happens if you remove it?
Why do you think I used it earlier in the chapter?". But the 'show.legend = FALSE' was'nt used earlier in the chapter (I've just checked).

**Comment by cportner** [comment]
Possibly should be `se = FALSE`, which would fit with being used earlier.

**Comment by hadley** [comment]
Fixed now, due to problem with earlier example.
