### ISSUE TITLE
Duplicated example

### ISSUE THREAD

**Issue by gg88** [hadley/r4ds#513]
In section 3.6 "Geometric objects" , the 4th set of plots has two duplicates, i.e. 2 of the 3 graphs are the same, generated by the same lines of code: 

ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))

**Comment by gg88** [comment]
In the section "7.5.1 A categorical and continuous variable", the length of the double arrow for the label "1.5*IQR"  is shown incorrectly: it should extent over the length of the the top whisker, not the distance from the top of the box plot and the 1st outlier.

**Comment by gg88** [comment]
In the section "10.2 Creating tibbles" there is a typo: instead of "For example, they might not start with a **letter**, " it should read "For example, they might not start with a **digit**,".

**Comment by gg88** [comment]
In the section "11.6 Other types of data" provided link https://jennybc.github.io/purrr-tutorial/examples.html is not working.

**Comment by hadley** [comment]
Thanks!
