### ISSUE TITLE
Shading in Figure 3.1 does not appear in print version

### ISSUE THREAD

**Issue by rogilmore** [hadley/r4ds#519]
The figure in the Logical Operators section on p. 47 of the printed book does not have the shading found in the diagrams/transform-logical.png file.

**Comment by hadley** [comment]
Yeah, unfortunately the printing process turned all the pale greys into white. Consider colouring it in an exercise for the reader ;)

**Comment by rogilmore** [comment]
I like that solution!

Keep up the great work.
