### ISSUE TITLE
first sentence of penultimate paragraph in page 10

### ISSUE THREAD

**Issue by mocalvao** [hadley/r4ds#530]
After "For each aesthetic you use", there must be a correction to the phrase beginning with "the aes() to associate...". Right now, it does not make sense; perhaps change to: "employ aes() to associate..."

**Comment by hadley** [comment]
It reads ok to me:

> For each aesthetic, you use `aes()` to associate the name of the aesthetic with a variable to display.

Might've been fixed since you fixed this issue.
