### ISSUE TITLE
3.7.1 Exercises #2: geom_col() no longer exists?

### ISSUE THREAD

**Issue by luiscrouch** [hadley/r4ds#540]
This question asks what `geom_col()` does, but it no longer seems to be included with `ggplot2`. Documentation is available online, but `?geom_col` and `??geom_col` within R both return nothing.

**Comment by sibusiso16** [comment]
This means you haven't loaded ggplot2 your session

**Comment by luiscrouch** [comment]
@sibusiso16 had it loaded, but not updated. Apparently installing tidyverse does not force updates on already-installed dependent packages. Regardless, closing issue.
