### ISSUE TITLE
difference in definition of tidy data between r4ds and tidy data paper

### ISSUE THREAD

**Issue by whao89** [hadley/r4ds#541]
First off, I have not found discussion of this topic anywhere, but it could exist somewhere casual like a twitter conversation. 

I noticed a slight rewording of the rules governing tidy data in r4ds when compared to the original tidy data paper. Rule 3 has changed from "Each type of observational unit forms a table" to "Each value must have its own cell." This change seems to have consequences that affect the examples in the original paper. In particular, under the r4ds rules, I think table 8 in the paper is technically tidy already, and does not need to be normalized into table 13.

Does this change reflect an evolution in the tidy philosophy?

**Comment by hadley** [comment]
It's just a change in wording that most people seem to find easier to understand. We don't rely discuss "relational" tidyness in this book.
