### ISSUE TITLE
Median line position in boxplot - EDA.Rmd

### ISSUE THREAD

**Issue by momenezes** [hadley/r4ds#551]
Median is not in the middle of the box, but inside it. The figure shown below the text (rightmost one) shows the median line far below the middle of the box.[EDA.Rmd](https://github.com/hadley/r4ds/edit/master/EDA.Rmd)
This is near line 319 of EDA.Rmd file

Regards, 
Mário

**Comment by hadley** [comment]
I think that's close enough for a casual definition. I don't want to overwhelm people with precision here.
