### ISSUE TITLE
Vectors: Confusing? Intentional?

### ISSUE THREAD

**Issue by saghirb** [hadley/r4ds#555]
In section 20.5.2 Subsetting (Print: p. 304)

> a <- list(a = 1:3, b = "a string", c = pi, d = list(-1, -5))

Was it intentional to have "a" as the list name and "a = 1:3" inside the same list? Part of me feels perhaps yes but it may confuse newer R users if that was not the case.

**Comment by hadley** [comment]
Yes, you need to learn that different things can have the same name in different places at some point.
