### ISSUE TITLE
General Issue: Datasets

### ISSUE THREAD

**Issue by saghirb** [hadley/r4ds#559]
**Structural Change:** 

After reading the "Exploratory Data Analysis" chapter I realised that 4 datasets (diamonds, mpg, faithful and flights) had been used in that chapter alone! I knew three of the four dataset _a priori_. Newcomers that I shared it with found it overwhelming. This is not surprising as data scientists in their real life jobs don't change datasets so often in any given day if at all.

For the second edition could you please at least consider including a Chapter or Appendix to explain the datasets used throughout the book. Perhaps also consider focusing on fewer datasets and exclude some that are less "universal" (I get groans for the mpg, baseball and diamonds datasets when I used them as an example).

**Thanks!**

**Comment by hadley** [comment]
These are all introduced earlier in the book. Unfortunately, it's just not possible to illustrate all the key EDA techniques with a single dataset.
