### ISSUE TITLE
General Issue: _Almost_ Real Life Example

### ISSUE THREAD

**Issue by saghirb** [hadley/r4ds#560]
**Structural Change** (Nice to have)

One of the issues that I hear often people learning R is "How does it all fit together?" The underlying request is "show me a real life data science example demonstrating how the _pieces_ fit together based on what I have learnt". It does not need to cover all the chapters or points raised. 

Perhaps a Chapter or an Appendix could help. This is more of a nice to have than a must so a link to an example might be enough.

Thanks!

**Comment by hadley** [comment]
That's currently out of scope for this book.
