### ISSUE TITLE
Minor Issue: Print versus Web graph (Themes)

### ISSUE THREAD

**Issue by saghirb** [hadley/r4ds#561]
Chapter (print 22 & Web 28): Graphic for Communication with ggplot2
Section Theme (Print p 463, Web Section 28.6): First plot - 
http://r4ds.had.co.nz/communicate-plots_files/figure-html/unnamed-chunk-31-1.png

On my print version the grid lines are not visible compare to the web version. Perhaps something like theme_linedraw() is better for the print version compare to theme_bw().

**Comment by hadley** [comment]
All the pale greys in the print book were printed as white :(
