### ISSUE TITLE
Chpt 3.6: Geometric Objects- some parameter missing that plots 3 graphs in a row

### ISSUE THREAD

**Issue by duttashi** [hadley/r4ds#565]
Foremost, thank you for this wonderful book and putting it online for free.

I'm following the online version of the book, so the page number is not visible. 
In chapter 3.6 on Geometric Objects, after this paragraph, _"Many geoms, like geom_smooth(), use a single geometric object to display multiple rows of data. For these geoms, you can set the group aesthetic to a categorical variable to draw multiple objects. ggplot2 will draw a separate object for each unique value of the grouping variable. In practice, ggplot2 will automatically group the data for these geoms whenever you map an aesthetic to a discrete variable (as in the linetype example). It is convenient to rely on this feature because the group aesthetic by itself does not add a legend or distinguishing features to the geoms."_ , the following code is duplicate;

`ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
   
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, group = drv)
  )`

The plots are correct, but you have shown them in a single row. Following the above code snippet, I' do not see how the three graphs can be plotted on a single row.

Thanks.

**Comment by cportner** [comment]
I believe the last one should be
`ggplot(data = mpg) +
    geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))`
for the example to make sense. The text refers to `group` not labeling outcomes.

**Comment by hadley** [comment]
Yeah, fixed now. Thanks!
