### ISSUE TITLE
Factor Reordering section - clarify relig data frame vs. factor

### ISSUE THREAD

**Issue by bbrewington** [hadley/r4ds#576]
I would recommend calling the summary data frame (tibble?) "relig_summary" or "relig_df", to make it more clear in the ggplot call with fct_reorder which is the data frame and which is the factor variable

![image](https://cloud.githubusercontent.com/assets/10573749/25282697/42067298-267f-11e7-90c3-aaf5fe8fdb2f.png)

![image](https://cloud.githubusercontent.com/assets/10573749/25282717/512a2c60-267f-11e7-8935-aeeae925a9e4.png)

**Comment by bbrewington** [comment]
I know this may seem like a moot point, but I was pretty confused by the naming at first (when I was just looking at the ggplot call, and before I ran the code myself to inspect)

**Comment by hadley** [comment]
Want to do a PR?

**Comment by bbrewington** [comment]
Done - https://github.com/hadley/r4ds/pull/577
