### ISSUE TITLE
Communicate your work: add subchapter on OpenCpu?

### ISSUE THREAD

**Issue by mrustl** [hadley/r4ds#58]
I love "shiny" for rapid prototypeing. However, in production based context the OpenCPU API (http://www.opencpu.org) is a valuable alternative, that does not only scale well but also enables to separate backend (R package) from front-end development. Thus I really appreciate if you spread a word about the OpenCPU alternative in your upcoming book.

**Comment by hadley** [comment]
I personally don't believe that's something you need until you're working with a much larger team, so it's unlikely it will be covered in the book.
