### ISSUE TITLE
add separate_rows() to tidyr chapter

### ISSUE THREAD

**Issue by bheavner** [hadley/r4ds#581]
In general, the tidyr chapter introduces column-centric manipulations, but finding saparate_rows() after reading the chapter saved me lots of time re-implementing it! As this is the suggested place to learn about the tidyverse, including more functions in a future edition will be great!

**Comment by krlmlr** [comment]
Seconded, though I find `separate_rows()` is doing too much. The same could be achieved with a verb that separates into a list column, and then unnesting (tidyverse/tidyr#309).

**Comment by hadley** [comment]
I think `separate()` and `separate_rows()` will move to the strings chapter, and will be explained as useless special cases of general operations.
