### ISSUE TITLE
invoke_map with tribble example throws an error

### ISSUE THREAD

**Issue by AndrewKostandy** [hadley/r4ds#585]
Running the below example with a list (copied from the book) works fine:

```
f <- c("runif", "rnorm", "rpois")  
param <- list(
  list(min = -1, max = 1), 
  list(sd = 5), 
  list(lambda = 10)
)
invoke_map(f, param, n=5) %>% str()
```

However, running it with a tribble (copied from the book) throws an error:

```
sim <- tribble(
  ~f,      ~params,
  "runif", list(min = -1, max = 1),
  "rnorm", list(sd = 5),
  "rpois", list(lambda = 10)
)
sim %>% 
  mutate(sim = invoke_map(f, params, n = 10))
```

**Error in vapply(x, obj_sum, character(1L)) : values must be length 1,
 but FUN(X[[1]]) result is length 2**

UPDATE:
The second piece of code seems to work in the RStudio Console but not within an R Markdown document. I've copied and pasted so it isn't a typo.

![screen shot 2017-06-03 at 3 43 16 am](https://cloud.githubusercontent.com/assets/13706356/26748518/860f011a-480f-11e7-8143-5efd182468e9.png)

![screen shot 2017-06-03 at 3 50 13 am](https://cloud.githubusercontent.com/assets/13706356/26748560/d43d3ec4-480f-11e7-8901-4d4d67965ca9.png)

**Comment by EllaKaye** [comment]
I got the same thing too. It seems to be an RStudio bug, according to an issue flagged here: https://github.com/tidyverse/googledrive/issues/99

**Comment by alexhallam** [comment]
Same issue. As stated from [tidyverse/googledrive#99](https://github.com/tidyverse/googledrive/issues/99) Changing the chunk output settings from "Chunk Output Inline" to "Chunk Output in Console" works as a temporary fix.

**Comment by EllaKaye** [comment]
I've updated to RStudio 1.1 and this bug now seems to be fixed.

**Comment by hadley** [comment]
Seems to work fine for me now:

``` r
library(tidyverse)

sim <- tribble(
  ~f,      ~params,
  "runif", list(min = -1, max = 1),
  "rnorm", list(sd = 5),
  "rpois", list(lambda = 10)
)
sim %>% 
  mutate(sim = invoke_map(f, params, n = 10))
#> # A tibble: 3 x 3
#>   f     params           sim       
#>   <chr> <list>           <list>    
#> 1 runif <named list [2]> <dbl [10]>
#> 2 rnorm <named list [1]> <dbl [10]>
#> 3 rpois <named list [1]> <int [10]>
```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
