### ISSUE TITLE
parse_number with locales

### ISSUE THREAD

**Issue by camillalindelow** [hadley/r4ds#592]
In section 11.3.1 Numbers this example:

parse_number("It cost $123.45")
#> [1] 123 #assuming default locale this will not be the output, it should be:
#> [1] 123.45

The example should probably be something like this
parse_number("It cost €123,45") to give a non-default example:
#> [1] 12345

**Comment by hadley** [comment]
I think the problem is the printing, not the example:

``` r
readr::parse_number("It cost $123.45")
#> [1] 123.45
```

<sup>Created on 2020-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
