### ISSUE TITLE
15.4 Factor Reordering Section

### ISSUE THREAD

**Issue by cardiomoon** [hadley/r4ds#593]
In the section 15.4, the R code can not reproduce the plots.  

## Original Code

```r
library(tidyverse)
library(forcats)

by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  group_by(age, marital) %>%
  count() %>%
  mutate(prop = n / sum(n))

by_age
```

```
# A tibble: 351 x 4
# Groups:   age, marital [351]
     age       marital     n  prop
   <int>        <fctr> <int> <dbl>
 1    18 Never married    89     1
 2    18       Married     2     1
 3    19 Never married   234     1
 4    19      Divorced     3     1
 5    19       Widowed     1     1
 6    19       Married    11     1
 7    20 Never married   227     1
 8    20     Separated     1     1
 9    20      Divorced     2     1
10    20       Married    21     1
# ... with 341 more rows
```

```r
ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")
```

![unnamed-chunk-2-1](https://user-images.githubusercontent.com/7410607/28352905-0571da1a-6c94-11e7-8b40-79304e104d2b.png)![unnamed-chunk-2-2](https://user-images.githubusercontent.com/7410607/28352911-0ca43a12-6c94-11e7-89e6-85d2de07d08c.png)

## Modified Code

You can get the desired result by adding one step: `group_by(age)`.

```r
by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  group_by(age, marital) %>%
  count() %>%
  group_by(age) %>%         ## This step should be added 
  mutate(prop = n / sum(n))

by_age
```

```
# A tibble: 351 x 4
# Groups:   age [72]
     age       marital     n        prop
   <int>        <fctr> <int>       <dbl>
 1    18 Never married    89 0.978021978
 2    18       Married     2 0.021978022
 3    19 Never married   234 0.939759036
 4    19      Divorced     3 0.012048193
 5    19       Widowed     1 0.004016064
 6    19       Married    11 0.044176707
 7    20 Never married   227 0.904382470
 8    20     Separated     1 0.003984064
 9    20      Divorced     2 0.007968127
10    20       Married    21 0.083665339
# ... with 341 more rows
```

```r
ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")
```
![unnamed-chunk-3-1](https://user-images.githubusercontent.com/7410607/28352914-135c3422-6c94-11e7-90a6-ce131baa05a8.png)![unnamed-chunk-3-2](https://user-images.githubusercontent.com/7410607/28352915-1384cf22-6c94-11e7-9278-c34ee48e77e6.png)

**Comment by pschloss** [comment]
We're seeing this in my lab group - those of us using 3.4.X the original code doesn't work, but those with 3.3.X get the original code to work.

**Comment by NLesniak** [comment]
This appears to be an issue with tidyr. Features added in version 0.7.0 are causing this issue. Issue #610 opened by @tmelconian gives more information on this issue and how to update the lesson to work with both versions

**Comment by mbac** [comment]
Hi,

I was able to get the example in the book working by using `ungroup()` instead of a second round of `group_by()`. Could you please explain how would that be different in other cases?

(I mean, in the book…)
