### ISSUE TITLE
In 15.4 - marital proportion plot doesn't work

### ISSUE THREAD

**Issue by jchase111** [hadley/r4ds#600]
Proposed replacement code

by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  group_by(age, marital) %>%
  **summarise(count=n()) %>%
  mutate(prop = count / sum(count))**

ggplot(by_age, aes(age, prop, colour = marital)) +
  geom_line(na.rm = TRUE)

ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")

**Comment by hadley** [comment]
I think this was fixed in #610
