### ISSUE TITLE
3.7.  Stat_summary code doesn't work

### ISSUE THREAD

**Issue by jchase111** [hadley/r4ds#606]
Current
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )

Suggested update
ggplot(data = diamonds) + 
   stat_summary(
   mapping = aes(x = cut, y = depth), 
   fun.y = "median",
   fun.ymin = "min",
   fun.ymax = "max"
)

**Comment by hadley** [comment]
Now fixed
