### ISSUE TITLE
failing to compile the book

### ISSUE THREAD

**Issue by alperyilmaz** [hadley/r4ds#608]
I cloned 0f956d64 from this repo and when I try to compile the book with `bookdown:::serve_book()`, in both Windows and Linux, I got the same error.

The error message was:
```
Quitting from lines 144-151 (model-building.Rmd) 
Error in overscope_eval_next(overscope, expr) : object 'G' not found
Calls: local ... lst_quos -> eval_tidy -> overscope_eval_next -> .Call

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile model-building.Rmd
```

What am I doing wrong here?

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  backports_1.1.0 bookdown_0.5    magrittr_1.5    rprojroot_1.2   htmltools_0.3.6
 [7] tools_3.4.1     rstudioapi_0.7  yaml_2.1.14     Rcpp_0.12.12    stringi_1.1.5   rmarkdown_1.6  
[13] knitr_1.17      stringr_1.2.0   digest_0.6.12   evaluate_0.10.1
```

**Comment by Facottons** [comment]
I got the PDF, after some errors, some very similar to yours. In my case the error messages was not very clear about the error itself and about the error line. So my advice is to check the root folder after a error. If you look closely you have strings.Rmd and strings.knit.Rmd (or something like that) files in the folder.
Open both files, side by side.
Go to last line in strings.knit.Rmd (or something like that) and see which code chunk was the root of your problem.
After that, add eval = FALSE in strings.Rmd {r} and rerun knit.
Repeat this process until you will have the PDF rendered book.

Of course this in some cases could not be the best, or even the correct solution. But it worked for me, the only trick that works, after many tries, uploading packages and Latex.

**Comment by alperyilmaz** [comment]
The method suggested by @Facottons can be used to render the book in case of errors I guess. But I was trying to pinpoint the problem although I'm not good at debugging R. Based on the [discussion](https://stackoverflow.com/questions/30159162/linear-model-with-categorical-variables-in-r) regarding how ordered factors handled, I tried to verify that was indeed the problem.

I changed line [121](https://github.com/hadley/r4ds/blame/master/model-building.Rmd#L121) in model-building.Rmd into this (color, cut and clarity are wrapped around `as.numeric()`:
```
mod_diamond2 <- lm(lprice ~ lcarat + as.numeric(color) + as.numeric(cut) + as.numeric(clarity), data = diamonds2)
```
and it still I get error in line [128](https://github.com/hadley/r4ds/blame/master/model-building.Rmd#L128). The code below cannot accomadete the model well.
```
grid <- diamonds2 %>% 
  data_grid(cut, .model = mod_diamond2)
```

**Comment by alperyilmaz** [comment]
Forget to mention, if I comment out the chunk (or convert into a regular code block) between lines 126-134, the book compiles without problems.

**Comment by rezabakhtiari** [comment]
one maybe naive question, because I get also the same error of "lines 144-151 (model-building.Rmd) ". How can I completely comment out this file (model-building.Rmd) ? I am interested in other parts of the more, so I can live without this!

Thanks!

**Comment by Ranae** [comment]
I also had trouble compiling the book, but only as a pdf.  Adding `always_allow_html: yes`, was suggested, but did not seem to do anything at all. In the end, I compiled most of the book by doing the following two things: 

1. Got around the model-building problem by making this replacement as suggested [here](https://github.com/tidyverse/modelr/issues/58): 

grid <- diamonds2 %>%
data_grid(cut, .model = mod_diamond2) %>%
add_predictions(mod_diamond2)

replaced with this:

grid <- diamonds2 %>%
data_grid(cut, lcarat = -0.515, color = "G", clarity = "SI1") %>%
add_predictions(mod_diamond2)

2. Left out strings.Rmd and rmarkdown-formats.Rmd by deleting them in the _bookdown.yml file - these had complaints about not being rendered as html.

**Comment by eddelbuettel** [comment]
So as a follow-up, on Ubuntu I needed to
- set `eval=FALSE` for all chunks with `str_view()` and `str_view_all()` in the `strings.Rmd` file
- set `eval=FALSE` on the one chunk with `leaflet` in `rmarkdown-formats.Rmd`

in addition to the `ggplot2` fix shown by @Ranae to produce a 408 page pdf.

**Comment by jrneal1** [comment]
I'll try to help before I ask for help.  For those of you having issues with the strings.Rmd file,  you should run the following lines:
```
install.packages("webshot")
library(webshot)
webshot::install_phantomjs()
```
That should get the strings chapter to compile without error.  Additionally, you should look at the packages listed under the Imports section of the DESCRIPTION file and be sure those are installed as well.

Having said that, I could use some help with the following error:
```
Output created: _book/_main.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file '_book/_main.pdf' does not exist
```

**Comment by jrneal1** [comment]
I'll try to help before I ask for help.  For those of you having issues with the strings.Rmd file,  you should run the following lines:
```
install.packages("webshot")
library(webshot)
webshot::install_phantomjs()
```
That should get the strings chapter to compile without error.  Additionally, you should look at the packages listed under the Imports section of the DESCRIPTION file and be sure those are installed as well.

Having said that, I could use some help with the following error:
```
Output created: _book/_main.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file '_book/_main.pdf' does not exist
```

**Comment by jrneal1** [comment]
I'll try to help before I ask for help.  For those of you having issues with the strings.Rmd file,  you should run the following lines:
```
install.packages("webshot")
library(webshot)
webshot::install_phantomjs()
```
That should get the strings chapter to compile without error.  Additionally, you should look at the packages listed under the Imports section of the DESCRIPTION file and be sure those are installed as well.

Having said that, I could use some help with the following error:
Output created: _book/_main.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file '_book/_main.pdf' does not exist

**Comment by eddelbuettel** [comment]
@jrneal1:  you posted essentially the same comment three times. While helpful, maybe consider removing the first two of the three?

**Comment by jrneal1** [comment]
@eddelbuettel : My apologies.  First time poster and I'm apparently using an outdated/unsupported browser.  Hopefully, I've cleaned up the mess.

**Comment by jrneal1** [comment]
@zoe-xanthellae I would prefer to teach you how to fish rather than give you a fish.  At least make a stab at it and post any issues.

**Comment by Ranae** [comment]
I totally agree with @jrneal1 that it is not great to just be giving out fish, but since this book is what actually  teaches fishing in the first place, I'm happy to link to my copy [here](https://github.com/Ranae/AGRON_R4DS/blob/master/week_00/R4DS_pdf.pdf). 

But please do note that this version is missing the chapter on Strings and, ironically, R Markdown Format.

**Comment by zoe-xanthellae** [comment]
Thanks @Ranae, much appreciated!
