### ISSUE TITLE
Use of count() in example in Factors chapter now broken due to change in grouping

### ISSUE THREAD

**Issue by tmelconian** [hadley/r4ds#610]
Referring to the following example in the factors chapter:

```
by_age <- gss_cat %>%
  filter(!is.na(age)) %>%
  group_by(age, marital) %>%
  count() %>%
  mutate(prop = n / sum(n))
```

To work correctly, this example requires that count() will remove one group_by level, like summarise does.  This was true when the book was written, and true as of dplyr 0.5, but is no longer true today, apparently due to https://github.com/tidyverse/dplyr/commit/439e54d555d36d5ced1e723b1cbd6ad9278626d3 and/or related changes.

Could you please update the book and explicitly note that this behavior has changed since earlier versions of dplyr?  It confuses students to have an example which doesn't work, and they already find the implicit removal of group_by levels confusing to start with.

The following variant works for me on both current and 0.50 dplyr:

```
gss_cat %>%
    filter(!is.na(age)) %>%
    group_by(age) %>%
    count(marital) %>%
    mutate(prop=n/sum(n))
```

**Comment by hadley** [comment]
Now fixed, thanks.
