### ISSUE TITLE
ifelse in Functions chapter

### ISSUE THREAD

**Issue by ijlyttle** [hadley/r4ds#62]
Hi,

I don't know if this is intentional or not, but the there is an exercise to detail the differences between `if` and `ifelse`, but you haven't discussed `ifelse` explicitly in this chapter (apologies if this is in an earlier chapter).

**Comment by hadley** [comment]
Right, you need to read the documentation yourself ;)

**Comment by ijlyttle** [comment]
Fair enough :)
