### ISSUE TITLE
Incorrect figure for geom_count on page 100

### ISSUE THREAD

**Issue by weimotu** [hadley/r4ds#632]
Not sure if anyone did point this out. The figure shown at the top on page 100 is a boxplot, but this probably should be a figure for geom_count.

**Comment by hadley** [comment]
Could you please provide a link to the section in the online book? I don't have a physical copy.

**Comment by weimotu** [comment]
Hi,

https://r4ds.had.co.nz/exploratory-data-analysis.html#covariation

The above link will direct you to the section I noted (right below the section title "7.5.2: Two categorical variables"), but the online version is correct. I have also attached a picture showing the issue from the physical copy. Thank you very much for your response; your book does benefit me a lot in my professional development. 

Best regards,
Wei-Mo Tu

**Comment by hadley** [comment]
If the online version is correct, then it means that it's already been fixed. Thanks for the report!
