### ISSUE TITLE
Typo in Fig 3.1: shapes

### ISSUE THREAD

**Issue by ghost** [hadley/r4ds#638]
In [Fig 3.1](http://r4ds.had.co.nz/data-visualisation.html#fig:shapes), which is at the end of [section 3.3: Aesthetic Mappings](http://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings), the shapes are oddly layed out by number (counting by column it goes: 0, 1, 2, 5, 3, 4, 6, 7...). 

Perhaps as a result of this, there are two shapes missing in the description of the interaction of the shape, colour and fill aesthetics.

> The hollow shapes (0-14) have a border determined by `colour`; the solid shapes (15-18) are filled with `colour`; the filled shapes (21-24) have a border of `colour`and are filled with `fill`.

19 and 20 should both be in the solid shapes category.

To fix the typo, the text could read:

> The hollow shapes (0-14) have a border determined by `colour`; the solid shapes (15-20) are filled with `colour`; the filled shapes (21-24) have a border of `colour`and are filled with `fill`.

I expect fixing the image in the figure (with a better layout of the shapes by number) would be a lower priority, but the text fix could occur by itself and solve the typo.

**Comment by hadley** [comment]
Typo was fixed.  The shapes are deliberately laid out in that order to focus on the similarities across the different types.
