### ISSUE TITLE
Documentation: Translation of the entire project into Spanish language

### ISSUE THREAD

**Issue by michaelizer** [hadley/r4ds#644]
Greetings, I would like to contribute to the project by translating it into Spanish. Spanish is my native language so don't panic, but a lot of Spanish speakers are still limited by the language so this is primarily to help them.

Thanks in advance and for your time. Keep up the great work.

**Comment by jbkunst** [comment]
I would love to help if this is needed. https://www.babbel.com/en/magazine/the-10-most-spoken-languages-in-the-world.

**Comment by hadley** [comment]
See http://github.com/edgararuiz/r4ds-es
