### ISSUE TITLE
Single character class for regex metacharacters

### ISSUE THREAD

**Issue by jennybc** [hadley/r4ds#673]
Re: the chapter on strings and how to include a literal metacharacter in the string representation of the regular expression.

It might be worth mentioning that a character class with that single character is an alternative to all the backslashes for many of the metacharacters. I think the resulting regex is more readable. I wish I remembered this more often myself!

Tacking this on at the end of an existing example:

``` r
# To create the regular expression, we need \\
dot <- "\\."

# But the expression itself only contains one:
writeLines(dot)
#> \.

# And this tells R to look for an explicit .
stringr::str_view(c("abc", "a.c", "bef"), "a\\.c")

# And so does this
stringr::str_view(c("abc", "a.c", "bef"), "a[.]c")
```

Preliminary fact collecting

👍 metacharacters for which this works: `$` `.` `|` `?` `*` `+` `(` `)` `[` `{` 

👎 for which this does not work, i.e. they have special meaning inside a character class: `]` `\` `^` `-`

**Comment by hadley** [comment]
Want to do a PR?

**Comment by jennybc** [comment]
PR made
