### ISSUE TITLE
Tibble Subsetting, confusion over partial matching in example

### ISSUE THREAD

**Issue by Cjen1** [hadley/r4ds#683]
A friend of mine had great confusion over the example in the subsetting section tibbles. In terms of the partial matching of column names which was used in the exercisej.

It would be better if it could be made more explicit.

**Comment by hadley** [comment]
Could you please provide a link to the section you're talking about?

**Comment by Cjen1** [comment]
Hi sorry, its been two years and I can't remember. I'll close this issue, and sorry for making such a terrible issue...

**Comment by hadley** [comment]
Don't worry about it; I do it all the time too 😆
