### ISSUE TITLE
4.4 question 2 part 1 

### ISSUE THREAD

**Issue by JamesCuster** [hadley/r4ds#692]
The question ask: "Tweak each of the following R commands so that they run correctly:"

This is the code provided:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

This code works properly without any modification, even though the question suggest that it should not. Looking at answers written by someone else makes it look like "data" used to be "dota". https://jrnold.github.io/r4ds-exercise-solutions/workflow-basics.html#coding-basics

**Comment by hadley** [comment]
Looks like this got fixed (re-broken) since you filed. Thanks for reporting!
