### ISSUE TITLE
mapproj dependency

### ISSUE THREAD

**Issue by lhami** [hadley/r4ds#694]
In the 3.9.1 Exercises, #3 asks about `coord_map()` despite the fact that this function doesn't work without `mapproj` installed, a package that is only suggested in `ggplot2` documentation and isn't mentioned anywhere even in the optional packages for the book. And the book itself says it's not going to go into spatial mapping for lack of time.

It's an interesting question, but it seems like it should either be clarified somewhere that the mapping functionality of `coord_map()` depends on having `mapproj` installed or that the question should be taken out for being a little superfluous.

**Comment by hadley** [comment]
You can answer the question by looking only at the docs, so I don't think the fact there's an extra package involved is a big deal.
