### ISSUE TITLE
A small typo in 11.2

### ISSUE THREAD

**Issue by dongzhuoer** [hadley/r4ds#695]
What does "munge" mean?

**Comment by sedaghatfar** [comment]
munge is not a typo, 

> munge: to manipulate (raw data), especially to convert (data) from one format to another

[https://www.dictionary.com/browse/munge](https://www.dictionary.com/browse/munge)

**Comment by dongzhuoer** [comment]
Wow, I can't find it in Bing Dictionary and Oxford Learner's Dictionaries. Thank you so much!
