### ISSUE TITLE
Tibble naming suggestion

### ISSUE THREAD

**Issue by andrewnguyen42** [hadley/r4ds#700]
It's a bit confusing to give a `tibble` object the name `df` in section [10.3.2](http://r4ds.had.co.nz/tibbles.html#subsetting)

```r
df <- tibble(
  x = runif(5),
  y = rnorm(5)
)

# Extract by name
df$x
#> [1] 0.434 0.395 0.548 0.762 0.254
df[["x"]]
#> [1] 0.434 0.395 0.548 0.762 0.254

# Extract by position
df[[1]]
#> [1] 0.434 0.395 0.548 0.762 0.254
```

In 10.2 a tibble is referred to as 

```r
tb <- tibble(
  `:)` = "smile", 
  ` ` = "space",
  `2000` = "number"
)
```

Seems more consistent to have a tibble called `tb` throughout

**Comment by hadley** [comment]
Tibbles are data frames, and by convention we often call them `df`.
