### ISSUE TITLE
Data Inconsistency in: 24.3.4 Time of year: an alternative approach

### ISSUE THREAD

**Issue by jaedynplewes** [hadley/r4ds#702]
In the second block of code we run:

daily %>% 
  data_grid(wday, date = seq_range(date, n = 13))

However, if I add:

 %>% mutate(wdayCheck = wday(date,label = T))

,then we can see that the wday column and the wdayCheck column do not match. This probably will not affect the visualization given in the chapter much because of the model, however it does seem like a minor error.

**Comment by mine-cetinkaya-rundel** [comment]
Modeling is no longer in scope for the book (for the 2nd edition) so I'll close this issue. Thank you!
