### ISSUE TITLE
Ambiguous wording for exercises in Section 5.3.1.

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#708]
A couple of the exercises in section 5.3.1 have ambiguous wording.

> Sort flights to find the fastest flights.

Does this mean fastest in terms of minimal air_time (`air_time`) or fastest in terms of average air speed (`air_time` / `distance`).

> Which flights travelled the longest? Which travelled the shortest?

I assume that this means the distance travelled (`distance`), but I could also interpret it in terms of time (`air_time`).

**Comment by MaraAlexeev** [comment]
Also for 5.3.1 question 1. How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).

Perhaps this question could have a mention of which variable is of interest. From searching online it, it seems like the dep_time is the one the question is going after. Could be intentionally vague to allow for any variable, but I suspect it meant dep_time.

Sorry if this isn't the right way to make this comment. New to GitHub.
