### ISSUE TITLE
"Cursor" character can be selected in workflow-scripts.

### ISSUE THREAD

**Issue by fryguybob** [hadley/r4ds#711]
In `workflow-scripts.Rmd` the character █ is used to represent the cursor.  If you copy the code sample that character also gets copied.  This led to a confused student today:

```.R
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay)█, !is.na(arr_delay))
```

Some browsers support `user-selected: none` CSS style that could prevent that character from being selected.  Unfortunately, as far as I can tell, you would have to teach pandoc how to do this, so it would require a lot of effort, for small gain.  I put this here in case I am mistaken and there is an easy post processing step that could make the small change.

**Comment by hadley** [comment]
I think you're right and there's no easy way to fix this.
