### ISSUE TITLE
Section 4.4, exercise 1

### ISSUE THREAD

**Issue by rwbaer** [hadley/r4ds#712]
my_variable <- 10
my_varıable
#> Error in eval(expr, envir, enclos): object 'my_varıable' not found

This code purportedly doesn't work, but after seeing nothing wrong, I resorted to cutting and pasting it to the command prompt, and it worked fine.  

Is there supposed to be a capital letter that got inadvertently fixed?

**Comment by sedaghatfar** [comment]
my_varıable has a "ı" instead of "i",  

Open issue https://github.com/hadley/r4ds/issues/605, has an error on Linux/Mac, but not Windows
