### ISSUE TITLE
htmlwidgets required by str_view

### ISSUE THREAD

**Issue by gvwilson** [hadley/r4ds#714]
In Chapter 14 (strings), trying the first regular expression exercises:

```
> library(tidyverse)
> library(stringr)
> str_view(c("a"), "a")
Error in loadNamespace(name) : there is no package called ‘htmlwidgets’
```

Should add warning that `library(htmlwidgets)` is required.

Q: is there a variation of `str_view` that does immediate character output rather than brower output?

**Comment by gillsignals** [comment]
Cross-referencing this previous thread on a similar issue, I'm going to infer that Hadley does not intend to change the warning. 
https://github.com/tidyverse/stringr/issues/196

Perhaps this has changed now though. I ran into the same issue being introduced to regexs on a different MOOC platform.

I can't answer your second Q - apologies. Just noting the relevant link to the original noted issue.

**Comment by hadley** [comment]
stringr issue re-opened since my position since I've changed my mind since then.

**Comment by hadley** [comment]
There isn't a version of `str_view()` that produces character output, but there could be: https://github.com/tidyverse/stringr/issues/370
