### ISSUE TITLE
ND Licensing, Cloning Repos, and Submitting PRs

### ISSUE THREAD

**Issue by kalendar** [hadley/r4ds#720]
I'm submitting this issue wearing my hat as Education Fellow at Creative Commons. I noticed today that you're using a Creative Commons license with the ND condition (CC BY-NC-ND) for R4DS. I know that you actively encourage people to clone the repo, make changes, and submit PRs based on those changes. On its face it would seem that cloning a repo, making changes to its content, and sharing that changed content - when that content is ND licensed - would be a violation of the license. Is this something you've considered? I'd be happy to jump on a Skype or similar to discuss if that would be helpful.

Even though I know an Issue isn't the best venue, please let me say I'm a huge fan of your work. R4DS and the Tidyverse have totally changed my professional life for the better.

**Comment by hadley** [comment]
Unfortunately this is the license that O'Reilly picked (after I signed the copyright away to them). I don't think we would interpret the process of making a pull request as making a derivative of the book.
