### ISSUE TITLE
Exercise 5.7.1.6 Seems like a bad question

### ISSUE THREAD

**Issue by JamesCuster** [hadley/r4ds#725]
I have an issue with this question and it seems like bad methodology. The question reads as follows:

Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time of a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?

My problem with this question is that you first identify these flights that are suspiciously fast, suggesting that they could be data entry errors, which would mean that they would be the shortest flight to that destination. Then afterwards you turn around and say to use these suspect flights to identify flights that are most delayed in the air. Seems to me like you should be comparing the flights with preferably the median, maybe the mean, to find the most delayed flights. Just a thought.

**Comment by hadley** [comment]
I think there's often some level of circularity in data cleaning — you make an initial guess, play with that for a while, and then update it to be more sophisticated.
