### ISSUE TITLE
15.4 explain what `x` and `y` is for `fct_reorder2()`

### ISSUE THREAD

**Issue by dongzhuoer** [hadley/r4ds#728]
For `fct_reorder()`

> `fct_reorder()` takes three arguments:

> * `f`, the factor whose levels you want to modify.
> * `x`, a numeric vector that you want to use to reorder the levels.
> * Optionally, `fun`, a function that's used if there are multiple values of
  `x` for each value of `f`. The default value is `median`.

So it's clear that in

```r
ggplot(relig_summary, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()
```
`relig` is `f`, `tvhours` is `x`.

**Comment by dongzhuoer** [comment]
But for `fct_reorder2()`

> Another type of reordering is useful when you are colouring the lines on a plot. `fct_reorder2()` reorders the factor by the `y` values associated with the largest `x` values. This makes the plot easier to read because the line colours line up with the legend.

In 

```r
ggplot(by_age, aes(age, prop, colour = fct_reorder2(marital, age, prop))) +
  geom_line() +
  labs(colour = "marital")
```

how does `age` & `prop` corresponds to `x` & `y` is not so straightforward.

**Comment by hadley** [comment]
I don't know how to explain it except that they're usually the variables on the `x` and `y` axes of the plot.

**Comment by dongzhuoer** [comment]
I mean that at least the book should tells `fct_reorder2(f, x, y)`
