### ISSUE TITLE
Section 14.3.4 Repetition does not contain an example of *

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#733]
Section "14.3.4 Repetition" introduces the regular expression repetition operators, `*`, `+`, and `?`. However, it does not contain an example of `*`.  

Perhaps the last example
```{r}
str_view(x, 'C[LX]+')
```
should be 
```
str_view(x, 'C[LX]*')
```

**Comment by hadley** [comment]
Hmmm that changes the match in a rather profound way that I'm not sure I want to explain here; but definitely does need to be explained somewhere so folks get a better mental model of what's happening.

**Comment by hadley** [comment]
Now discussed in https://r4ds.hadley.nz/strings.html#introduction-to-regular-expressions
