### ISSUE TITLE
Exercise 23.4.5.3 is unclear

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#744]
I had a hard time making sense of exactly what this question was asking.

> Using the basic principles, convert the formulas in the following two models into functions. (Hint:  start by converting the categorical variable into 0-1 variables.)

> ```
> mod1 <- lm(y ~ x1 + x2, data = sim3)
> mod2 <- lm(y ~ x1 * x2, data = sim3)
> ```

-  What are the expected inputs and outputs of the function? The most reasonable interpretation to me was to mimic the behavior of `model_matrix()` for the special cases of those formulas. But I could also interpret it as asking for a function to estimate the regression.
-  Should it be assumed that `x1` is continuous and `x2` is categorical? Or can `x1` and `x2` be anything. Since `sim3` is explicitly mentioned, I assume that is the case, but I'm not sure.

Some of these ambiguities are reasonable. Having to think through the complexity of how to handle formulas in generality and scoping it down to something feasible is a good lesson. However, the first question seems the most important. I think being more clear about the expected inputs and outputs of the function. Perhaps stating that the exercise is to write a function that does what `model_matrix()` does, but for these specific cases would make it more clear.

**Comment by hadley** [comment]
We're scrapping the modelling chapters for the 2nd edition.
