### ISSUE TITLE
Problems with Exercise 21.5.3

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#747]
The question text is:

> Rewrite map(x, function(df) lm(mpg ~ wt, data = df)) to eliminate the anonymous function.

The code is confusing. What is this code supposed to represent?  What is `x`? It must be a list of data frames, given the function. However, given the variables used in the call to `lm()`, the vector must be subsets of `mtcars`. Also, `x` is defined earlier in the chapter as a list of numeric vectors, adding to the confusion. 

This would work:
```r
mpg %>%
  split(.$cyl)
  map(x, function(df) lm(mpg ~ wt, data = df))
```
Although an example in the chapter already splits by `cyl` and gives this answer. Perhaps `mtcars` could be split by `vs` or `am`? 

Alternatively, replace the question with another

Second, by removing the anonymous function, do you mean to use the shortcut one-sided formula, or actually write a named function. To me, the later is simply syntactic sugar in purrr for creating a one-sided function.

**Comment by hadley** [comment]
The intent was to generate `map(x, lm, formula = mpg ~ wt)`

**Comment by hadley** [comment]
This exercise has been removed since we're moving away from teaching general iteration in favour of teaching a few specific use cases.
