### ISSUE TITLE
Ambiguity in section 21.4.1 Ex. 1

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#752]
The question reads:

> Read the documentation for `apply()`. In the 2d case, what two for loops does it generalize?

The first time, I read "2d case" as the "2nd case", which may owe as much to me spending too much time reading historical works where 2d and 3d were abbreviations for 2nd and 3rd as it does to reading too fast. But the documentation of `apply()` has two paragraphs on what it does when `FUN` returns vectors of the same size, and what it does when `FUN` returns vectors of different sizes.  I suggest using "2-d", or making 2-dimensions more explicit.

I don't know if `apply()` "generalizes" for loops. I think of it more as a replacement.

I think something like the following may be a more clear question that accomplishes the same intent.

> Read the documentation for `apply()`. Rewrite the `apply()` calls using for loops.
> ```r
> df <- tibble(
>   a = rnorm(10),
>   b = rnorm(10),
>   c = rnorm(10),
>   d = rnorm(10)
> )
> apply(df, 1, mean)
> apply(df, 2, mean)
> apply(df, c(1, 2), mean)
```

**Comment by hadley** [comment]
Also going away in 2ed.
