### ISSUE TITLE
6.1 Ctrl + Shift + S

### ISSUE THREAD

**Issue by 1rdsk1** [hadley/r4ds#761]
"nstead of running expression-by-expression, you can also execute the complete script in one step: Cmd/Ctrl + Shift + S. Doing this regularly is a great way to check that you’ve captured all the important parts of your code in the script."

Ctrl + Shift + S  doesnt do this.  Per Rstudio shortcut key list  "Source the current document"

Run current document	Ctrl+Alt+R  according to this list although it doesnt work for me.  So I'm confused!

https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts

**Comment by hadley** [comment]
<img width="735" alt="Screenshot 2020-10-04 at 4 09 16 PM" src="https://user-images.githubusercontent.com/4196/95027146-f52ba180-065b-11eb-9599-bbb20d943f2f.png">

I'm pretty sure that's the correct shortcut.
