### ISSUE TITLE
Exercise 5.4.3 is possibly obselete

### ISSUE THREAD

**Issue by jrnold** [hadley/r4ds#762]
The question reads:

> What does the `one_of()` function do? Why might it be helpful in conjunction with this vector?

The need for `one_of()` is less obvious now that tidy eval exists.

Something like this,
```r
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
select(flights, one_of(vars))
````
 can be replaced by this,
```r
select(flights, vars)
```
or this, to avoid ambiguity,
```r
select(flights, !!!vars)
```

**Comment by hadley** [comment]
`all_of()`/`any_off()` are important because it disambiguates between a df-var called `vars`  and an env var called `vars`.
