### ISSUE TITLE
Confusing order of y & !x in figure 5.1

### ISSUE THREAD

**Issue by EdwinTh** [hadley/r4ds#764]
All the boolean examples are `x` then `y`, except for the first one. This to me is extremely confusing, since `y` is still represented by the right hand side circle of the Venn diagram. I suggest changing it into `!x & y` so it matches both the Venn diagram and the other examples.

<img width="804" alt="screenshot 2019-02-15 at 12 30 38" src="https://user-images.githubusercontent.com/7958036/52854213-173a7e00-311e-11e9-800c-0ad1757a0cec.png">

**Comment by marwahaha** [comment]
The image itself would have to be changed - I'm not sure how it was created.
https://github.com/hadley/r4ds/blob/master/diagrams/transform-logical.png

**Comment by hadley** [comment]
I think it's also in the wrong position? It makes more sense to me to put in the bottom left:

<img width="957" alt="Screenshot 2021-04-18 at 9 55 18 AM" src="https://user-images.githubusercontent.com/4196/115150014-300b8a80-a02c-11eb-93b0-f934b8c3a44b.png">
