### ISSUE TITLE
Generated function calls in diagram wrong

### ISSUE THREAD

**Issue by marcel-burkhard** [hadley/r4ds#770]
https://github.com/hadley/r4ds/blob/ce824d0a33149b34c7b1cacabf8636e132970592/iteration.Rmd#L778

There is a tiny mistake In the linked graphic.

It should be `sd = 1` instead of `sigma = 1` as **rnorm** doesn't have a _sigma_ argument.

**Comment by hadley** [comment]
This diagram will no longer appear in the 2nd edition.
