### ISSUE TITLE
clarification on definition of "tidy dataset"

### ISSUE THREAD

**Issue by aeggers** [hadley/r4ds#771]
In the case study, you turn the who dataset into something that looks to me like table2 in the set of examples at the beginning of the chapter. And yet the first is referred to as tidy but the second is not.

Commonalities: 
-- in both cases we have a country and year column, column(s) identifying what we have counted in that country and year, and then a count.
-- in both cases a row refers to an observation defined as "a property of a country in a year", and there is a single column/variable with values in it.

It seems to me that that original who dataset was closer to table1 in format, so I'm not sure why table1 is called tidy but the original who dataset is not, while table2 is not tidy but the transformed who data is.

I hope that helps clarify things for other readers (and me!). 

Thanks for this book.

**Comment by hadley** [comment]
I think you'd normally think of `cases` and `populations` as variables, not as data points, so `table2` isn't tidy. I don't see the equivalence with `who_tidy`.
