### ISSUE TITLE
challenge data

### ISSUE THREAD

**Issue by DavudDourvash** [hadley/r4ds#772]
Hi, I'm David.
i'm looking for "challenge" data set discussed in this book. 
i couldn't find any link or something else in book show me where "challenge" data is. 
how can i get this data?

**Comment by mbeveridge** [comment]
Hi David,
Are you referring to s11.4.2 in the online book?

[https://r4ds.had.co.nz/data-import.html]...
readr contains a challenging CSV that illustrates both of these problems:
`challenge <- read_csv(readr_example("challenge.csv"))`

**Comment by DavudDourvash** [comment]
Thanks
it solved.
