### ISSUE TITLE
hierarchy chapter: additional pipe

### ISSUE THREAD

**Issue by pachamaltese** [hadley/r4ds#777]
this exercise in L182 has an extra pipe:

```r
 files <- dir("data", pattern = "\\.csv$")
 files %>%
 set_names(., basename(.)) %>%
 map_df(safely(readr::read_csv), .id = "filename") %>%
```

**Comment by marwahaha** [comment]
What do you mean by "pipe" @pachamaltese  ? I know pipe as the up-and-down key, like | .

**Comment by pachamaltese** [comment]
this: `map_df(safely(readr::read_csv), .id = "filename") %>%`
that final `%>%` breaks the code and is not needed at all
