### ISSUE TITLE
venn diagram shading not visible in relational data chapter 

### ISSUE THREAD

**Issue by raynamharris** [hadley/r4ds#778]
I was searching to see if this book discusses venn diagrams at all, and I found a place where a venn diagram is used to illustrate the different joins(https://r4ds.had.co.nz/relational-data.html#mutating-joins). When I was taking a screenshot, I noticed that the venn diagrams are supposed to be shaded grey, but this is not the case when viewing the data without any highlighting. 

Photo 1: grey apparent when the image is highlighted or selected

![IMG_1232](https://user-images.githubusercontent.com/7544197/57253023-8bd8d680-7002-11e9-8f47-36d12f9e9306.png)

Photo 2: grey not visible when the image is not highlighted 

![IMG_1233](https://user-images.githubusercontent.com/7544197/57253026-8f6c5d80-7002-11e9-9934-4db664cf02b8.png)

**Comment by MarcSaric** [comment]
I concur with that. The printed book  (2nd edition) has that same problem, shading is there but almost not visible. This should be fixed in the future, probably by using a somewhat more resolute shade of grey (print looks like 10%).

**Comment by hadley** [comment]
Should be fixed in modern printings of the book.
