### ISSUE TITLE
Parsing problems example mismatch (11.4.2)

### ISSUE THREAD

**Issue by jnudaniel** [hadley/r4ds#780]
The example call to problems(challenge) seems to show problems in the y column parsing dates as logicals, but the description (below) and code fix discuss the issues in the x column (not visible from the output of the function call).
"A good strategy is to work column by column until there are no problems remaining. Here we can see that there are a lot of parsing problems with the x column - there are trailing characters after the integer value. That suggests we need to use a double parser instead."
This should discuss the issues with col y, since those are the ones visible in the example output, or the example output should be moved.

**Comment by BinxiePeterson** [comment]
I just submitted a PR #784 to fix this without checking issues first. I apologize for that.

**Comment by edwinfinlay** [comment]
+1 was going to submit this, a bit confusing.
