### ISSUE TITLE
Travis CI job fails with error about devtools package

### ISSUE THREAD

**Issue by salmasian** [hadley/r4ds#786]
See [this](https://travis-ci.org/hadley/r4ds/builds/546414037) for instance

Here is the pertinent part of the job log:

```
...
label: unnamed-chunk-9
Quitting from lines 296-297 (intro.Rmd) 
Error in loadNamespace(name) : there is no package called 'devtools'
Calls: local ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
...
```

I wonder if the configuration of CI job needs to be changed to specify loading of `devtools` package. After all, the PR that triggers this has nothing to do with packages and config.

**Comment by pabloedug** [comment]
The [same](https://travis-ci.org/hadley/r4ds/builds/553349808?utm_source=github_status&utm_medium=notification) happened to me. I just replaced one word with another and didn't pass the test.
