### ISSUE TITLE
Unclear on list of condiments example

### ISSUE THREAD

**Issue by bensoltoff** [hadley/r4ds#789]
I'm a bit confused by the example in [20.5.3](https://r4ds.had.co.nz/vectors.html#lists-of-condiments) and wondered if the last figure is mislabeled. The contents of the pepper packet are called `x[[1]][[1]]`. That equate to all the grains of pepper being in a single vector, correct?

In my mind, I always thought that `x[[1]][[1]]` would be a single grain of pepper from the packet, each grain indexed by `i` in `x[[1]][[i]]`.

**Comment by hadley** [comment]
Good catch; it's fixed now.
