### ISSUE TITLE
Website blocked by Norton chrome extension

### ISSUE THREAD

**Issue by steffengreup** [hadley/r4ds#791]
Just to let you know, the r4ds url just got blocked by the Norton Security chrome extension for me. Screenshot below. 

The message translates to:
Dangerous Website Blocked. 

This is a known dangerous web page. It is advisible NOT to visit. 

<img width="758" alt="r4ds" src="https://user-images.githubusercontent.com/24866176/61126178-14b13a00-a4ac-11e9-83c6-bb333bf6403c.png">

**Comment by steffengreup** [comment]
I can access the advanced R url without any warning or blocking, by the way

**Comment by hadley** [comment]
Not sure what lead to this, but there haven't been other reports so I assume it's been resolved.
