### ISSUE TITLE
dbplyr footnote or example or exercise

### ISSUE THREAD

**Issue by esuess** [hadley/r4ds#796]
After a year of teaching out of the r4ds book I have received some feedback from a number of students who took my class.  The main issues my students have had while interviewing for jobs is that they have been quizzed on SQL basics.  Having studied the dplyr they know a lot about how to wrangle data and do all of the things one can do with SQL, but they do not know the basic SQL commands SELECT, FROM, WHERE, GROUP BY, etc.

Having recently scrolled down on the main dbplyr page I was very happy to discover *show_query()*, *translate_sql()* and then I found the *RSQLite::dbGetQuery()* command. Using these function to introduce SQL while learning dplyr would be a nice way to learn some SQL.  And it might increase the opportunities of R users in the Data Science career path.

The most important being the *show_query()*.  Giving a footnote to the reader so they know of the existence of the dbplyr package would be great.  Suggesting that using dbplyr can be used to learn some basic relationships between dplyr and SQL.  

Giving a footnote, example, or an exercise would be great to point people in the right direction.

The r-bloggers recent [A Comprehensive Introduction to Working with Databases using R](https://www.r-bloggers.com/a-comprehensive-introduction-to-working-with-databases-using-r/) blog post from August 7 is an excellent reference beyond the [dbplyr](https://dbplyr.tidyverse.org/index.html) webpage.

I have not thought too much about which chapter or what page this should go on.  My first thought is at the end of Section 13.4.7 Other implementations.  Since there is a comparison of dplyr and SQL code given in the table there, this might be a good place to mention that dbplyr can be used to produce the SQL code from the dplyr code.

Here is one example using nycflights13 data.

```{r}
library(pacman)
p_load(tidyverse, dbplyr, nycflights13, RSQLite)

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

copy_to(con, flights)

flights2 <- tbl(con, "flights")

flights2_subset <- flights2 %>% 
  filter(month == 11 | month == 12)

flights2_subset %>% show_query()
```

```{r, echo=TRUE}
summary <- flights2 %>% 
  group_by(carrier) %>% 
  summarise(arr_delay_mean = mean(arr_delay, na.rm = TRUE)) %>% 
  arrange(desc(arr_delay_mean))

summary %>% show_query()
```

**Comment by hadley** [comment]
Plan is to have a whole chapter on this in the 2nd ed.
