### ISSUE TITLE
gather and spread retired

### ISSUE THREAD

**Issue by cswingle** [hadley/r4ds#803]
The sections on gathering and spreading in `tidy.Rmd` should be updated to use `pivot_longer` and `pivot_wider` now that `gather` and `spread` have been retired.

https://github.com/hadley/r4ds/blob/ce824d0a33149b34c7b1cacabf8636e132970592/tidy.Rmd#L144
https://github.com/hadley/r4ds/blob/ce824d0a33149b34c7b1cacabf8636e132970592/tidy.Rmd#L190

**Comment by hathawayj** [comment]
Is there a timeline for updates to the book?

**Comment by markbneal** [comment]
Looks like gather and spread now incorporated, I think this issue could be closed now?

**Comment by cswingle** [comment]
Yep. Looks like it was updated in 24597025005d19b85c74e9f39e36f5da8ac2bc29. Closed, thanks!
