### ISSUE TITLE
A broken link in section 3.6 to the ggplot2 cheatsheet

### ISSUE THREAD

**Issue by orenmn** [hadley/r4ds#810]
Currently the book (https://r4ds.had.co.nz/data-visualisation.html#geometric-objects) says:
"The best way to get a comprehensive overview is the ggplot2 cheatsheet, which you can find at http://rstudio.com/cheatsheets."

The link seems broken to me. I think it has moved to https://rstudio.com/resources/cheatsheets/, which contains a link to the ggplot2 cheatsheet: https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf

**Comment by hadley** [comment]
Now fixed
