### ISSUE TITLE
Update facet_wrap() instructions in favour of vars()

### ISSUE THREAD

**Issue by philip-khor** [hadley/r4ds#816]
In Section 3.5 

> The first argument of facet_wrap() should be a formula, which you create with ~ followed by a variable name (here “formula” is the name of a data structure in R, not a synonym for “equation”). The variable that you pass to facet_wrap() should be discrete.

However, the ggplot2 documentation for `facet_wrap()` states that the formula interface is there for compatibility in favour of `vars()`: 

> For compatibility with the classic interface, can also be a formula or character vector. Use either a one sided formula, ~a + b, or a character vector, c("a", "b").

**Comment by arencambre** [comment]
I agree. Also, in the same section, **facet_grid** uses classic **~** notation, and the documentation suggests R has moved on from that to use **rows, cols**. I suspect the author of this book knows who made the ggplot2 library, so he may have insight on the intended direction. 😁

**Comment by hadley** [comment]
I think `vars()` is going away again. So the book remains correct.
