### ISSUE TITLE
Suggestion for 16. Functions: when to use stop

### ISSUE THREAD

**Issue by richelbilderbeek** [hadley/r4ds#82]
Some feedback as requested [on Hadley's Twitter](https://twitter.com/hadleywickham/status/707920694298869760):

I think the chapter is well written, but lacks one thing: what if the function cannot do its work?

An example is a function to calculate a variance:

```
calculate_variance <- function(x) {
  if (length(x) < 2) {
    stop("calculate_variance: cannot calculate the variance if x has less than two values")
  }
}
```

Note how I add my personal preference for also adding the function its name to the error message. An alternative would be to return NA. But references [1,2] argue you should use stop.

It would be great to see some more guidance on how to handle incorrect function arguments!

Good luck, Richel Bilderbeek

## References

 * [1] 'Rchaeology: Idioms of R Programming' by Paul E. Johnson, January 28, 2015, 4. Function arguments. [...] 2. Check argument values
 * [2] Wickham, Hadley. Advanced R. CRC Press, 2014. Chapter 9, page 149: Fatal errors are raised by 'stop' and force all execution to terminate. Errors are used when there is no way for a function to continue.

**Comment by hadley** [comment]
You definitely shouldn't include the name of the function in the error message because you can easily find it out with `traceback()`.  There is now a whole section that goes into this idea in more detail.

Thanks for the feedback!

**Comment by richelbilderbeek** [comment]
Thanks for the tip!
