### ISSUE TITLE
unnest() no longer fails when attempting to unnest list-columns of different lengths

### ISSUE THREAD

**Issue by mpaulacaldas** [hadley/r4ds#827]
The [last example](https://github.com/hadley/r4ds/blob/master/model-many.Rmd#L545-L552) in the "Many models" chapter no longer fails because `unnest()` recycles the shorter elements from the list-columns:

```r
# Doesn't work because y and z have different number of elements
df2 <- tribble(
  ~x, ~y,           ~z,
   1, "a",         1:2,  
   2, c("b", "c"),   3
)
df2
#> # A tibble: 2 x 3
#>       x y         z        
#>   <dbl> <list>    <list>   
#> 1     1 <chr [1]> <int [2]>
#> 2     2 <chr [2]> <dbl [1]>
df2 %>% unnest(y, z)
#> Warning: unnest() has a new interface. See ?unnest for details.
#> Try `df %>% unnest(c(y, z))`, with `mutate()` if needed
#> # A tibble: 4 x 3
#>       x y         z
#>   <dbl> <chr> <dbl>
#> 1     1 a         1
#> 2     1 a         2
#> 3     2 b         3
#> 4     2 c         3
```
I am not sure if this was an intentional change to the behaviour of `nest()` or if it's a bug that should be reported to tidyr. If the first, then the last section in the "Many models" chapter should be adapted to reflect the new behaviour of the function.

**Comment by FixTestRepeat** [comment]
Hi, I found this ticket for similar reasons. Looks like the example for unnesting doesn't match the explanatory text anymore?

**Comment by hadley** [comment]
This chapter is gone from the 2nd edition.
