### ISSUE TITLE
small error in who dataset tidying

### ISSUE THREAD

**Issue by Skl8em** [hadley/r4ds#831]
Hi,

I believe there is a small typo in the code for tidying the who dataset. 
In [tidy.Rmd](https://github.com/hadley/r4ds/blob/master/tidy.Rmd) line 514 you want to separate by the newly created names_from column from line 506 and not the key column.
Else you still have names like "newrel" when you split using "_".

regards and thanks for the book!
Ben

**Comment by presnell** [comment]
I believe that the correction should actually be to replace "names_from" by "key" on line 506.  The correct code actually appears later on line 548.

**Comment by presnell** [comment]
Looks like the error is repeated in the 2nd exercise in this section.  Again, "names_from" should be replaced by "key" in the call to mutate().

**Comment by hadley** [comment]
This has been rewritten in the 2nd edition.
