### ISSUE TITLE
epub

### ISSUE THREAD

**Issue by zachariae** [hadley/r4ds#846]
I am trying to read the r4ds on my ebook reader (device). With some attitional css, everything looks fine. Only the str_view-chunks are rendered to images that are rather small (width="70%") and unreadable.
I could resize them using css to 100% or 110% using css as well. However, there is a lot of white space that seems to be part the rendered image.

Kind regards, Silke

**Comment by hadley** [comment]
We don't provide an epub version of the book, so you're on your own here, sorry.

**Comment by maciejmotyka** [comment]
Just FYI, it's possible (and quite easy) to render an epub version of the book. There will be quite few missing output chunks in chapter "Strings" and the interactive map from chapter "R Markdown formats" will not be included. The rest of the book renders nicely.

How to:
1. clone the repo
2. open the project in RStudio
3. [optional] discover and install required packages
4. edit files `strings.Rmd` and `rmarkdown-formats.Rmd` and at the very top of these files insert these 3 lines:
```
---
always_allow_html: true
---
```
5. run `bookdown::render_book("index.rmd", bookdown::epub_book())`
6. [optional] convert the epub to mobi using Calibre and enjoy the book on your Kindle
