### ISSUE TITLE
implict coercion in 16.4.2

### ISSUE THREAD

**Issue by mccroweyclinton-EPA** [hadley/r4ds#852]
In one of the examples given in section 16.4.2 the following code is given. 

```
flights_dt <- flights_dt %>% 
  mutate(
    overnight = arr_time < dep_time,
    arr_time = arr_time + days(overnight * 1),
    sched_arr_time = sched_arr_time + days(overnight * 1)
  )
```

Since this book is geared toward novice-intermediate users of R it is my opinion that explicit coercion be preferred over implicit coercion. If implicit coercion is used it is also my opinion that it explicitly pointed out to the reader that implicated coercion was used.

the issue is with coercion that is occurring in this part of the code
```
overnight = arr_time < dep_time,
    days(overnight * 1),    
```

The variable "overnight" is of type logical and 1 is obviously of type numeric/double. R's coercion rules dictate that logical variables multiplied by a numeric variable results in the logical variable being automatically coerced into a numeric variable for binary evaluation.

I had someone ask me what was happening here and I had to explain it to them. My suggestion is to change this to 
```
overnight = arr_time < dep_time,
    days(as.numeric(overnight) * 1),    
```
which makes it apparent to novice readers what the intent is. You can either do that or add a simple inline comment such as 

```
overnight = arr_time < dep_time,
#binary arithmetic of logical variables against numeric variables will cause 
#the logical variable to be automatically coerced into a numeric type
#where FALSE = 0 and TRUE = 1.
    days(overnight * 1),    
```
"

This may make the code uglier but considering that this book was written for beginners I think it may be helpful to remind the readers to be aware of variable classes and coercion rules.

Thanks

**Comment by hadley** [comment]
In general, I agree with you but I think the logical <-> numeric conversion is so important that you have to understand it to use R effectively. We'll make it more clear in the 2nd ed.

**Comment by hadley** [comment]
I changed my mind — I think an `ifelse` makes the logic more clear.
