### ISSUE TITLE
Wrong link in Chapter 9 (wrangle introduction)

### ISSUE THREAD

**Issue by Shurakai** [hadley/r4ds#853]
On that page, the tibble section is introduced via 

> In tibbles, you’ll learn about the variant of the data frame that we use in this book:

where tibble is a link. It links to the vector chapter (Chapter 20), more precisely Section 20.7.3, instead of Chapter 10.

**Comment by hadley** [comment]
This is all being substantially reorganised in the WIP 2nd ed.
