### ISSUE TITLE
Chapter 7.5.3: code date=smaller produces an error message

### ISSUE THREAD

**Issue by kshawnelson** [hadley/r4ds#862]
In chapter 7.5.3, the third box of code says:

> ggplot(data = smaller) +
>   geom_bin2d(mapping = aes(x = carat, y = price))
> 
> # install.packages("hexbin")
> ggplot(data = smaller) +
>   geom_hex(mapping = aes(x = carat, y = price))

This produces an error message:

> Error in ggplot(data = smaller) : object 'smaller' not found

I've managed to get it to work by substituting 'diamonds' for 'smaller', but the graph produced looks slightly different and I'm still in the dark as to what 'smaller' is supposed to do - no explanation is given in the book.

**Comment by rivaquiroga** [comment]
Hi @kshawnelson!
`smaller` is created on section 7.3.1, on the fifth code chunk:

```
smaller <- diamonds %>% 
  filter(carat < 3)
```

**Comment by kshawnelson** [comment]
Aha, amazing, thank you!
