### ISSUE TITLE
14.2.2 Combining strings: Extra space is needed between "Good" and "morning" 

### ISSUE THREAD

**Issue by mbuczynski26** [hadley/r4ds#868]
**The given syntax in the book:** (5th box under 14.2.2)

name <- "Hadley"
time_of_day <- "morning"
birthday <- FALSE 

str_c( 
  "Good", time_of_day, " ", name, 
  if (birthday)" and HAPPY BIRTHDAY", ".")

**Is written to result in:** 

"Good morning Hadley."

**But it really the output is:** 

"Goodmorning Hadley."

**Because there is no space indicated between "Good" and "morning"  **

**Change code to:**

str_c( 
  "Good",  " ", time_of_day, " ", name, 
  if (birthday)" and HAPPY BIRTHDAY", ".")

![14 2 2](https://user-images.githubusercontent.com/67971043/91646742-3c909380-ea07-11ea-96ab-bb7b41606c68.JPG)

**Comment by hadley** [comment]
Looks like this has already been fixed in the dev version
