### ISSUE TITLE
Chapter 7.5.3: code for boxplots generates a different plot than the one shown

### ISSUE THREAD

**Issue by mtcruz** [hadley/r4ds#869]
By the end of [Chapter 7.5.3](https://r4ds.had.co.nz/exploratory-data-analysis.html#two-continuous-variables) there are two boxplots, just above the "7.5.3.1 Exercises" section. When I run the code from the book the output boxplot plot is different from the boxplot shown in the book. 

Here is the code from the book for the first boxplot (+ what you would need to run it "out of the box"):

```
library(tidyverse)

smaller  <- diamonds %>%
  filter(carat < 3)

#code from the book
ggplot(data = smaller, mapping = aes(x = carat, y = price)) + 
  geom_boxplot(mapping = aes(group = cut_width(carat, 0.1)))
```
Here is an image comparing the boxplots from the book and from my RStudio showing how different they are:

![R4DS](https://user-images.githubusercontent.com/52223950/91743141-be122e00-eb8d-11ea-8934-5db2f227e170.png)

As you can (hopefully) see, the boxes (not the axis) seem rotated, more outliers are shown and the thickness of the boxes is different.

<details>
  <summary> [spoiler] Here is the same for the second boxplot </summary>

Code:
```
library(tidyverse)

smaller  <- diamonds %>%
  filter(carat < 3)

#code from the book for second boxplot
ggplot(data = smaller, mapping = aes(x = carat, y = price)) + 
  geom_boxplot(mapping = aes(group = cut_number(carat, 20)))
```

Plot comparison:

![R4DS2](https://user-images.githubusercontent.com/52223950/91743958-1269dd80-eb8f-11ea-9d38-9fad5df227fa.png)

</details>

I think it is unlikely it an issue related to the version of packages being used, as [the book uses 4.0.0](https://r4ds.had.co.nz/introduction.html#colophon) for most of packages and I am using 4.0.2. I don't know if this helps, but here is my "sessioninfo::session_info(c("tidyverse"))" just in case:
<details>
  <summary>[spoiler] sessioninfo::session_info(c("tidyverse"))</summary>

> - Session info ---------------------------------------------------------------------------------------------------------
>  setting  value                       
>  version  R version 4.0.2 (2020-06-22)
>  os       Windows 10 x64              
>  system   x86_64, mingw32             
>  ui       RStudio                     
>  language (EN)                        
>  collate  English_United States.1252  
>  ctype    English_United States.1252  
>  tz       America/Sao_Paulo           
>  date     2020-08-31                  
> 
> - Packages -------------------------------------------------------------------------------------------------------------
>  package      * version  date       lib source        
>  askpass        1.1      2019-01-13 [1] CRAN (R 4.0.2)
>  assertthat     0.2.1    2019-03-21 [1] CRAN (R 4.0.2)
>  backports      1.1.7    2020-05-13 [1] CRAN (R 4.0.0)
>  base64enc      0.1-3    2015-07-28 [1] CRAN (R 4.0.0)
>  BH             1.72.0-3 2020-01-08 [1] CRAN (R 4.0.0)
>  blob           1.2.1    2020-01-20 [1] CRAN (R 4.0.2)
>  broom          0.7.0    2020-07-09 [1] CRAN (R 4.0.2)
>  callr          3.4.3    2020-03-28 [1] CRAN (R 4.0.2)
>  cellranger     1.1.0    2016-07-27 [1] CRAN (R 4.0.2)
>  cli            2.0.2    2020-02-28 [1] CRAN (R 4.0.2)
>  clipr          0.7.0    2019-07-23 [1] CRAN (R 4.0.2)
>  colorspace     1.4-1    2019-03-18 [1] CRAN (R 4.0.2)
>  cpp11          0.2.1    2020-08-11 [1] CRAN (R 4.0.2)
>  crayon         1.3.4    2017-09-16 [1] CRAN (R 4.0.2)
>  curl           4.3      2019-12-02 [1] CRAN (R 4.0.2)
>  DBI            1.1.0    2019-12-15 [1] CRAN (R 4.0.2)
>  dbplyr         1.4.4    2020-05-27 [1] CRAN (R 4.0.2)
>  desc           1.2.0    2018-05-01 [1] CRAN (R 4.0.2)
>  digest         0.6.25   2020-02-23 [1] CRAN (R 4.0.2)
>  dplyr        * 1.0.2    2020-08-18 [1] CRAN (R 4.0.2)
>  ellipsis       0.3.1    2020-05-15 [1] CRAN (R 4.0.2)
>  evaluate       0.14     2019-05-28 [1] CRAN (R 4.0.2)
>  fansi          0.4.1    2020-01-08 [1] CRAN (R 4.0.2)
>  farver         2.0.3    2020-01-16 [1] CRAN (R 4.0.2)
>  forcats      * 0.5.0    2020-03-01 [1] CRAN (R 4.0.2)
>  fs             1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
>  generics       0.0.2    2018-11-29 [1] CRAN (R 4.0.2)
>  ggplot2      * 3.3.2    2020-06-19 [1] CRAN (R 4.0.2)
>  glue           1.4.1    2020-05-13 [1] CRAN (R 4.0.2)
>  gtable         0.3.0    2019-03-25 [1] CRAN (R 4.0.2)
>  haven          2.3.1    2020-06-01 [1] CRAN (R 4.0.2)
>  highr          0.8      2019-03-20 [1] CRAN (R 4.0.2)
>  hms            0.5.3    2020-01-08 [1] CRAN (R 4.0.2)
>  htmltools      0.5.0    2020-06-16 [1] CRAN (R 4.0.2)
>  httr           1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
>  isoband        0.2.2    2020-06-20 [1] CRAN (R 4.0.2)
>  jsonlite       1.7.0    2020-06-25 [1] CRAN (R 4.0.2)
>  knitr          1.29     2020-06-23 [1] CRAN (R 4.0.2)
>  labeling       0.3      2014-08-23 [1] CRAN (R 4.0.0)
>  lattice        0.20-41  2020-04-02 [2] CRAN (R 4.0.2)
>  lifecycle      0.2.0    2020-03-06 [1] CRAN (R 4.0.2)
>  lubridate      1.7.9    2020-06-08 [1] CRAN (R 4.0.2)
>  magrittr       1.5      2014-11-22 [1] CRAN (R 4.0.2)
>  markdown       1.1      2019-08-07 [1] CRAN (R 4.0.2)
>  MASS           7.3-52   2020-08-18 [1] CRAN (R 4.0.2)
>  Matrix         1.2-18   2019-11-27 [2] CRAN (R 4.0.2)
>  mgcv           1.8-32   2020-08-19 [1] CRAN (R 4.0.2)
>  mime           0.9      2020-02-04 [1] CRAN (R 4.0.0)
>  modelr         0.1.8    2020-05-19 [1] CRAN (R 4.0.2)
>  munsell        0.5.0    2018-06-12 [1] CRAN (R 4.0.2)
>  nlme           3.1-149  2020-08-23 [1] CRAN (R 4.0.2)
>  openssl        1.4.2    2020-06-27 [1] CRAN (R 4.0.2)
>  pillar         1.4.6    2020-07-10 [1] CRAN (R 4.0.2)
>  pkgbuild       1.1.0    2020-07-13 [1] CRAN (R 4.0.2)
>  pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 4.0.2)
>  pkgload        1.1.0    2020-05-29 [1] CRAN (R 4.0.2)
>  plogr          0.2.0    2018-03-25 [1] CRAN (R 4.0.2)
>  plyr           1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
>  praise         1.0.0    2015-08-11 [1] CRAN (R 4.0.2)
>  prettyunits    1.1.1    2020-01-24 [1] CRAN (R 4.0.2)
>  processx       3.4.3    2020-07-05 [1] CRAN (R 4.0.2)
>  progress       1.2.2    2019-05-16 [1] CRAN (R 4.0.2)
>  ps             1.3.4    2020-08-11 [1] CRAN (R 4.0.2)
>  purrr        * 0.3.4    2020-04-17 [1] CRAN (R 4.0.2)
>  R6             2.4.1    2019-11-12 [1] CRAN (R 4.0.2)
>  RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 4.0.0)
>  Rcpp           1.0.5    2020-07-06 [1] CRAN (R 4.0.2)
>  readr        * 1.3.1    2018-12-21 [1] CRAN (R 4.0.2)
>  readxl         1.3.1    2019-03-13 [1] CRAN (R 4.0.2)
>  rematch        1.0.1    2016-04-21 [1] CRAN (R 4.0.2)
>  reprex         0.3.0    2019-05-16 [1] CRAN (R 4.0.2)
>  reshape2       1.4.4    2020-04-09 [1] CRAN (R 4.0.2)
>  rlang          0.4.7    2020-07-09 [1] CRAN (R 4.0.2)
>  rmarkdown      2.3      2020-06-18 [1] CRAN (R 4.0.2)
>  rprojroot      1.3-2    2018-01-03 [1] CRAN (R 4.0.2)
>  rstudioapi     0.11     2020-02-07 [1] CRAN (R 4.0.2)
>  rvest          0.3.6    2020-07-25 [1] CRAN (R 4.0.2)
>  scales         1.1.1    2020-05-11 [1] CRAN (R 4.0.2)
>  selectr        0.4-2    2019-11-20 [1] CRAN (R 4.0.2)
>  stringi        1.4.6    2020-02-17 [1] CRAN (R 4.0.0)
>  stringr      * 1.4.0    2019-02-10 [1] CRAN (R 4.0.2)
>  sys            3.4      2020-07-23 [1] CRAN (R 4.0.2)
>  testthat       2.3.2    2020-03-02 [1] CRAN (R 4.0.2)
>  tibble       * 3.0.3    2020-07-10 [1] CRAN (R 4.0.2)
>  tidyr        * 1.1.1    2020-07-31 [1] CRAN (R 4.0.2)
>  tidyselect     1.1.0    2020-05-11 [1] CRAN (R 4.0.2)
>  tidyverse    * 1.3.0    2019-11-21 [1] CRAN (R 4.0.2)
>  tinytex        0.25     2020-07-24 [1] CRAN (R 4.0.2)
>  utf8           1.1.4    2018-05-24 [1] CRAN (R 4.0.2)
>  vctrs          0.3.2    2020-07-15 [1] CRAN (R 4.0.2)
>  viridisLite    0.3.0    2018-02-01 [1] CRAN (R 4.0.2)
>  whisker        0.4      2019-08-28 [1] CRAN (R 4.0.2)
>  withr          2.2.0    2020-04-20 [1] CRAN (R 4.0.2)
>  xfun           0.16     2020-07-24 [1] CRAN (R 4.0.2)
>  xml2           1.3.2    2020-04-23 [1] CRAN (R 4.0.2)
>  yaml           2.2.1    2020-02-01 [1] CRAN (R 4.0.2)
> 
> [1] C:/Users/mateu/Documents/R/win-library/4.0
> [2] C:/Program Files/R/R-4.0.2/library

</details>

**Edit**
I have no experience with bookdown, but I think the problem might be around[ line 473 of the chapter](https://github.com/hadley/r4ds/blob/2df59fd8ae0f78eb45d67e7ab5ef8f4a8c7edb51/EDA.Rmd#L473), however, I was not able to find anything suspicious.
Is this a problem with my RStudio or is there a mistake on the book?

**Comment by hadley** [comment]
The plots in the book look fine now.
