### ISSUE TITLE
orphan table at beginning of section 12.2

### ISSUE THREAD

**Issue by david-romano** [hadley/r4ds#877]
[Section 12.2](https://r4ds.had.co.nz/tidy-data.html#tidy-data-1) introduces `table3` but only refers to it indirectly in line 56 of the [Rmd file](https://github.com/hadley/r4ds/blob/master/tidy.Rmd):

> In this example, only `table1` is tidy. It's the only representation where each column is a variable. 

However, `table3` could also be interpreted as tidy from the point of view of the given definition, although the `rate` column contains expressions as opposed to the numbers yielded by these expressions.  If these expressions are to be interpreted by the reader as an untidy way of storing both case and population values, this should be addressed in the text.

**Comment by hadley** [comment]
It's used in https://r4ds.had.co.nz/tidy-data.html#separating-and-uniting ?
