### ISSUE TITLE
no exponential relationship in 7.5.3

### ISSUE THREAD

**Issue by limes11** [hadley/r4ds#879]
At the beginning of Chapter 7.5.3 it says

"For example, you can see an exponential relationship between the carat size and price of a diamond."

This is incorrect. There is no exponential relationship but a polynomial one. This also becomes clear later in Chapter 24 when log/log plots are considered. In fact, Exercise 2 in 24.2.3 asks specifically to identify this.

**Comment by hadley** [comment]
I was taught that's an exponential relationship, so you're going to need to provide more evidence than "you're incorrect" if you want to convince me of that.

**Comment by limes11** [comment]
Dear Hadley,

Thanks for coming back to this and sorry, I should have probably added more details here. The connection between carat size and price of a diamond is of the form 

price = a * size^b, where a and b are fixed constants.  (***)

(Of course, this only holds approximately.) 
Taking logarithms gives 

log price = log a + b * log size

which is precisely the statement of Exercise 24.2.3 (a_1 = b and a_0 = log a) 

(***) is called a power-law, the variable is the base and the exponent is fixed. Exponential relationship would be something of the form 

price = a * b^size, where a and b are fixed constants.

I hope this makes my point more understandable.

Best Wishes!
