### ISSUE TITLE
Hint in Exercise 1 in 25.2.5

### ISSUE THREAD

**Issue by limes11** [hadley/r4ds#881]
Exercise 1 in 25.2.5 reads as follows: 

"A linear trend seems to be slightly too simple for the overall trend. Can you do better with a quadratic polynomial? How can you interpret the coefficients of the quadratic? (Hint you might want to transform year so that it has mean zero.)"

The hint is confusing. A quadratic polynomial has an additive term. Transforming year to have mean zero makes absolutely no difference, this kind of scaling is done by the polynomial.

**Comment by hadley** [comment]
It doesn't affect the predictions, but it profoundly affects the interpretation.
