### ISSUE TITLE
Semi-join in 25.2.4

### ISSUE THREAD

**Issue by limes11** [hadley/r4ds#882]
The semi-join construction in the last piece of code in 25.2.4 is unnecessarily complicated as "glance" contains all we need. The following simpler code yields the same result:

glance %>% 
  unnest(data)%>%
  filter(r.squared < 0.25) %>%
  ggplot(aes(year, lifeExp, colour = country)) +
  geom_line()

**Comment by hadley** [comment]
That seems like very similar to the code that's already there?

```R
bad_fit <- filter(glance, r.squared < 0.25)

gapminder %>% 
  semi_join(bad_fit, by = "country") %>% 
  ggplot(aes(year, lifeExp, colour = country)) +
  geom_line()
```
