### ISSUE TITLE
Suggestion for copy&paste

### ISSUE THREAD

**Issue by limes11** [hadley/r4ds#883]
My last remark is a suggestion. Feel free to ignore it if you find it unsuitable:

I did a lot of copy&paste to run code. Particularly useful is the option to copy code by clicking on the button/link in the top right corner of a code window. It would be great if the file could be set up in such a way that this action only copies actual code and leaves out the commented-out output. The commented-out part is great to have in the book, but it is rather distracting when being imported into RStudio.

**Comment by hadley** [comment]
See https://github.com/rstudio/bookdown/issues/1072
