### ISSUE TITLE
Printed tibbles in Examples are distorted

### ISSUE THREAD

**Issue by mannymistry** [hadley/r4ds#885]
This morning all tibbles within the examples are showing up as distorted
![Screenshot from 2020-10-03 13-04-17](https://user-images.githubusercontent.com/32691082/94997507-88d87180-0579-11eb-9dc6-faa83b969790.png)

**Comment by hadley** [comment]
Nope, that didn't fix it 😬

**Comment by mannymistry** [comment]
It is looking ok for me now

**Comment by mannymistry** [comment]
![Screenshot from 2020-10-04 17-45-22](https://user-images.githubusercontent.com/32691082/95027807-73427500-0669-11eb-972c-44826d99bf27.png)
