### ISSUE TITLE
Links in book appear broken

### ISSUE THREAD

**Issue by MaraAlexeev** [hadley/r4ds#886]
Reading a few chapters today, I noticed that many links appear broken in the chapters I was reading: 17-20. In the below screen shot, you can see that [strings] looks like it should be a link to the strings chapter, but does nothing.

![Screenshot 2020-10-04 at 4 44 46 PM](https://user-images.githubusercontent.com/39673697/95026689-2064bf80-0661-11eb-9ae2-6b8a240f9267.png)

**Comment by hadley** [comment]
Link: https://r4ds.had.co.nz/vectors.html#character
