### ISSUE TITLE
link to section 14.1 in TOC references chapter 1

### ISSUE THREAD

**Issue by david-romano** [hadley/r4ds#887]
Just noticed this, but can't correct it at the moment, so thought I'd post.

**Comment by hadley** [comment]
What does this mean?

**Comment by david-romano** [comment]
If you click the link to section 14.1 (the introduction to Chapter 14) in
the table of contents that appears on the left, you'll be taken to Chapter
1 (the introduction to the text).  I was going to try my hand at a pull
request, which I've never done, but wanted to document the bad link in case
I couldn't fix it myself.

**Comment by hadley** [comment]
This was fixed in 08a93c7eb4d77039b28994f95c6f0b55ccdb1d1f — it wasn't the link that was bad, but an underlying change in bookdown that required some research and the help of @cderv to fix.
