### ISSUE TITLE
3.7 Statistical transformation stat_summary() example

### ISSUE THREAD

**Issue by maggieklope** [hadley/r4ds#888]
In the third example in section 3.7 of why you might explicitly set a stat by using the stat_summary() function, the book uses the code:

```
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.min = min,
    fun.max = max,
    fun = median
  )
```

However to get the same graph as in the book, one must use:

```
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

**Comment by nzwarts** [comment]
When I run your code I get the warning:
Warning messages:
1: `fun.y` is deprecated. Use `fun` instead. 
2: `fun.ymin` is deprecated. Use `fun.min` instead. 
3: `fun.ymax` is deprecated. Use `fun.max` instead. 

I don't know when they changed it, but apparently the code from the book is correct anyway.
