### ISSUE TITLE
Do not understand a sentence... Typo error?

### ISSUE THREAD

**Issue by cderv** [hadley/r4ds#90]
Hi, 

In the Function part of the book line 218: 

> This is an important part of the “do no repeat yourself” (or DRY) principle. The more repitition you have in your code, the more places you need to remember to update when things change (and they always code!), and the more likely you are to create bugs over time.

I am not sure if *and they always code!* means *and they always __do__!* . It as I understand it.
If not, this sentence is not so clear. 

Sorry I could not improve myself, I am not sure of the meaning. 
Thanks.

**Comment by hadley** [comment]
Should be "do not repeat", and it looks like it's been fixed in the meantime.
