### ISSUE TITLE
Automatic hyperlinking leads to wrong documentation

### ISSUE THREAD

**Issue by sonicdoe** [hadley/r4ds#904]
There are a few cases where automatic hyperlinking leads to the wrong documentation. For example:

- In [1 Introduction](https://r4ds.had.co.nz/introduction.html#running-r-code), when talking about the prompt (`>`), the link leads to the documentation on [binary operators](https://rdrr.io/r/base/Comparison.html).
- In [3 Data visualisation](https://r4ds.had.co.nz/data-visualisation.html#common-problems), when talking about the `+` character in the console, the link leads to the documentation on [arithmetic operators](https://rdrr.io/r/base/Arithmetic.html).
- In [4 Workflow: basics](https://r4ds.had.co.nz/workflow-basics.html#exercises-7), `filter` links to [`stats::filter()`](https://rdrr.io/r/stats/filter.html) instead of [`dplyr::filter()`](https://dplyr.tidyverse.org/reference/filter.html).

**Comment by hadley** [comment]
Yes, these are suboptimal, but unfortunately I don't think that they're worth the effort to fix given the current design of the auto-linking system.

**Comment by hadley** [comment]
Turns out I was wrong; it was simple to fix 😄  Now looks much better in 2e: http://r4ds.hadley.nz/

**Comment by sonicdoe** [comment]
Great to hear 🙌 I see even `filter()` now links to `dplyr::filter()`, despite masking `stats::filter()`.

Do you have a link to the commit? I’m curious how you fixed it.

**Comment by hadley** [comment]
It's rather hacky, but here you go: https://github.com/r-lib/downlit/commit/f7a8f5febe3e51c51cc2181025b8166964583b57
