### ISSUE TITLE
🎆 Ideas for new edition 🎆

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [hadley/r4ds#915]
Here is a rough sketch for chapter outline for the new edition. 

Bolded text: New or moved chapters
Strikethrough: Removed chapters
`*` indicates "consider alternative title"

---

0. **Preface 2e**
1. Introduction

### Whole game

2. Introduction
3. Data visualisation
4. Workflow: basics
5. Data transformation
6. **Data tidying**
7. **Data import**
8. Workflow: scripts
9. Exploratory data analysis: **mention `rowwise()` for summaries of multiple columns**
10. Workflow: projects

### Data types `*`

an alternative title for part: Transform

11. **Introduction: a mix of dplyr and tidyr functionality for dealing with various aspects of real data**
12. Tibbles
13. Relational data & joins
14. **Logicals and numbers** `*`
15. **General vector tools** (?) `*`
16. **Missing values**
17. Strings
18. Factors
19. Dates and times

### Wrangle

20. Introduction
21. **Column-wise operations**: `across()` with `mutate()` and `summarise()`
22. **List columns**: working with `rowwise()`, using many models as an example (?)
23. **Rectangling data**: mostly tidyr -- `unnest()`, `hoist()`, etc.

### Import

24. **Introduction**
25. **Rectangular data** (existing content, moved and reworked)
    - **Getting started**
    - **Parsing a vector**
    - **Parsing a file**
    - **Writing to a file**
26. **Spreadsheets**
    - **Excel**
    - **Google Sheets**
27. **Databases**
28. **Web scraping**
    - **Getting started** (what, why, why not)
    - **rvest and SelectorGadget**
    - **Scraping from a single page**
    - **End with a motivation of why to iterate for multiple pages...**
29. **Other types of data**

### Program

30. Introduction
31. Pipes
32. Functions
33. Vectors
34. Iteration: **Add new section: a case study for web scraping from multiple pages**

### ~Model~

~Introduction~
~Model basics~
~Model building~
~Many models~

### Communicate

35. Introduction
36. R Markdown
37. Graphics for communication
38. R Markdown formats
49. R Markdown workflow

**Comment by hadley** [comment]
Also need preface chapter to note major changes.

**Comment by mitsuoxv** [comment]
I hope that the new version will induce more Excel users to jump to R. It shall reach out to their needs, attract them, and, at the same time, shall not intimidate them. So I agree to add more, especially web scraping, to "Import", but don't agree to move list-columns and nest in earlier pages and to eliminate "Model". It might be better to separate "Wrangle" into "Import 1", "Tidy", "Transform" and "Import 2".

**Comment by go-bayes** [comment]
Wonderful outline! Consider starting with R Markdown earlier because it builds on something people already do (writing) and because people should cultivate good workflow and communication habits early.

**Comment by hadley** [comment]
Locking this issue — this is a place for me and Mine to discuss changes, not an open call for suggestions.
