### ISSUE TITLE
optim doesn't use Newton-Raphson

### ISSUE THREAD

**Issue by bbolker** [hadley/r4ds#930]
The *Model basics* section (23.1) says:

> But there’s a better way to tackle that problem: a numerical minimisation tool called Newton-Raphson search. The intuition of Newton-Raphson is pretty simple: you pick a starting point and look around for the steepest slope. You then ski down that slope a little way, and then repeat again and again, until you can’t go any lower. In R, we can do that with optim():

There are a few problems here.

- `optim` uses Nelder-Mead simplex by default
- it doesn't offer Newton-Raphson as an option (it does have some "quasi-Newton" algorithms such as BFGS)
- what's described here sounds more like *gradient descent* than N-R (although admittedly it could be a rough description of N-R).

**Comment by hadley** [comment]
The modelling chapters are going away in the 2nd edition so this question is now moot 😄
