### ISSUE TITLE
Section 14.3.4 Repetition "{,m}: at most m" is not syntactically valid in regex

### ISSUE THREAD

**Issue by luifrancgom** [hadley/r4ds#933]
In **chapter 14 Strings** > **Section 14.3.4 Repetition** it is mention that:

```
You can also specify the number of matches precisely:

- {,m}: at most m
```

However this syntaxis is not valid:

``` r
library(stringr)
x <- "1888 is the longest year in Roman numerals: MDCCCLXXXVIII"
str_view(x, "C{,1}")
#> Error in stri_locate_first_regex(string, pattern, opts_regex = opts(pattern)): Error in {min,max} interval. (U_REGEX_BAD_INTERVAL, context=`C{,1}`)
```
<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I want to know if this is a typo and if it is what would be the correct expression:

```
You can also specify the number of matches precisely:

- {0,m}: at most m
- {1,m}: at most m
```
Or simply not to include the `at most m` case because it is not documented in regex

**Comment by hadley** [comment]
This is fixed in the WIP 2e.
