### ISSUE TITLE
27.4.3 incorrectly describes data-frame printing

### ISSUE THREAD

**Issue by arencambre** [hadley/r4ds#939]
27.4.3 says "R Markdown prints data frames and matrices as you’d see them in the console", using a code example of `mtcars[1:5, ]`. In fact, it produces a fairly attractive table by default:
![image](https://user-images.githubusercontent.com/411495/112741657-3a66c700-8f4d-11eb-8f7d-af51ae981c51.png)

That is considerably different than the console output of the same command:
```
> mtcars[1:5, ]
                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
```

It later mischaracterizes kable by suggesting that simply using `knitr::kable` causes "additional formatting". In fact, it causes *less* formatting:
![image](https://user-images.githubusercontent.com/411495/112741670-641fee00-8f4d-11eb-9761-0f81b0953396.png)

It might be more correct to explain kable as something that can permit additional formatting options without suggesting that a unadorned use of kable will cause significant enhancements.

**Comment by hadley** [comment]
That's not RMarkdown, that's RStudio. If you knit the doc, you'll see what the book says.
