### ISSUE TITLE
Its not clear at first that R has dataset inside like mpg

### ISSUE THREAD

**Issue by marttoygoy4** [hadley/r4ds#941]
Hello ! 
It would be nice if you would note that ggplot2 puts datasets on your computer... anyways great job THANKS!

**Comment by marttoygoy4** [comment]
Sorry I am not a native English speaker here it is:
![image](https://user-images.githubusercontent.com/80398595/113511111-dd7b9a00-9566-11eb-8072-acf2b25acb32.png)

**Comment by hadley** [comment]
It's not obvious how we could make this more clear — the next sentence tells you about the dataset?
