### ISSUE TITLE
29.7.1 htmlwidgets - failed to load leaflet demo

### ISSUE THREAD

**Issue by zlkrvsm** [hadley/r4ds#954]
I was reading the chapter on Rmarkdown formats and the leaflet demo chunk is not rendering its output.
![image](https://user-images.githubusercontent.com/36903822/118825820-65a4cd00-b891-11eb-831d-bba5c6641cf5.png)

**Comment by mine-cetinkaya-rundel** [comment]
This is loading for me on Chrome, are you able to see this at https://r4ds.hadley.nz/r-markdown-formats.html?q=htmlwi#htmlwidgets?

**Comment by zlkrvsm** [comment]
Yes I've tested it on my phone now and it seems to work.

Den mån 9 maj 2022 19:33Mine Cetinkaya-Rundel ***@***.***>
skrev:

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
