### ISSUE TITLE
Translation of R4DS 2ed in Portuguese

### ISSUE THREAD

**Issue by beatrizmilz** [hadley/r4ds#955]
Hi Hadley! I meant to send this on Twitter but I can't send you DM's. Let me know if there is a better place to send this message other than an GitHub issue.

Are there any plans for the translations for the 2nd edition yet? https://r4ds.hadley.nz/

I would like to know if there is a chance that this edition could be translated to Brazilian Portuguese by the community (when the book is ready).
The first edition was translated by Alta Books, but there are some downsides on this version:
- is not available free and online.
- all the graphic elements are black and white, so reading the chapter for ggplot2 is not really clear
- I did not buy this version, I have the English version by O`Reilly, but people of the community said that some parts of the translations are not really clear/accurate. 

I'm part of the group that translated the datasets used in the book to Brazilian Portuguese: https://cienciadedatos.github.io/dados/ . This group (and more people) are really interested in helping to translate to Portuguese in a way that the book could be available for free online, in a similar way that the community translated to Spanish (@rivaquiroga  <3) .

Let me know what are your thoughts, and thank you so much for your attention.

**Comment by hsvab** [comment]
It would be a great initiative to have the book available in pt-br free and online - it would make a huge difference in access to the material in Brazil, considering that books here are too expensive for the population in general.
And I am willing to help @beatrizmilz on this journey in case you decide to give the Brazilian community this opportunity :-)

**Comment by jeanprado** [comment]
i vouch for this initiative and I'm willing to help with the transition as well! it would be so valuable for our community to have this amazing reference for our r4ds study widely available in the same format the english and spanish version are

**Comment by hadley** [comment]
Unfortunately O'Reilly owns the translation rights, and there's not much I can do about the first edition. However, I can see if they might be open to a community translation for the second edition.

**Comment by mcaines** [comment]
I use R4DS in the courses I teach at University of New Haven.  Sometimes, when it could be helpful, I help students in accessing the book in their native language--like this (for Portuguese) :  [R4DS in Portuguese](https://r4ds-had-co-nz.translate.goog/?_x_tr_sl=auto&_x_tr_tl=pt&_x_tr_hl=en&_x_tr_pto=wapp) .

The feedback I've gotten is that Google Translate does a ***very good*** translation for ESL students.  Many students have said:  *"Google puts a majority of the book in my native language, and my fluency in English helps me understand the rest."*

Generating these Google Translate links is rather easy.  Just go to [https://translate.google.com/](https://translate.google.com/), paste the weblink in the input pane, select the language from the output pane, and then click on the output link.

Hope this helps.

**Comment by beatrizmilz** [comment]
Thanks @hadley !

Hi @mcaines !
I think your suggestion is not the best solution. The translated version by Google has **a lot** mistakes (including names of packages, important concepts and so on). 
Also, if the book is translated (for real, not by google translation) the graphs can be made using the traslated datasets (which we already did with the package [{dados}](https://cienciadedatos.github.io/dados/), and have axes and legends in Portuguese aswell. The package [{dados}](https://cienciadedatos.github.io/dados/) was developed with the contribution of the team that made the Spanish translation of the book.

**Comment by mcaines** [comment]
@beatrizmilz 

My suggestion was meant as an interim solution for ESL students. If you'd rather wait to provide assistance to students who use this book until it is translated into their native language, you may certainly do so.  However, pairing the Google translate link with a cautionary note would get _**at least something**_ that may help your learners.  If it doesn't help them, they can simply not use it, no?

**Comment by hadley** [comment]
I have confirmed with O'Reilly that we can do a community translation of the 2nd edition 😄

**Comment by HektorDannyel** [comment]
@hadley That's super awesome! Let's make it happen, folks.

**Comment by rivaquiroga** [comment]
This is great news!! 🍸

**Comment by beatrizmilz** [comment]
Such great news! Thanks @hadley for taking the time and considering this possibility!


@rivaquiroga I think it will be very helpfull to know more about how team that translated the Spanish version was organized. I will DM you on LatinR slack to ask more about it, ok?

**Comment by rivaquiroga** [comment]
@beatrizmilz, sure!

**Comment by HektorDannyel** [comment]
@beatrizmilz @rivaquiroga Is there room for more contributors? A buddy and I would be delighted to participate!

**Comment by hsvab** [comment]
@hadley Great news!  I'm here to help ;-)

**Comment by najmiehsa** [comment]
@hadley Hi, following this comment https://github.com/hadley/r4ds/issues/955#issuecomment-1048312831
I am interested in translating the second edition of **R for data science** in Persian and I can contribute to french translation as well.
I am looking forward to getting an update on this issue and maybe opening a separate issue for Persian/Contributing to the french translation if needed. Thanks!

**Comment by brunomioto** [comment]
If it's still possible, I would like to help!

**Comment by beatrizmilz** [comment]
Hi @brunomioto! https://github.com/hadley/r4ds/issues/955#issuecomment-1190190582 The book is still a  work-in-progress , so we are waiting for it to be finished to start translating :)

**Comment by gaiobr** [comment]
I would also like to help!

**Comment by gfsarmanho** [comment]
I am also interested in helping with the translation!

**Comment by hadley** [comment]
R4DS 2e is now finished and off to the printers! Would you like me to get permission from O'Reilly for an open-access Portuguese translation?

**Comment by hsvab** [comment]
For sure @hadley!

**Comment by beatrizmilz** [comment]
> R4DS 2e is now finished and off to the printers! Would you like me to get permission from O'Reilly for an open-access Portuguese translation?

What a great news!! Yes Hadley, as @hsvab said, for sure! Thank you so much.

**Comment by rafalopespx** [comment]
Count on me for any help!

**Comment by HektorDannyel** [comment]
That's awesome! Please let us know!

**Comment by hadley** [comment]
Just got permission! 🥳

**Comment by brunomioto** [comment]
> Just got permission! 🥳 

Let's get to work!

**Comment by rafalopespx** [comment]
How we can organize this? I suggest a mailing list or something like

**Comment by beatrizmilz** [comment]
Hi!

Hadley, this is such great news!!

About how to organize this:

- I will talk to @rivaquiroga so we can set up a repository in the https://github.com/cienciadedatos organization (is the same for the Spanish translation);
- We can use GitHub projects and issues in that repository to organize who wants to translate each chapter, who wants to review, what is the status of each chapter, and so on;
- And we also need some place to talk about questions, etc. In the translation of package dados ( https://github.com/cienciadedatos/dados ), we used a channel in Latin-R slack. I don't know if you all are used to Slack. @rafalopespx suggested a mailing list. There is also a possibility of a telegram group, but we could create issues for the questions (in the repository of the translations, not here 😆 ), and other general stuff there. 


As soon as we have the repository for the translation, I will post here and we can focus on working there (so Hadley won't receive so many notifications!)

**Comment by rafalopespx** [comment]
Thanks, @beatrizmilz for organizing this.

To me it works either way, via Slack or via telegram, I think Slack is better cause we can keep the history of the discussions.


Should we open an organization like ciencia de datos to the Portuguese translation?

**Comment by beatrizmilz** [comment]
> Thanks, @beatrizmilz for organizing this.
> 
> To me it works either way, via Slack or via telegram, I think Slack is better cause we can keep the history of the discussions.
> 
> Should we open an organization like ciencia de datos to the Portuguese translation?

We already translated the datasets to use in the book translation, the package dados. We did that translation in the [Ciencia de datos](https://github.com/cienciadedatos)  org and I think is a good idea to create the book translation there as well, so all the translations from Latin America are focused there (the Spanish and Portuguese versions).

I asked Riva to create the repo and give me access, Soon I will be back with any news.

I think Slack is a good option because of that aswell. 
For those who want to contribute to the translation, please join the Latin-R slack: https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc

**Comment by beatrizmilz** [comment]
We have a fork! https://github.com/cienciadedatos/pt-r4ds

And a Slack channel on Latin-R Slack!

**Comment by nextmarte** [comment]
Hey @beatrizmilz I'm interested in helping too, kudos on the initiative!

**Comment by beatrizmilz** [comment]
Hi! We have started working on the translation. 
 
 Some useful links:
- Wiki: https://github.com/cienciadedatos/pt-r4ds/wiki
- Project: https://github.com/orgs/cienciadedatos/projects/2/views/1
- Conversations on [Latin-R slack](https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc), channel #traducao-r4ds
 
I was able to add in the Slack  channel a lot of people from this thread that say that is interested in contributing to the translation, but I was not able to add @gaiobr @gfsarmanho (maybe you can send me an email and we can talk there? milz.bea@gmail.com )

**Comment by beatrizmilz** [comment]
Hi @hadley ! 🎉 
Good news, today we finished translating the text to portuguese: https://cienciadedatos.github.io/pt-r4ds/

We still have to translate some of the diagrams, illustrations, etc. We are working on this. And also some other small fixes.

I have some questions: (@rivaquiroga)
- 1) Is it possible to have an URL similar to the other translations? Like https://es.r4ds.hadley.nz/
- 2) Can this version be linked in the list of translations in the original (english) version of the book? 
- 3) What is the best way to acknowledge the participants of the translation in the book? Is it ok to add a [section about the translation, like the one from the Spanish version](https://es.r4ds.hadley.nz/#sobre-la-traducci%C3%B3n), in the book? 

Thank you!

**Comment by hadley** [comment]
1. Yes! You want `pt.r4ds.hadley.nz`? I'll do some set up on my end and then send you some instructions for you end.
2. Yes please! Do you mind doing a PR?
3. Yes, I think that's perfect

Thanks so much to everyone for their hard work on this!

**Comment by hadley** [comment]
@beatrizmilz is there someone that I could send some little gifts who could then distribute them amongst the translators? Or are y'all too spread out for that too be worthwhile.

**Comment by beatrizmilz** [comment]
> 1. Yes! You want `pt.r4ds.hadley.nz`? I'll do some set up on my end and then send you some instructions for you end.
> 
>     2. Yes please! Do you mind doing a PR?
> 
>     3. Yes, I think that's perfect
> 
> 
> Thanks so much to everyone for their hard work on this!

1. Yes! That would be great! Let me know what I have to do!  :)
2. Ok! I will do a PR!
3. OK! I'll make this edit.


Thank you and the co-authors for allowing us to translate the book!

**Comment by beatrizmilz** [comment]
> @beatrizmilz is there someone that I could send some little gifts who could then distribute them amongst the translators? Or are y'all too spread out for that too be worthwhile.

@hadley I think I can be the focus for that!

**Comment by hadley** [comment]
I think you should just be able to set the CNAME for your GitHub pages to pt.r4ds.hadley.nz and it should now work?

**Comment by beatrizmilz** [comment]
> I think you should just be able to set the CNAME for your GitHub pages to pt.r4ds.hadley.nz and it should now work?

Thanks Hadley! It worked! https://pt.r4ds.hadley.nz/

**Comment by hadley** [comment]
@beatrizmilz can you please shoot me an email to hadley@posit.co so we can figure out how to get y'all some swag 😄
