### ISSUE TITLE
Wrong function reference link in Chapter 12.5

### ISSUE THREAD

**Issue by dshemetov** [hadley/r4ds#963]
Hi. The link to the `fill()` function in the Chapter 12.5 on Missing values points to the fill function ggplot2, while I believe it should point to the [function in tidyr](https://tidyr.tidyverse.org/reference/fill.html) instead. I tried clicking the GitHub actions to edit the source and make a PR, but it kept taking me to the wrong book source files. If someone can point me to the right source file, I can make the PR.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the report! This is now at https://github.com/hadley/r4ds/blob/master/missing-values.Rmd. However, the linking is done automatically so you won't find a hyperlink to edit there. I'll leave the issue open for now so we can figure out how to avoid the incorrect linking.

**Comment by hadley** [comment]
Tracking at https://github.com/r-lib/downlit/issues/135
