### ISSUE TITLE
perfectible grammar in optim() description @ 23.2

### ISSUE THREAD

**Issue by terravivaXXI** [hadley/r4ds#974]
In the following sentence three paragraphs before the end of Section 23.2 the bolded part could be preceded by **and** 

Don’t worry too much about the details of how optim() works. It’s the intuition that’s important here. If you have a function that defines the distance between a model and a dataset **, an** algorithm that can minimise that distance by modifying the parameters of the model, you can find the best model.

**Comment by hadley** [comment]
This chapter is being removed from the second edition
