### ISSUE TITLE
Exercise 4.4

### ISSUE THREAD

**Issue by lucavd** [hadley/r4ds#983]
https://r4ds.had.co.nz/workflow-basics.html#exercises-7

> Why does this code not work?
``` r
my_variable <- 10
my_varıable
#> Error in eval(expr, envir, enclos): object 'my_varıable' not found
```

This code actually __works__ when the locale is set to 'it' (Italian), but not in 'en'. Don't know why.

**Comment by hadley** [comment]
Closing as a duplicate. Not sure why windows behaves this way.
