### ISSUE TITLE
Broken link in "tidy-data" section

### ISSUE THREAD

**Issue by maxdrohde** [hadley/r4ds#990]
At the very bottom of the tidy data section, it reads:
"If you’d like to learn more about non-tidy data, I’d highly recommend this thoughtful blog post by Jeff Leek: http://simplystatistics.org/2016/02/17/non-tidy-data/"

The link is broken -- the updated link should be:
https://simplystatistics.org/posts/2016-02-17-non-tidy-data/

**Comment by hadley** [comment]
Thanks; I've since rewritten this section and it no longer links out.
