### ISSUE TITLE
Unclear question in chapter 7

### ISSUE THREAD

**Issue by edmondo1984** [hadley/r4ds#993]
https://github.com/hadley/r4ds/blob/fc869d3e75cf131b6662323ad301f71b69cc41db/EDA.Rmd#L341

I think it is maybe useful to have an answer page at the end of each chapter?

```R
> ggplot(data = diamonds2) + 
+     geom_histogram(mapping=aes(x=y))
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Warning message:
Removed 9 rows containing non-finite values (stat_bin). 
> ggplot(data = diamonds2) + 
+     geom_barchart(mapping=aes(x=y))
Error in geom_barchart(mapping = aes(x = y)) : 
  could not find function "geom_barchart"
> ggplot(data = diamonds2) + 
+     geom_bar(mapping=aes(x=y))
Warning message:
Removed 9 rows containing non-finite values (stat_count). 
`

**Comment by mine-cetinkaya-rundel** [comment]
I added a clarification to the question that's hopefully helpful. I don't think we're planning to add solutions to the book but there are some community projects that have the answers (that I assume might be updated when 2nd edition is out), e.g. https://jrnold.github.io/r4ds-exercise-solutions/.

**Comment by edmondo1984** [comment]
💯 thank you
