### ISSUE TITLE
r4ds Package

### ISSUE THREAD

**Issue by BB1464** [hadley/r4ds#996]
Good Evening Dear All,
     Please I am trying to install the r4ds package from github but I get the following error below:
checking for file 'C:\Users\USER\AppData\Local\Temp\RtmpOGVxNi\remotes379c206559a2\hadley-r4ds-6bb4c0d/DESCRIPTION' (426ms)
-  preparing 'r4ds': (2.4s)
E  checking DESCRIPTION meta-information ... 
   Malformed Authors@R field:
     <text>:4:5: unexpected symbol
   3:     person("Garrett", "Grolemund", , "garrett@rstudio.com", role = "aut")
   4:     person
          ^   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.

It seems that there is a problem with the description file from your end because I am seeing two comma in the person(author) when I look at the description file from the r4ds repository on github.
 **Please I can I resolve this?**

**Comment by mine-cetinkaya-rundel** [comment]
This should now be resolved with 3f24f0fc07c0b8a178ba2f6fb543385866e5342c, thanks for the report!
